import {WasmBridgeProxy} from '../bridge/wasm-bridge-proxy.js?v=7';
import {NATIVE_SEED_IDS} from './generated/native-seed-ids.js';
import {SCALE0_SCENARIO_BOUNDARY, SCALE0_ABSORBING_SCENARIOS, SCALE0_MASS_GRAVITY_SCENARIOS} from '../config/toggles.js';
import {hasScale0WasmWorkerTransport, MAX_WASM_INTERACTIVE_LATTICE, MAX_DIRECT_WASM_INTERACTIVE_LATTICE} from '../scales/scale0/ui/toolbar/limits.js?v=2';

/** Existing dashboard post-construction policy, before explicit recipe edits. */
export function nativePresetProtocol(id) {
    const boundary = SCALE0_SCENARIO_BOUNDARY[id] || {};
    const fluxGravity = SCALE0_ABSORBING_SCENARIOS.has(id), massGravity = SCALE0_MASS_GRAVITY_SCENARIOS.has(id);
    return {'protocol.boundary': boundary.mode ?? (boundary.reflective ? 1 : 2),
        'protocol.absorbing_boundary': Number(fluxGravity),
        'protocol.latency_field': Number(fluxGravity || massGravity),
        'protocol.field_energy_gravity': Number(fluxGravity),
        ...(massGravity ? {'protocol.genesis': 0} : {})};
}

export function nativeOverrides(recipe) {
    const values = {...(recipe.blank ? {} : nativePresetProtocol(recipe.scenarioId)), ...recipe.overrides};
    if (recipe.blank) {
        values['recipe.blank'] = 1; values['recipe.componentCount'] = recipe.components.length;
        recipe.components.forEach((component, i) => {
            const index = NATIVE_SEED_IDS.indexOf(component.scenarioId);
            if (index < 0) throw new Error('Unknown native ingredient');
            const prefix = `ingredient.${i}.`;
            values[`${prefix}scenario`] = index; values[`${prefix}enabled`] = Number(component.enabled);
            for (const [key, value] of Object.entries({...nativePresetProtocol(component.scenarioId), ...component.overrides}))
                values[prefix + key] = value;
        });
    }
    return values;
}

let nativeCatalog;
async function sourceAnnotations() {
    nativeCatalog ||= fetch(new URL('./generated/native-seeds.json', import.meta.url)).then(async response => {
        if (!response.ok) throw new Error('Native seed schema is unavailable');
        return response.json();
    }).catch(error => { nativeCatalog = null; throw error; });
    return nativeCatalog;
}

export async function describeNativeRecipe(ctx, recipe) {
    const bridge = ctx.bridge;
    if (!bridge?.describeScenarioSeed) throw new Error('The current engine does not expose editable seed descriptions.');
    const catalog = await sourceAnnotations();
    const registered = catalog.presets[`${recipe.scenarioId}@${recipe.size}`];
    // Generated by the same constructor, these exact-size defaults can populate
    // a form without allocating 143 scratch lattices while browsing the catalog.
    // Edits and composites still resolve against a detached live constructor.
    const result = !recipe.blank && !Object.keys(recipe.overrides).length && registered
        ? {...registered, properties: registered.properties.map(p => ({...p, value: nativePresetProtocol(recipe.scenarioId)[p.key] ?? p.value}))}
        : await bridge.describeScenarioSeed(recipe.scenarioId, recipe.size, nativeOverrides(recipe));
    return {...result, schemaIdentity: 'native-seed-2', properties: result.properties.map(property => {
        const match = /^ingredient\.(\d+)\.(.+)$/.exec(property.key);
        const id = match ? recipe.components[Number(match[1])].scenarioId : recipe.scenarioId;
        const key = match ? match[2] : property.key;
        const schema = catalog.presets[`${id}@${recipe.size}`] || catalog.presets[`${id}@33`];
        const annotation = schema?.properties.find(p => p.key === key);
        const defaults = recipe.blank && !match ? {} : nativePresetProtocol(id);
        return {...property, default: defaults[key] ?? property.default,
            ...(annotation ? {source: annotation.source, line: annotation.line,
                defaultExpression: annotation.defaultExpression, dependencies: annotation.dependencies} : {}),
            path: match ? ['components', Number(match[1]), ...(key === 'enabled' ? ['enabled'] : ['overrides', key])]
                : ['overrides', property.key],
        };
    })};
}

export async function prepareNativeRecipe(ctx, recipe, signal) {
    if (ctx.bridge?.isNativeGPU || ctx.bridge?.isNativeWebSocket) {
        if (!ctx.bridge.prepareScenarioSeed) throw new Error('The native server does not support staged seed recipes.');
        return ctx.bridge.prepareScenarioSeed(recipe, signal, nativeOverrides(recipe));
    }
    const worker = hasScale0WasmWorkerTransport() && !ctx._wasmWorkerDisabled;
    const limit = worker ? MAX_WASM_INTERACTIVE_LATTICE : MAX_DIRECT_WASM_INTERACTIVE_LATTICE;
    if (!Number.isInteger(recipe.size) || recipe.size < 3 || recipe.size > limit || recipe.size % 2 === 0)
        throw new Error(`Choose an odd lattice size from 3 to ${limit} for this browser backend.`);
    if (signal?.aborted) throw new Error('Preparation cancelled');
    const overrides = nativeOverrides(recipe);
    if (!worker) return ctx.bridge.prepareScenarioSeed(recipe.scenarioId, recipe.size, overrides);
    return new Promise((resolve, reject) => {
        let finished = false;
        const owner = new WasmBridgeProxy(recipe.size);
        const finish = error => {
            if (finished) return; finished = true;
            signal?.removeEventListener('abort', abort); clearTimeout(timer);
            if (error) {owner.dispose(); reject(error instanceof Error ? error : new Error(String(error)));}
            else {owner.setRunning(false); resolve(owner);}
        };
        const abort = () => finish(new Error('Preparation cancelled'));
        const timer = setTimeout(() => finish(new Error('Seed preparation timed out')), 60000);
        signal?.addEventListener('abort', abort, {once: true});
        owner.beginConfiguration({latticeSize: recipe.size, scenarioId: recipe.scenarioId,
            onInitFailure: finish, onSetupFailure: finish, onRuntimeFailure: finish,
            onConfigurationApplied: ack => finish(ack.ok ? null : new Error(ack.errors.join('; '))),
        });
        if (!owner.setupScenarioSeed(recipe.scenarioId, overrides)) finish(new Error('Could not stage this seed'));
    });
}
