/**
 * Render the Verify header: build stamp, tier counts, and the top-3
 * largest tensions from the hard-prediction tier. Tensions are clickable
 * and scroll to their row. Parametric-tier deltas never appear here (by
 * design — see spec §5).
 */
function escapeHtml(s) {
    return String(s ?? '').replace(/[&<>"']/g, (c) => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
    }[c]));
}

function fmtPull(pull) {
    if (pull == null || !Number.isFinite(pull)) return '—';
    const sign = pull >= 0 ? '+' : '';
    return `${sign}${pull.toFixed(2)}σ`;
}

function fmtPpb(ppb) {
    if (ppb == null || !Number.isFinite(ppb)) return '—';
    const a = Math.abs(ppb);
    if (a < 1) return `${ppb.toFixed(2)} ppb`;
    if (a < 1e3) return `${ppb.toFixed(1)} ppb`;
    return `${(ppb / 1e6).toFixed(2)} ppm`;
}

export function renderHeader(manifest) {
    const stamp = manifest.build_stamp || {};
    const counts = manifest.counts || { hard: 0, parametric: 0, unpredicted: 0 };
    const tensions = manifest.top_tensions || [];

    const tensionList = tensions.length
        ? tensions.map((t) => `
            <li class="verify-tension">
                <a href="#verify-row-${escapeHtml(t.id)}" data-tension-id="${escapeHtml(t.id)}">
                    <span class="verify-tension-question">${escapeHtml(t.question)}</span>
                    <span class="verify-tension-pull">${fmtPull(t.pull)}</span>
                    <span class="verify-tension-delta">${fmtPpb(t.delta_ppb)}</span>
                </a>
            </li>`).join('')
        : '<li class="verify-tension verify-tension--empty">No hard-prediction rows yet.</li>';

    return `
        <header class="verify-header">
            <div class="verify-header-stamp">
                <span class="verify-ver">FTD v${escapeHtml(stamp.ftd_version || '?')}</span>
                <span class="verify-commit">build ${escapeHtml(stamp.commit || '?')}</span>
                <span class="verify-date">${escapeHtml((stamp.timestamp || '').slice(0, 10))}</span>
            </div>
            <p class="verify-header-sub">Generated by <code>scripts/proofs/build_verify_manifest.py</code>. Numbers are static for this build; regenerate the manifest to refresh.</p>
            <ul class="verify-counts">
                <li><strong>${counts.hard}</strong> questions with hard-prediction answers</li>
                <li><strong>${counts.parametric}</strong> questions with parametric answers</li>
                <li><strong>${counts.unpredicted}</strong> questions with no FTD answer</li>
            </ul>
            <div class="verify-tensions">
                <h3 class="verify-tensions-label">Largest deltas in the hard-prediction tier</h3>
                <ul class="verify-tensions-list">${tensionList}</ul>
            </div>
        </header>
    `;
}
