"""
TikZ generator for the spine-theorem-only view of the FTD math node map.

Scope-limited per the plan §honest-constraint to the G* paper's algebraic
content: the 9 spine theorems + 4 subsidiaries + their immediate LEDGER
anchoredges + ledger-depends-on edges between them.  Per-sector / per-LEDGER-claim
densities exceed paper-friendly TikZ budgets; those views live in the
matplotlib SVGs.

Output:
    docs/papers/figures/node_map_tikz.tex   (\\input-able fragment)

Usage:
    python scripts/visualization/render_node_map_tikz.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

REPO_ROOT = Path(__file__).resolve().parents[2]
JSON_PATH = REPO_ROOT / "scripts" / "verification" / "results" / "math_node_map.json"
OUT_PATH = REPO_ROOT / "docs" / "papers" / "figures" / "node_map_tikz.tex"


def _safe(s: str) -> str:
    """Make a string TikZ-label safe."""
    s = (s.replace("\\", "\\textbackslash{}")
          .replace("&", "\\&").replace("%", "\\%").replace("$", "\\$")
          .replace("#", "\\#").replace("_", "\\_").replace("{", "\\{").replace("}", "\\}")
          .replace("^", "\\^{}"))
    if len(s) > 38:
        s = s[:35] + "..."
    return s


def _safe_id(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", s)


def render(data: dict) -> str:
    spine_ids = {t["id"] for t in data["layers"]["theorems"]}
    anchoredgeed_ledger = {t["ledger_ref"] for t in data["layers"]["theorems"]
                       if t.get("ledger_ref")}
    visible = spine_ids | anchoredgeed_ledger

    nodes_by_id = {}
    for layer in ("theorems", "ledger"):
        for n in data["layers"][layer]:
            if n["id"] in visible:
                n["_layer"] = layer
                nodes_by_id[n["id"]] = n

    # Rescale (x, y) from the cached FR layout (in [-0.5, 0.5]) into TikZ
    # coordinates in inches.  10in wide x 6in tall is a comfortable
    # paper-figure footprint.
    if not nodes_by_id:
        return "% (no spine nodes to render)\n"

    xs = [n["x"] for n in nodes_by_id.values()]
    ys = [n["y"] for n in nodes_by_id.values()]
    xmin, xmax = min(xs), max(xs)
    ymin, ymax = min(ys), max(ys)
    width_in, height_in = 5.5, 3.5

    def _proj(n):
        sx = (n["x"] - xmin) / max(xmax - xmin, 1e-9) * width_in
        sy = (n["y"] - ymin) / max(ymax - ymin, 1e-9) * height_in
        return sx, sy

    lines = [
        "% Auto-generated by scripts/visualization/render_node_map_tikz.py",
        "% Source: scripts/verification/results/math_node_map.json",
        f"% Commit: {data.get('source_commit', '?')[:7]}",
        "% Scope: spine-only view (9 spine theorems + 4 subsidiaries + their LEDGER anchoredges).",
        "% Companion: scripts/visualization/results/math_node_map/spine_only.{svg,png}",
        "%",
        "% Requires: \\usepackage{tikz} +",
        "%   \\usetikzlibrary{arrows.meta,positioning,calc,shapes.geometric}",
        "% Standalone preview: wrap in \\documentclass[tikz]{standalone}\\begin{document}\\input{node_map_tikz}\\end{document}",
        "",
        "\\begin{tikzpicture}[",
        "  spine/.style={diamond, draw=blue!80!black, fill=blue!20, thick,",
        "                minimum size=18pt, font=\\small\\bfseries, inner sep=2pt},",
        "  ledger/.style={rectangle, rounded corners=2pt, draw=black!60, fill=gray!10,",
        "                 minimum width=14pt, minimum height=12pt, font=\\footnotesize, inner sep=3pt},",
        "  anchoredge/.style={->, >={Stealth[length=4pt]}, draw=blue!70, thick},",
        "  dep/.style={->, >={Stealth[length=3pt]}, draw=gray!60, dashed, thin},",
        "]",
    ]

    # Node declarations.
    for nid, n in nodes_by_id.items():
        sx, sy = _proj(n)
        style = "spine" if n["_layer"] == "theorems" else "ledger"
        if n["_layer"] == "theorems":
            label = f"{n['id']}"
        else:
            label = f"{n['id']}"
        lines.append(f"  \\node[{style}] ({_safe_id(nid)}) at ({sx:.2f}in,{sy:.2f}in) {{{_safe(label)}}};")

    # Edge declarations.
    for e in data["edges"]:
        if e["from"] not in visible or e["to"] not in visible:
            continue
        if e["type"] == "theorem-anchoredges-ledger":
            style = "anchoredge"
        elif e["type"] == "ledger-depends-on":
            style = "dep"
        else:
            continue
        lines.append(f"  \\draw[{style}] ({_safe_id(e['from'])}) -- ({_safe_id(e['to'])});")

    lines.append("\\end{tikzpicture}")
    lines.append("")

    return "\n".join(lines)


def main():
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    tikz = render(data)
    OUT_PATH.write_text(tikz, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(REPO_ROOT)} ({len(tikz)} chars)")
    print(f"  Standalone preview:")
    print(f"    cd {OUT_PATH.parent}")
    print(f"    echo '\\\\documentclass[tikz]{{standalone}}\\\\usetikzlibrary{{arrows.meta,positioning,calc}}\\\\begin{{document}}\\\\input{{node_map_tikz}}\\\\end{{document}}' > _preview.tex")
    print(f"    pdflatex _preview.tex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
