"""Consistent Gaussian-prime paraboloid and causal-cone reference geometry.

This is an exact arithmetic visualization, not a native FTD propagation
claim.  A Gaussian prime ``z = a + i b`` has norm ``N(z) = a^2 + b^2``.
Two useful lifts must be kept distinct:

* paraboloid: ``(a, b, h=N(z))``;
* null cone:  ``(a, b, tau=sqrt(N(z)))``.

The three-plane lift places the same planar point in the ``xy``, ``yz``,
and ``zx`` coordinate planes of a 3+1 reference cone.  It produces three
great-circle sections, not a full three-dimensional prime distribution.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from enum import Enum
import math
from pathlib import Path
from typing import Iterable, Sequence


class GaussianPrimeKind(str, Enum):
    """Arithmetic class of a Gaussian-prime element."""

    RAMIFIED = "ramified"
    SPLIT = "split"
    INERT = "inert"


@dataclass(frozen=True)
class GaussianPrimePoint:
    """One Gaussian-prime element and its exact integer invariants."""

    a: int
    b: int
    norm: int
    rational_prime: int
    kind: GaussianPrimeKind

    @property
    def radius(self) -> float:
        return math.sqrt(self.norm)

    @property
    def angle(self) -> float:
        return math.atan2(self.b, self.a)

    @property
    def diagonal_offset(self) -> float:
        """Angle from the first-quadrant 45-degree line."""

        return self.angle - 0.25 * math.pi

    @property
    def normalized_components(self) -> tuple[float, float]:
        radius = self.radius
        return self.a / radius, self.b / radius


@dataclass(frozen=True)
class SpacetimePoint:
    """A point in a 3+1 Euclidean-space/Minkowski-time reference chart."""

    x: float
    y: float
    z: float
    tau: float
    plane: str

    @property
    def minkowski_null_residual(self) -> float:
        return self.tau**2 - self.x**2 - self.y**2 - self.z**2


def is_rational_prime(value: int) -> bool:
    """Deterministic primality check sufficient for visualization bounds."""

    if value < 2:
        return False
    if value in (2, 3):
        return True
    if value % 2 == 0 or value % 3 == 0:
        return False
    divisor = 5
    while divisor * divisor <= value:
        if value % divisor == 0 or value % (divisor + 2) == 0:
            return False
        divisor += 6
    return True


def classify_gaussian_prime(a: int, b: int) -> GaussianPrimePoint | None:
    """Classify ``a + i b`` as ramified, split, inert, or non-prime.

    Off-axis elements are Gaussian prime exactly when their norm is a
    rational prime.  Axis elements are Gaussian prime exactly when the
    nonzero coordinate is a rational prime congruent to 3 modulo 4.
    """

    if a == 0 and b == 0:
        return None

    norm = a * a + b * b
    if a != 0 and b != 0:
        if not is_rational_prime(norm):
            return None
        kind = (
            GaussianPrimeKind.RAMIFIED
            if norm == 2
            else GaussianPrimeKind.SPLIT
        )
        return GaussianPrimePoint(a, b, norm, norm, kind)

    coordinate = abs(a) if b == 0 else abs(b)
    if is_rational_prime(coordinate) and coordinate % 4 == 3:
        return GaussianPrimePoint(
            a,
            b,
            norm,
            coordinate,
            GaussianPrimeKind.INERT,
        )
    return None


def gaussian_primes_in_box(bound: int) -> list[GaussianPrimePoint]:
    """Enumerate Gaussian-prime elements in ``[-bound, bound]^2``."""

    if bound < 1:
        raise ValueError("bound must be positive")
    points: list[GaussianPrimePoint] = []
    for a in range(-bound, bound + 1):
        for b in range(-bound, bound + 1):
            point = classify_gaussian_prime(a, b)
            if point is not None:
                points.append(point)
    return points


def rotate_quarter(a: int, b: int) -> tuple[int, int]:
    """Multiply ``a + i b`` by the Gaussian unit ``i``."""

    return -b, a


def reflect_across_diagonal(a: int, b: int) -> tuple[int, int]:
    """Apply ``z -> i conjugate(z)``, reflection across ``a=b``."""

    return b, a


def unit_orbit(a: int, b: int) -> tuple[tuple[int, int], ...]:
    """Return the exact four-step orbit under multiplication by ``i``."""

    orbit: list[tuple[int, int]] = []
    current = (a, b)
    for _ in range(4):
        orbit.append(current)
        current = rotate_quarter(*current)
    return tuple(orbit)


def dihedral_orbit(a: int, b: int) -> frozenset[tuple[int, int]]:
    """Return the D4 orbit generated by quarter-turn and diagonal reflection."""

    reflected = reflect_across_diagonal(a, b)
    return frozenset((*unit_orbit(a, b), *unit_orbit(*reflected)))


def paraboloid_lift(point: GaussianPrimePoint) -> tuple[float, float, float]:
    """Return ``(a, b, N)`` on ``h = a^2 + b^2``."""

    return float(point.a), float(point.b), float(point.norm)


def cone_lift(point: GaussianPrimePoint) -> tuple[float, float, float]:
    """Return ``(a, b, sqrt(N))`` on ``tau^2 = a^2 + b^2``."""

    return float(point.a), float(point.b), point.radius


def three_plane_lifts(point: GaussianPrimePoint) -> tuple[SpacetimePoint, ...]:
    """Return the ``xy``, ``yz``, and ``zx`` sections of a 3+1 null cone."""

    a = float(point.a)
    b = float(point.b)
    tau = point.radius
    return (
        SpacetimePoint(a, b, 0.0, tau, "xy"),
        SpacetimePoint(0.0, a, b, tau, "yz"),
        SpacetimePoint(b, 0.0, a, tau, "zx"),
    )


def moore_minimum_ticks(x: int, y: int, z: int = 0) -> int:
    """Exact 26-neighbour graph distance, distinct from Euclidean radius."""

    return max(abs(x), abs(y), abs(z))


def geometry_diagnostics(points: Sequence[GaussianPrimePoint]) -> dict[str, float | int]:
    """Return exact/finite diagnostics used by the CLI and tests."""

    null_residual = max(
        (
            abs(tau * tau - a * a - b * b)
            for a, b, tau in map(cone_lift, points)
        ),
        default=0.0,
    )
    spacetime_residual = max(
        (
            abs(lift.minkowski_null_residual)
            for point in points
            for lift in three_plane_lifts(point)
        ),
        default=0.0,
    )
    return {
        "points": len(points),
        "ramified": sum(point.kind is GaussianPrimeKind.RAMIFIED for point in points),
        "split": sum(point.kind is GaussianPrimeKind.SPLIT for point in points),
        "inert": sum(point.kind is GaussianPrimeKind.INERT for point in points),
        "max_2_plus_1_null_residual": null_residual,
        "max_3_plus_1_null_residual": spacetime_residual,
    }


def _scatter_by_kind(ax, points: Iterable[GaussianPrimePoint], coordinates) -> None:
    colors = {
        GaussianPrimeKind.RAMIFIED: "#F4D35E",
        GaussianPrimeKind.SPLIT: "#4EA5D9",
        GaussianPrimeKind.INERT: "#EE6C4D",
    }
    labels = {
        GaussianPrimeKind.RAMIFIED: "ramified p=2",
        GaussianPrimeKind.SPLIT: "split p=1 mod 4",
        GaussianPrimeKind.INERT: "inert p=3 mod 4",
    }
    sizes = {
        GaussianPrimeKind.RAMIFIED: 34,
        GaussianPrimeKind.SPLIT: 8,
        GaussianPrimeKind.INERT: 22,
    }
    for kind in GaussianPrimeKind:
        selected = [point for point in points if point.kind is kind]
        if not selected:
            continue
        xyz = [coordinates(point) for point in selected]
        ax.scatter(
            [entry[0] for entry in xyz],
            [entry[1] for entry in xyz],
            [entry[2] for entry in xyz],
            s=sizes[kind],
            c=colors[kind],
            alpha=0.82,
            label=labels[kind],
            depthshade=False,
        )


def render_reference_figure(
    points: Sequence[GaussianPrimePoint],
    output_path: Path,
) -> None:
    """Render planar, 2+1 cone, and normalized 3+1-section views."""

    import matplotlib.pyplot as plt
    import numpy as np

    if not points:
        raise ValueError("at least one Gaussian prime is required")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure = plt.figure(figsize=(18, 6.4), constrained_layout=True)

    planar = figure.add_subplot(1, 3, 1)
    planar.set_aspect("equal")
    planar.axhline(0.0, color="#666666", linewidth=0.7)
    planar.axvline(0.0, color="#666666", linewidth=0.7)
    limit = max(max(abs(point.a), abs(point.b)) for point in points)
    planar.plot([-limit, limit], [-limit, limit], "--", color="#999999", linewidth=0.8)
    planar.plot([-limit, limit], [limit, -limit], "--", color="#999999", linewidth=0.8)
    planar_colors = {
        GaussianPrimeKind.RAMIFIED: "#F4D35E",
        GaussianPrimeKind.SPLIT: "#4EA5D9",
        GaussianPrimeKind.INERT: "#EE6C4D",
    }
    for kind in GaussianPrimeKind:
        selected = [point for point in points if point.kind is kind]
        planar.scatter(
            [point.a for point in selected],
            [point.b for point in selected],
            s=20 if kind is not GaussianPrimeKind.SPLIT else 8,
            color=planar_colors[kind],
            alpha=0.82,
            label=kind.value,
        )
    planar.set_title("Gaussian-prime plane\nperiod-4 rotations; D4 reflection pairs")
    planar.set_xlabel("a")
    planar.set_ylabel("b")
    planar.legend(loc="upper right", fontsize=8)

    cone = figure.add_subplot(1, 3, 2, projection="3d")
    radial = np.linspace(0.0, math.sqrt(2.0) * limit, 22)
    theta = np.linspace(0.0, 2.0 * math.pi, 65)
    rr, tt = np.meshgrid(radial, theta)
    cone.plot_surface(
        rr * np.cos(tt),
        rr * np.sin(tt),
        rr,
        color="#91C4F2",
        alpha=0.08,
        linewidth=0.0,
    )
    _scatter_by_kind(cone, points, cone_lift)
    cone.set_title("Consistent 2+1 lift\n$\\tau^2=a^2+b^2$")
    cone.set_xlabel("a")
    cone.set_ylabel("b")
    cone.set_zlabel("$\\tau=\\sqrt{N}$")
    cone.view_init(elev=24, azim=-56)
    cone.legend(loc="upper left", fontsize=7)

    sphere = figure.add_subplot(1, 3, 3, projection="3d")
    polar = np.linspace(0.0, math.pi, 28)
    azimuth = np.linspace(0.0, 2.0 * math.pi, 56)
    pp, aa = np.meshgrid(polar, azimuth)
    sphere.plot_wireframe(
        np.sin(pp) * np.cos(aa),
        np.sin(pp) * np.sin(aa),
        np.cos(pp),
        color="#999999",
        alpha=0.12,
        linewidth=0.35,
        rstride=3,
        cstride=4,
    )
    plane_colors = {"xy": "#4EA5D9", "yz": "#59A14F", "zx": "#B07AA1"}
    for plane in ("xy", "yz", "zx"):
        normalized = []
        for point in points:
            lift = next(item for item in three_plane_lifts(point) if item.plane == plane)
            normalized.append((lift.x / lift.tau, lift.y / lift.tau, lift.z / lift.tau))
        sphere.scatter(
            [entry[0] for entry in normalized],
            [entry[1] for entry in normalized],
            [entry[2] for entry in normalized],
            s=5,
            alpha=0.35,
            color=plane_colors[plane],
            label=plane,
            depthshade=False,
        )
    sphere.set_title("Normalized 3+1 cross-section\nthree great circles, not a full sphere")
    sphere.set_xlabel("x/$\\tau$")
    sphere.set_ylabel("y/$\\tau$")
    sphere.set_zlabel("z/$\\tau$")
    sphere.legend(loc="upper right", fontsize=8)
    sphere.set_box_aspect((1, 1, 1))

    figure.suptitle(
        "Gaussian-prime causal-cone reference geometry\n"
        "[THEOREM: lifts]  [SELECTION: time reading]  [OPEN: native Moore/Lorentz bridge]",
        fontsize=14,
    )
    figure.savefig(output_path, dpi=220, bbox_inches="tight")
    plt.close(figure)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bound", type=int, default=30)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent
        / "results"
        / "gaussian_prime_cone"
        / "gaussian_prime_causal_cone.png",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    points = gaussian_primes_in_box(args.bound)
    render_reference_figure(points, args.output)
    diagnostics = geometry_diagnostics(points)
    print("Gaussian-prime reference geometry")
    for key, value in diagnostics.items():
        print(f"  {key}: {value}")
    print(f"  output: {args.output}")
    print("  status: exact geometry; physical time identification remains OPEN")


if __name__ == "__main__":
    main()
