// Generated by scripts/phi_v2_lattice/hydro/experiments/generate_native_header.py; do not edit.
#pragma once
#include <cstdint>
namespace ftd::hydro::tables {
constexpr int N_VEL = 24, N_PHASE = 4, N_POL = 2, N_CHANNELS = 192;
constexpr std::int8_t VELOCITY[24][3] = {{1,0,0}, {1,0,0}, {-1,0,0}, {-1,0,0}, {0,1,0}, {0,1,0}, {0,-1,0}, {0,-1,0}, {0,0,1}, {0,0,1}, {0,0,-1}, {0,0,-1}, {1,1,0}, {1,-1,0}, {-1,1,0}, {-1,-1,0}, {1,0,1}, {1,0,-1}, {-1,0,1}, {-1,0,-1}, {0,1,1}, {0,1,-1}, {0,-1,1}, {0,-1,-1}};
constexpr bool IS_FACE[24] = {true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false};
constexpr std::int8_t TARGET_KIND[24] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
constexpr std::int8_t TARGET_OFFSET[24][3] = {{0,0,0}, {0,0,0}, {-1,0,0}, {-1,0,0}, {0,0,0}, {0,0,0}, {0,-1,0}, {0,-1,0}, {0,0,0}, {0,0,0}, {0,0,-1}, {0,0,-1}, {0,0,0}, {0,-1,0}, {-1,0,0}, {-1,-1,0}, {0,0,0}, {0,0,-1}, {-1,0,0}, {-1,0,-1}, {0,0,0}, {0,0,-1}, {0,-1,0}, {0,-1,-1}};
constexpr std::int8_t TARGET_INDEX[24][2] = {{0,0}, {0,0}, {0,0}, {0,0}, {1,0}, {1,0}, {1,0}, {1,0}, {2,0}, {2,0}, {2,0}, {2,0}, {2,0}, {2,1}, {2,1}, {2,0}, {1,0}, {1,1}, {1,1}, {1,0}, {0,0}, {0,1}, {0,1}, {0,0}};
constexpr int SC_SOURCES = 4, FCC_SOURCES = 2;
constexpr std::int8_t SOURCE_SC[3][4][4] = {{{0,0,0,0}, {0,0,0,1}, {1,0,0,2}, {1,0,0,3}}, {{0,0,0,4}, {0,0,0,5}, {0,1,0,6}, {0,1,0,7}}, {{0,0,0,8}, {0,0,0,9}, {0,0,1,10}, {0,0,1,11}}};
constexpr std::int8_t SOURCE_FCC[3][2][2][4] = {{{{0,0,0,20}, {0,1,1,23}}, {{0,0,1,21}, {0,1,0,22}}}, {{{0,0,0,16}, {1,0,1,19}}, {{0,0,1,17}, {1,0,0,18}}}, {{{0,0,0,12}, {1,1,0,15}}, {{0,1,0,13}, {1,0,0,14}}}};
constexpr unsigned char TABLE_HASH[32] = {171, 242, 92, 242, 96, 114, 192, 59, 91, 120, 101, 254, 132, 211, 243, 28, 39, 2, 99, 210, 192, 97, 231, 191, 61, 129, 226, 125, 120, 59, 83, 117};
constexpr unsigned char ENCODING_HASH[32] = {60, 16, 193, 52, 218, 223, 58, 166, 243, 47, 49, 186, 88, 137, 150, 227, 196, 117, 90, 246, 125, 76, 128, 77, 181, 103, 245, 196, 179, 97, 39, 12};
constexpr unsigned char LAW_HASH[32] = {184, 145, 189, 2, 148, 91, 11, 214, 206, 34, 102, 66, 78, 175, 125, 42, 224, 70, 110, 167, 216, 87, 36, 99, 13, 160, 100, 175, 115, 116, 138, 195};
constexpr const char* LAW_ID = "phi-hydro-staged-candidate-1";
}  // namespace ftd::hydro::tables
