import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { isCurrentScale0TelemetryMeta, readScale0TotalEnergy, readScale0WaveEnergy, readScale0FieldEnergy } from '../js/telemetry/scale0-read.js';
const read=n=>fs.readFileSync(new URL('../js/scales/scale0/ui/overlays/'+n,import.meta.url),'utf8');
const strip=s=>s.replace(/^import[\s\S]*?from\s+['"][^'"]+['"];\s*/gm,'').replace(/export\s+/g,'');
const noop=()=>{};const noRead=()=>{throw Error('unexpected full reduction');};
const cl={contains:()=>false,add:noop,remove:noop,toggle:noop};
function flux() {
 let tick=2**31+7;const calls=[];const d={key:'fluxJ',sample:()=>new Float64Array([1,2,3,4])};
 const P=vm.runInNewContext(strip(read('flux-slice-panel.js'))+'\nFluxSlicePanel',{
 FIELD_DRIVERS:[d],DEFAULT_FIELD_OVERRIDE:{fluxJ:'on'},getScale0State:()=>({currentScenarioId:'fixture'}),isPanelLive:()=>true,isScale0AuthoritativeGenerationReady:()=>true,getFieldStateSnapshot:()=>({}),axisIndex:()=>0,DENSE_THRESHOLD:2,FLOOR_FRAC:1e-6}).prototype;
 const bridge={latticeSize:2,currentTick:()=>tick,getDiagnostics:noRead};
 const f={_emptyInapplicable:false,_dockHost:{},_panel:{classList:cl},_fields:{fluxJ:{row:{classList:cl},slots:{}}},visible:true,_sub:{},frameCount:0,updateEvery:2,_lastN:2,_lastSimTick:0,_axisVisible:{xy:true,xz:true,yz:true},_fieldOverride:{fluxJ:'on'},_fieldGlobalMax:{fluxJ:0},_scratch:{},_maxDecay:0.98,getBridge:()=>bridge,_refreshChip:noop,_refreshResetButton:noop,_isFieldRowVisible:()=>true,_buildFrameSampleCache:()=>{calls.push('sample');return{};},_paintSlice:(...a)=>calls.push(a[6])};
 return{P,f,bridge,calls,tick:v=>tick=v,run:()=>P.update.call(f)};
}
test('Flux scalar clock preserves >2^31 precision, cadence and three paints',()=>{const x=flux();x.run();assert.equal(x.calls.length,0);x.run();assert.deepEqual(x.calls,['sample',2**31+7,2**31+7,2**31+7]);});
test('unknown clocks cannot synthesize zero or erase valid rewind baseline',()=>{const x=flux();x.f._lastSimTick=20;for(const t of [undefined,null,NaN,Infinity,-1,1.5,'3',Number.MAX_SAFE_INTEGER+1]){x.tick(t);x.calls.length=0;x.f.frameCount=1;x.run();assert.deepEqual(x.calls,['sample',null,null,null]);assert.equal(x.f._lastSimTick,20);}x.tick(0);x.f.frameCount=1;x.f._fieldGlobalMax.fluxJ=100;x.run();assert.equal(x.f._lastSimTick,0);assert.equal(x.f._fieldGlobalMax.fluxJ,4);});
test('both empty and painted Flux captions preserve unavailable clocks',()=>{const x=flux();const readout={textContent:''};const ctx={fillRect:noop,drawImage:noop};const slot={rgbaBuf:new Uint8Array(16),ctx,canvas:{width:2,height:2},readout,imgData:{},currentN:2,tmpCanvas:{width:2},tmpCtx:{putImageData:noop}};const f={_fields:{fluxJ:{slots:{xy:slot}}},_dockMode:true,_expanded:false,_canvasPx:2,_fmt:String};const drv={key:'fluxJ',ramp:(t,out)=>{out[0]=t;out[1]=0;out[2]=0;}};x.P._paintSlice.call(f,drv,'xy',null,2,1,1,null,true);assert.match(readout.textContent,/tick unavailable/);x.P._paintSlice.call(f,drv,'xy',new Float64Array([1,0,0,0]),2,1,1,null,true);assert.match(readout.textContent,/tick unavailable/);assert.equal(slot.rgbaBuf[0],255);});
function update(name,end,g){const s=read(name),i=s.indexOf('    function update() {');return vm.runInNewContext(s.slice(i,s.indexOf(end,i))+'\nupdate',g);}
function time(meta,diag){const g={updateRetainedReadout:(container,html)=>{container.innerHTML=html;},updateTimeReadout:(container,markup)=>g.updateRetainedReadout(container,String(markup)),getBridge:()=>g.bridge,bridge:{getDiagnostics:noRead,getEnergyAudit:noRead,capabilities:{scale0:{latticeSize:3}}},telemetryHub:{s0:{diag},getResetVersion:()=>0,getScale0TelemetryMeta:()=>meta,publishScale0ProperTimeMetrics:noop},timeSourceBoundary:()=>null,sourceBoundary:null,bridgeId:null,resetVersion:0,resetTwin:noop,isPanelLive:()=>true,host:{},BASE_STRIDE:1,TARGET_AXIS_SAMPLES:33,readEngineToggle:()=>false,cardA:{},cardB:{},cardC:{},cardE:{},cardF:{},renderD:noop,renderCardA:(a,m)=>g.metrics=m,renderCardB:noop,renderCardC:noop,renderCardE:noop,renderCardF:noop,sampleField:()=>({hasField:false}),sampleProperTimeMetrics:()=>({hasField:false}),visibleTwin:()=>({}),twin:{},lastMetrics:null,lastPhysicalTime:null};return{g,run:update('time-panel.js','    // Defer the rAF',g)};}
test('Time keeps qualified physicalTime without unused audit computation',()=>{const x=time({tick:9,stale:false},{tick:9,physicalTime:4.5,dt:0.5});x.run();assert.equal(x.g.metrics.physicalTime,4.5);x.g.telemetryHub.s0.diag={tick:9,physicalTime:4.75,dt:0.5};x.run();assert.equal(x.g.metrics.physicalTime,4.75,'no tick-only cache');});
test('Time missing/stale provenance never polls or invents a zero baseline',()=>{for(const m of [null,{tick:8,stale:true}]){const x=time(m,{tick:8});x.run();assert.match(x.g.cardA.innerHTML,/unavailable/);assert.equal(x.g.lastPhysicalTime,null);}});
function thermo(auditMeta){const meta={tick:8,stale:false,source:'fixture',sourceEpoch:1};const g={bridge:{latticeSize:3,getDiagnostics:noRead,getEnergyAudit:noRead},getBridge:()=>g.bridge,telemetryHub:{s0:{diag:{tick:8,manifested:0},audit:{fieldEnergy:3,waveEnergy:6,dynamicEnergy:9}},getResetVersion:()=>0},bridgeId:null,resetVersion:0,lastHistoryStamp:null,lastRenderStamp:null,mHist:[],isPanelLive:()=>true,host:{},currentScale0Meta:k=>k==='diagnostics'?meta:auditMeta,readScale0WaveEnergy,readScale0FieldEnergy,readScale0TotalEnergy,slider:{value:'0.02'},C2:1/3,telemetryStamp:m=>m?String(m.tick):'waiting',panel:{dataset:{}},renderCount:0,phaseEl:{style:{}},barEl:{style:{}},mpctEl:{},rowsEl:{},rowHTML:(k,v)=>k+'='+v+';',heat:{width:3,height:3,getContext:()=>({clearRect:noop})},hmaxEl:{},renderHistory:noop};return{g,run:update('thermo-panel.js','    const armSub',g)};}
test('Thermo missing audit provenance does not trigger discarded fallback',()=>{const x=thermo(null);x.run();assert.match(x.g.rowsEl.innerHTML,/E total=—/);assert.equal(x.g.mHist[0].value,0);});
test('Thermo keeps qualified audit and unchanged-render guard',()=>{const x=thermo({tick:8,stale:false});x.run();assert.match(x.g.rowsEl.innerHTML,/E total=9.000/);x.run();assert.equal(x.g.renderCount,1);});
test('Thermo mixed audit remains independently read without current-total relabeling',()=>{const x=thermo({tick:7,stale:false});x.run();assert.equal(x.g.panel.dataset.telemetryState,'mixed');assert.match(x.g.rowsEl.innerHTML,/E total=—/);assert.match(x.g.rowsEl.innerHTML,/=3.000/);});
test('Scale Context uses qualified hub scalar and preserves knot source',()=>{let meta={tick:10,stale:false};const hub={s0:{diag:{manifested:7}},getScale0TelemetryMeta:()=>meta};const s=read('scale-context-panel.js'),i=s.indexOf('function readTelemetry(');const f=vm.runInNewContext(s.slice(i,s.indexOf('export function mountScaleContextPanel',i))+'\nreadTelemetry',{telemetryHub:hub,isCurrentScale0TelemetryMeta});const bridge={capabilities:{scale0:{getScale0Diagnostics:noRead,getScale0KnotTelemetry:()=>({count:1,size:[4]})}}};assert.equal(f(()=>bridge).manifested,7);assert.equal(f(()=>null).manifested,null);assert.equal(f(()=>({})).manifested,null);assert.equal(f(()=>bridge).maxClusterSize,4);for(const invalid of [null,{tick:10,stale:true},{tick:NaN},{tick:10,status:'unavailable'}]){meta=invalid;assert.equal(f(()=>bridge).manifested,null);}meta={tick:11,stale:false};hub.s0.diag={manifested:0};assert.equal(f(()=>bridge).manifested,0);});
