// FTD Ontology Atlas — pedagogical content + epistemic tags.
// SINGLE SOURCE OF TRUTH for what each layer means and its honest status.
// Tags are canonical (LEDGER / SPEC). Do NOT soften [SELECTION]/[OPEN]/declined
// into theorem-like language: J is real, Ψ is bookkeeping, M is declined.

export const GROUPS = [
  { id: 'full',          label: 'Full · ontic-real', color: '#378ADD' },
  { id: 'manifestation', label: 'Manifestation',     color: '#639922' },
  { id: 'derived',       label: 'Derived · spatial', color: '#1D9E75' },
  { id: 'imposed',       label: 'Imposed',           color: '#9c9a92' },
  { id: 'partial',       label: 'Partial access',    color: '#EF9F27' },
  { id: 'epistemic',     label: 'Epistemic tool',    color: '#7F77DD' },
  { id: 'declined',      label: 'Declined',          color: '#E24B4A' },
];

export const LAYERS = {
  J: { id: 'J', group: 'full', symbol: 'J', name: 'Flux field',
    definition: 'Continuous ℝ³ vector field — the one fundamental substrate.',
    math: '∂ₜ²J = c²∇²J', tag: '[AXIOM · P3] ontic-real', doc: 'SPEC_FTD §3',
    flowsTo: ['divJ', 'psi', 'curlForces'] },
  qpClock: { id: 'qpClock', group: 'full', symbol: '(q,p)', name: 'Native clock θ(k)',
    definition: 'Symplectic quadratures; the substrate’s only native winding angle.',
    math: 'ω(k)=2·C_WAVE·|sin(k/2)|', tag: '[MEASURED] FTD-0251', doc: 'EXPLR_SUBSTRATE_NATIVE_ANGLE',
    flowsTo: ['s'] },
  s: { id: 's', group: 'manifestation', symbol: 's', name: 'State field',
    definition: 'Ternary {−1, 0, +1} — what actually manifests (the actual).',
    math: 's = sign(∇·J) on threshold', tag: '[AXIOM · P3] manifestation', doc: 'SPEC_FTD §1.1',
    flowsTo: ['J', 'curlForces'] },
  filter: { id: 'filter', group: 'manifestation', symbol: 'E', name: 'Existence Filter',
    definition: 'The gate E(x)=Re(x): flux is projected onto the real axis and snaps to ternary.',
    math: 'E(x) = Re(x)', tag: '[SELECTION]', doc: 'FOUND_THE_EXISTENCE_FILTER',
    flowsTo: ['s'] },
  divJ: { id: 'divJ', group: 'derived', symbol: '∇·J', name: 'Gauss source',
    definition: 'Divergence of the flux — sets manifestation polarity.',
    math: 'ρ = ∇·J', tag: '[DERIVED]', doc: 'SPEC_FTD §4.1',
    flowsTo: ['filter'] },
  psi: { id: 'psi', group: 'derived', symbol: 'ψ⊥', name: 'Transverse plane',
    definition: 'ψ = J_x + i·J_y left by the Gauss constraint — the wave-function "arena".',
    math: 'ψ = J_x + i·J_y', tag: '[SELECTION]', doc: 'DERIV_QM_FROM_LATTICE',
    flowsTo: ['readoff'] },
  latency: { id: 'latency', group: 'derived', symbol: 'L', name: 'Latency / gravity',
    definition: 'Poisson well sourced by mass; lapse f=1−L², clock rate √f.',
    math: '∇²L = 4πGρ ; dτ/dt = √(1−L²)', tag: '[DERIVED · imposed]', doc: 'SPEC_FTD_LAGRANGIAN §4',
    flowsTo: [] },
  split: { id: 'split', group: 'derived', symbol: '∥⊥', name: 'Gauss decomposition',
    definition: 'Longitudinal (constrained) vs transverse (free) parts of J.',
    math: 'J = J∥ + J⊥', tag: '[THEOREM]', doc: 'Gauss projection',
    flowsTo: ['psi'] },
  curlForces: { id: 'curlForces', group: 'derived', symbol: '∇×J', name: 'Forces',
    definition: 'Curl + Coulomb give Lorentz-like forces on charges.',
    math: 'F ∝ ∇(|J|²), ∇×J', tag: '[DERIVED]', doc: 'SPEC_FTD §6.3',
    flowsTo: ['latency'] },
  lr: { id: 'lr', group: 'imposed', symbol: 'L/R', name: 'Dual substrate',
    definition: 'Hand-set parity split into mirror copies (not emergent).',
    math: 'f_L ≈ 0.978', tag: '[IMPOSED] FTD-0248', doc: 'AUDIT_DUAL_SUBSTRATE_PROVENANCE',
    flowsTo: [] },
  observer: { id: 'observer', group: 'partial', symbol: 'obs', name: 'Observer’s view',
    definition: 'A frame-relative slice of the substrate; carries a structural self blind-spot.',
    math: 'restriction of {s, J, …}', tag: '[SYNTHESIS / OPEN]', doc: 'REF_REFERENCE_FRAME_VOCABULARY',
    flowsTo: [] },
  readoff: { id: 'readoff', group: 'epistemic', symbol: '→', name: 'Statistical read-off',
    definition: 'A partial observer reads the substrate statistically (Born-style). The Born rule itself is unresolved.',
    math: 'P ?= |ψ|²', tag: '[OPEN] (Born)', doc: 'FTD-0187',
    flowsTo: ['psiWave'] },
  psiWave: { id: 'psiWave', group: 'epistemic', symbol: 'Ψ', name: 'Wavefunction (statistical)',
    definition: 'A partial observer’s bookkeeping. Accurate, but not a thing in the substrate.',
    math: 'Ψ = epistemic state', tag: '[SELECTION]', doc: 'DERIV_QM_FROM_LATTICE',
    flowsTo: [] },
  M: { id: 'M', group: 'declined', symbol: 'M', name: 'Non-commutativity (declined)',
    definition: 'QM’s operator / Hilbert-space import. FTD declines it (FC-1) — not in the model.',
    math: '[A,B] ≠ 0  ✗', tag: '[CLOSED-NEG ×4 · FC-1]', doc: 'THEOREM_COMMUTATIVITY_INDEPENDENCE',
    flowsTo: [] },
};
