/**
 * Scale 2/3 diagnostics table descriptor (Atom / Molecule Engine).
 * Rows summarize the current AE scenario via the same descriptor-driven
 * diagnostics surface as Scales 0/1. One descriptor serves both AE scales
 * ('2' atoms, '3' molecules) — the panel root is `.scale-ae`-classed.
 *
 * Sources:
 *   s2.diag    — aeGetDiagnostics() snapshot: tick, atomCount, bondCount,
 *                totalKE, totalPEIonic, totalPEVdw, totalPEBond, totalPEAngle,
 *                totalEnergy, momentumX/Y/Z, temperature,
 *                energyComplete, energyConservative, energyStatus
 *   s2.runtime — aeGetRuntimeState() snapshot + scenario label:
 *                scenario, dt, softening, thermostatTemp, toggles.*
 *
 * Units: AE energies/temperature/momentum are SIM UNITS (implicit k_B = 1,
 * audit P0-10) — the unit column says "(sim)", never MeV / Kelvin.
 */

export const sections = [
    {
        id: 'ae-runtime',
        title: 'Scenario Dynamics',
        rows: [
            { id: 'scenario', label: 'Scenario', unit: '', format: 'text',
              source: 's2.runtime.scenario' },
            { id: 'dt', label: 'Time Step', unit: 'tick', source: 's2.runtime.dt' },
            { id: 'softening', label: 'Softening', unit: 'a₀', source: 's2.runtime.softening' },
            { id: 'ionic-on', label: 'Ionic (Coulomb)', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.ionic' },
            { id: 'vdw-on', label: 'Van der Waals', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.vdw' },
            { id: 'bonds-force-on', label: 'Bond Springs', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.bonds_force' },
            { id: 'bonding-on', label: 'Auto-Bonding', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.bonding' },
            { id: 'damping-on', label: 'Damping', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.damping' },
            { id: 'speed-limit-on', label: 'Speed Limit', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.speed_limit' },
        ],
    },
    {
        id: 'ae-phase3',
        title: 'Phase 3 Forces',
        rows: [
            { id: 'hbonds-on', label: 'H-Bonds', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.h_bonds' },
            { id: 'angle-on', label: 'VSEPR Angle Strain', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.angle_strain' },
            { id: 'dipole-on', label: 'Dipole-Dipole', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.dipole_dipole' },
            { id: 'thermostat-on', label: 'Thermostat', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.thermostat' },
            { id: 'electronegativity-on', label: 'Electronegativity', unit: '', format: 'boolean',
              source: 's2.runtime.toggles.electronegativity' },
            { id: 'thermostat-temp', label: 'Thermostat Target', unit: '(sim)',
              source: 's2.runtime.thermostatTemp' },
        ],
    },
    {
        id: 'ae-nuclear-reaction',
        title: 'Nuclear Reaction Ledger',
        rows: [
            { id: 'nuclear-channel', label: 'Channel', unit: '', format: 'text', source: 's2.diag.nuclear.label' },
            { id: 'nuclear-phase', label: 'Phase', unit: '', format: 'text', source: 's2.diag.nuclear.phase' },
            { id: 'nuclear-mode', label: 'Population Mode', unit: '', format: 'text', source: 's2.diag.nuclear.mode' },
            { id: 'nuclear-events', label: 'Events', unit: 'ct', source: 's2.diag.nuclear.eventCount', trend: 'aeReactionEvents' },
            { id: 'nuclear-event-rate', label: 'Events / 100 Ticks', unit: 'ct', source: 's2.diag.nuclear.eventRatePer100Ticks',
              tooltip: 'Accepted live nuclear collisions during the trailing 100 simulation ticks.' },
            { id: 'nuclear-represented-events', label: 'Represented Events', unit: 'ct', source: 's2.diag.nuclear.representedEventCount' },
            { id: 'nuclear-generation', label: 'Chain Generation', unit: 'ct', source: 's2.diag.nuclear.generation', trend: 'aeNuclearGeneration' },
            { id: 'nuclear-fuel', label: 'Fuel Remaining', unit: 'ct', source: 's2.diag.nuclear.fuelRemaining', trend: 'aeNuclearFuel' },
            { id: 'nuclear-live-neutrons', label: 'Live Neutrons', unit: 'ct', source: 's2.diag.nuclear.liveNeutrons',
              tooltip: 'Free neutron particle records currently inside the finite computed state.' },
            { id: 'nuclear-source-saturated', label: 'Source Saturated', unit: '', format: 'boolean', source: 's2.diag.nuclear.sourceSaturated',
              tooltip: 'True when automatic or manual injection reached the finite nuclear particle safety ceiling.' },
            { id: 'nuclear-k-effective', label: 'Observed Neutron Reproduction', unit: '', source: 's2.diag.nuclear.kEffective',
              tooltip: 'Prompt fission-neutron births divided by resolved neutron losses (fission, capture, and leakage) so far. This is measured from the run; it is not an imposed reactor k-effective.' },
            { id: 'nuclear-fission-births', label: 'Fission Neutron Births', unit: 'ct', source: 's2.diag.nuclear.fissionNeutronBirths' },
            { id: 'nuclear-fission-losses', label: 'Neutrons Causing Fission', unit: 'ct', source: 's2.diag.nuclear.neutronFissionLosses' },
            { id: 'nuclear-leaks', label: 'Neutron Leakage', unit: 'ct', source: 's2.diag.nuclear.leakedNeutrons' },
            { id: 'nuclear-absorbed', label: 'Neutron Captures', unit: 'ct', source: 's2.diag.nuclear.absorbedNeutrons' },
            { id: 'nuclear-scattered', label: 'Moderator Scatters', unit: 'ct', source: 's2.diag.nuclear.scatteredNeutrons' },
            { id: 'nuclear-neutron-containment', label: 'Neutron Containment [IMPOSED]', unit: 'frac', source: 's2.diag.nuclear.neutronContainment' },
            { id: 'nuclear-gamma-containment', label: 'Gamma Containment [IMPOSED]', unit: 'frac', source: 's2.diag.nuclear.gammaContainment' },
            { id: 'nuclear-incident', label: 'Incident Energy', unit: 'MeV', source: 's2.diag.nuclear.incidentEnergyMeV' },
            { id: 'nuclear-collision-energy', label: 'Last Collision Energy', unit: 'MeV', source: 's2.diag.nuclear.collisionEnergyMeV',
              tooltip: 'Relative center-of-mass kinetic energy of the last accepted live isotope collision.' },
            { id: 'nuclear-collision-probability', label: 'Last Reaction Probability', unit: 'frac', source: 's2.diag.nuclear.reactionProbability',
              tooltip: '[PARAMETRIC] Seeded acceptance probability of the last event from energy response, overlap exposure, and the explicit reactivity coefficient.' },
            { id: 'nuclear-q', label: 'Selected-Channel Mass Q', unit: 'MeV', source: 's2.diag.nuclear.qMeV' },
            { id: 'nuclear-release-per-event', label: 'Recoverable / Event', unit: 'MeV', source: 's2.diag.nuclear.recoverablePerEventMeV' },
            { id: 'nuclear-released', label: 'Ensemble Released', unit: 'MeV', source: 's2.diag.nuclear.releasedMeV', trend: 'aeNuclearReleased' },
            { id: 'nuclear-joule', label: 'Ensemble Released', unit: 'J', source: 's2.diag.nuclear.releasedJoule', trend: 'aeNuclearJoule' },
            { id: 'nuclear-charged', label: 'Charged-Particle Kinetic', unit: 'MeV', source: 's2.diag.nuclear.chargedMeV' },
            { id: 'nuclear-neutron-energy', label: 'Prompt-Neutron Kinetic', unit: 'MeV', source: 's2.diag.nuclear.neutronMeV' },
            { id: 'nuclear-gamma-energy', label: 'Prompt / Capture Gamma', unit: 'MeV', source: 's2.diag.nuclear.promptGammaMeV' },
            { id: 'nuclear-delayed-heat', label: 'Delayed Recoverable Heat', unit: 'MeV', source: 's2.diag.nuclear.delayedHeatMeV' },
            { id: 'nuclear-deposited', label: 'Deposited', unit: 'MeV', source: 's2.diag.nuclear.depositedMeV', trend: 'aeNuclearDeposited' },
            { id: 'nuclear-transit', label: 'In Transit', unit: 'MeV', source: 's2.diag.nuclear.inTransitMeV', trend: 'aeNuclearTransit' },
            { id: 'nuclear-escaped', label: 'Escaped', unit: 'MeV', source: 's2.diag.nuclear.escapedMeV', trend: 'aeNuclearEscaped' },
            { id: 'nuclear-proton-residual', label: 'Proton Residual', unit: 'ct', source: 's2.diag.nuclear.protonResidual' },
            { id: 'nuclear-charge-residual', label: 'Charge Residual', unit: 'e', source: 's2.diag.nuclear.chargeResidual' },
            { id: 'nuclear-neutron-residual', label: 'Neutron Residual', unit: 'ct', source: 's2.diag.nuclear.neutronResidual' },
            { id: 'nuclear-momentum-residual', label: 'Momentum Residual', unit: '(sim)', source: 's2.diag.nuclear.momentumResidual' },
            { id: 'nuclear-energy-residual', label: 'Q Ledger Residual', unit: 'MeV', source: 's2.diag.nuclear.energyResidualMeV' },
            { id: 'nuclear-total-ledger-residual', label: 'Total Ledger Residual', unit: 'MeV', source: 's2.diag.nuclear.totalLedgerResidualMeV' },
            { id: 'nuclear-transport-residual', label: 'Transport Residual', unit: 'MeV', source: 's2.diag.nuclear.transportResidualMeV' },
            { id: 'nuclear-transport-residual-frac', label: 'Transport Residual / Released', unit: 'frac', source: 's2.diag.nuclear.transportResidualFraction',
              tooltip: 'Scale-independent closure residual. Use this row for ensemble ledgers large enough that one floating-point ULP spans many MeV.' },
        ],
    },
    {
        id: 'ae-hamiltonian',
        title: 'Tracked Energy',
        rows: [
            { id: 'atoms', label: 'Atoms', unit: 'ct',
              source: 's2.diag.atomCount', trend: 'aeAtomCount' },
            { id: 'bonds', label: 'Bonds', unit: 'ct',
              source: 's2.diag.bondCount', trend: 'aeBonds' },
            { id: 'ke', label: 'Kinetic Energy', unit: '(sim)',
              source: 's2.diag.totalKE', trend: 'aeKE' },
            { id: 'pe-ionic', label: 'PE Ionic', unit: '(sim)',
              source: 's2.diag.totalPEIonic', trend: 'aePEIonic' },
            { id: 'pe-vdw', label: 'PE vdW', unit: '(sim)',
              source: 's2.diag.totalPEVdw', trend: 'aePEVdw' },
            { id: 'pe-bond', label: 'PE Bond', unit: '(sim)',
              source: 's2.diag.totalPEBond', trend: 'aePEBond' },
            { id: 'pe-angle', label: 'PE Angle', unit: '(sim)',
              source: 's2.diag.totalPEAngle', trend: 'aePEAngle' },
            { id: 'accounting', label: 'Accounting', unit: '', format: 'text',
              source: 's2.diag.energyStatus' },
            { id: 'total', label: 'Tracked Energy', unit: '(sim)',
              source: 's2.diag.totalEnergy', trend: 'aeEnergy' },
            { id: 'drift', label: 'Conservative Drift', unit: '%',
              compute: (hub) => hub.aeDrift.last(), trend: 'aeDrift' },
        ],
    },
    {
        id: 'ae-conservation',
        title: 'Conservation & Thermal',
        rows: [
            { id: 'momentum', label: 'Momentum', unit: '(sim)', format: 'vector',
              source: ['s2.diag.momentumX', 's2.diag.momentumY', 's2.diag.momentumZ'] },
            { id: 'momentum-mag', label: '|p|', unit: '(sim)',
              compute: (hub) => hub.aeMomentum.last(), trend: 'aeMomentum' },
            { id: 'temperature', label: 'Temperature', unit: '(sim)',
              source: 's2.diag.temperature', trend: 'aeTemp' },
            { id: 'tick', label: 'AE Tick', unit: 'tick',
              source: 's2.diag.tick' },
            { id: 'force-clamped', label: 'Force Clamp Active', unit: '', format: 'boolean',
              source: 's2.diag.forceClamped' },
            { id: 'force-clamp-scale', label: 'Force Clamp Scale', unit: '',
              source: 's2.diag.forceClampScale' },
            { id: 'force-clamp-events', label: 'Force Clamp Events', unit: 'ct',
              source: 's2.diag.forceClampEvents', trend: 'aeForceClampEvents' },
            { id: 'last-error', label: 'Engine Status', unit: '', format: 'text',
              source: 's2.diag.lastError' },
        ],
    },
];
