/**
 * Scale 1 diagnostics table descriptor.
 * These rows summarize the current ParticleEngine scenario using the same
 * descriptor-driven diagnostics surface as Scale 0.
 */

import { G_PE, ALPHA_G_ELECTRON, GRAVITY_VIS_GAIN } from '../../../../constants.js';
import { scale1State } from '../../../../scales/scale1/state/store.js';

function scale1LastPromotionField(key) {
    const p = scale1State.lastPromotion;
    return p ? String(p[key] ?? '—') : '—';
}

export const sections = [
    {
        id: 'pe-runtime',
        title: 'Scenario Dynamics',
        rows: [
            { id: 'scenario', label: 'Scenario', unit: '', format: 'text',
              source: 's1.runtime.scenario' },
            { id: 'dt', label: 'Time Step', unit: 'tick', source: 's1.runtime.dt' },
            { id: 'softening', label: 'Softening', unit: 'lu', source: 's1.runtime.softening' },
            { id: 'coulomb-on', label: 'Coulomb', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.coulomb' },
            { id: 'gravity-on', label: 'Gravity', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.gravity' },
            { id: 'damping-on', label: 'Damping', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.damping' },
            { id: 'exchange-on', label: 'Exchange', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.exchange' },
            { id: 'strong-on', label: 'Strong', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.strong' },
            { id: 'lorentz-on', label: 'Lorentz', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.lorentz' },
            { id: 'magdip-on', label: 'Mag. Dipole', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.magnetic_dipole' },
            { id: 'spinorbit-on', label: 'Spin-Orbit', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.spin_orbit' },
            { id: 'radiation-on', label: 'Radiation', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.radiation' },
            { id: 'relativistic-on', label: 'Relativistic', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.relativistic' },
            { id: 'rel-verlet-on', label: 'Rel. Verlet', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.relativistic_verlet' },
            { id: 'g-pe', label: 'G_PE (derived)', unit: 'MeV⁻²',
              compute: () => G_PE },
            { id: 'alpha-g-ee', label: 'α_G(e,e)', unit: '',
              compute: () => ALPHA_G_ELECTRON },
        ],
    },
    {
        id: 'pe-hamiltonian',
        title: 'Active Hamiltonian',
        rows: [
            { id: 'count', label: 'Particles', unit: 'ct',
              source: 's1.diag.particleCount', trend: 'peCount' },
            { id: 'locked', label: 'Locked / Mobile', unit: 'ct', format: 'pair',
              compute: (hub) => [hub.peLockedCount.last(), hub.peMobileCount.last()] },
            { id: 'charge-comp', label: 'Charge +/0/-', unit: '', format: 'triple',
              compute: (hub) => [hub.pePosCount.last(), hub.peZeroCount.last(), hub.peNegCount.last()] },
            { id: 'ke', label: 'Kinetic Energy', unit: 'MeV',
              source: 's1.diag.totalKE', trend: 'peKE' },
            { id: 'pe', label: 'Potential (active terms)', unit: 'MeV',
              source: 's1.diag.totalPE', trend: 'pePE' },
            { id: 'coulomb-pe', label: 'Coulomb PE', unit: 'MeV',
              source: 's1.diag.coulombPE', trend: 'peCoulombPE' },
            { id: 'gravity-pe', label: 'Gravity PE', unit: 'MeV',
              source: 's1.diag.gravityPE', trend: 'peGravityPE' },
            { id: 'total', label: 'Total Energy', unit: 'MeV',
              source: 's1.diag.totalEnergy', trend: 'peTotal' },
            { id: 'drift', label: 'Energy Drift', unit: '%',
              compute: (hub) => hub.peEnergyDrift.last(), trend: 'peEnergyDrift' },
        ],
    },
    {
        id: 'pe-conservation',
        title: 'Conservation',
        rows: [
            { id: 'momentum', label: 'Momentum', unit: 'sim', format: 'vector',
              source: ['s1.diag.momentumX', 's1.diag.momentumY', 's1.diag.momentumZ'] },
            { id: 'momentum-mag', label: '|p|', unit: 'sim',
              compute: (hub) => hub.peMomentum.last(), trend: 'peMomentum' },
            { id: 'angmom', label: 'Angular Mom (origin)', unit: 'sim', format: 'vector',
              source: ['s1.diag.angMomX', 's1.diag.angMomY', 's1.diag.angMomZ'] },
            { id: 'angmom-mag', label: '|L| (origin)', unit: 'sim',
              compute: (hub) => hub.peAngMom.last(), trend: 'peAngMom' },
            { id: 'virial', label: 'Virial 2K/|U|', unit: '',
              compute: (hub) => hub.peVirial.last(), trend: 'peVirial' },
            { id: 'net-charge', label: 'Net Charge Q', unit: 'e',
              compute: (hub) => hub.peNetCharge.last(), trend: 'peNetCharge' },
        ],
    },
    {
        id: 'pe-field-forces',
        title: 'Forces & Geometry',
        rows: [
            { id: 'max-beta', label: 'Max |v|/c', unit: 'c',
              compute: (hub) => hub.peMaxBeta.last(), trend: 'peMaxBeta' },
            { id: 'cap-count', label: 'At Causal Cap', unit: 'ct',
              compute: (hub) => hub.peCapCount.last(), trend: 'peCapCount' },
            { id: 'max-force', label: 'Max Net Force', unit: 'sim',
              compute: (hub) => hub.peMaxForce.last(), trend: 'peMaxForce' },
            { id: 'mean-force', label: 'Mean Net Force', unit: 'sim',
              compute: (hub) => hub.peMeanForce.last(), trend: 'peMeanForce' },
            { id: 'vrms', label: 'RMS Velocity', unit: 'c',
              compute: (hub) => hub.peRmsVelocity.last(), trend: 'peRmsVelocity' },
            { id: 'temperature', label: 'Temperature', unit: 'MeV',
              compute: (hub) => hub.peTemperature.last(), trend: 'peTemperature' },
            { id: 'radius', label: 'System Radius', unit: 'lu',
              compute: (hub) => hub.peSystemRadius.last(), trend: 'peSystemRadius' },
            { id: 'separation', label: '2-Body Separation', unit: 'lu',
              compute: (hub) => hub.peSeparation.last(), trend: 'peSeparation' },
            { id: 'radial-velocity', label: 'Radial Velocity', unit: 'c',
              compute: (hub) => hub.peRadialVelocity.last(), trend: 'peRadialVelocity' },
        ],
    },
    {
        id: 'pe-velocities',
        title: 'Velocities Overlay',
        visibleWhen: (hub) => !!hub.s1?._overlayVelocitiesOn,
        rows: [
            { id: 'vrms2', label: 'RMS Velocity', unit: 'c',
              compute: (hub) => hub.peRmsVelocity.last() },
            { id: 'max-beta2', label: 'Max |v|/c', unit: 'c',
              compute: (hub) => hub.peMaxBeta.last() },
            { id: 'cap-count2', label: 'At Causal Cap', unit: 'ct',
              compute: (hub) => hub.peCapCount.last() },
            { id: 'legend', label: 'Color legend', unit: '', format: 'text',
              compute: () => 'green→yellow <0.5c · yellow→orange 0.5-0.85c · orange→red 0.85-0.985c · red→white >0.985c (cap)' },
        ],
    },
    {
        id: 'pe-trails',
        title: 'Trails Overlay',
        visibleWhen: (hub) => !!hub.s1?._overlayTrailsOn,
        rows: [
            { id: 'orbit-period', label: 'Orbit period (2-body proxy)', unit: 'tick',
              format: 'text',
              compute: (hub) => hub.s1._orbitPeriod === null ? '—' : String(hub.s1._orbitPeriod) },
        ],
    },
    {
        id: 'pe-efield',
        title: 'E-Field Streamlines Overlay',
        visibleWhen: (hub) => !!hub.s1?._overlayEfieldOn,
        rows: [
            { id: 'coulomb-pe2', label: 'Coulomb PE', unit: 'MeV',
              compute: (hub) => hub.s1.diag?.coulombPE ?? 0 },
            { id: 'grid-res', label: 'Sample grid', unit: '', format: 'text',
              compute: () => '25×20 (XZ plane, fixed)' },
        ],
    },
    {
        id: 'pe-potential',
        title: 'Potential Heatmap Overlay',
        visibleWhen: (hub) => !!hub.s1?._overlayPotentialOn,
        rows: [
            { id: 'coulomb-pe3', label: 'Coulomb PE', unit: 'MeV',
              compute: (hub) => hub.s1.diag?.coulombPE ?? 0 },
            { id: 'potential-min', label: 'Min potential (this frame)', unit: '',
              compute: (hub) => hub.s1._potentialMin ?? 0 },
            { id: 'potential-max', label: 'Max potential (this frame)', unit: '',
              compute: (hub) => hub.s1._potentialMax ?? 0 },
        ],
    },
    {
        id: 'pe-gravity-field',
        title: 'Gravity Vectors Overlay',
        visibleWhen: (hub) => !!hub.s1?._overlayGravityFieldOn,
        rows: [
            { id: 'gravity-pe2', label: 'Gravity PE', unit: 'MeV',
              compute: (hub) => hub.s1.diag?.gravityPE ?? 0 },
            { id: 'g-pe2', label: 'G_PE constant', unit: 'MeV⁻²', compute: () => G_PE },
            { id: 'vis-gain', label: 'Visual gain applied', unit: '×',
              compute: () => GRAVITY_VIS_GAIN,
              format: 'text' },
        ],
    },
    {
        id: 'pe-force-decomp',
        title: 'Force Decomposition Overlay',
        visibleWhen: (hub) => !!hub.s1?._overlayForceOn,
        rows: [
            { id: 'max-force2', label: 'Max Net Force', unit: 'sim',
              compute: (hub) => hub.peMaxForce.last() },
            { id: 'mean-force2', label: 'Mean Net Force', unit: 'sim',
              compute: (hub) => hub.peMeanForce.last() },
        ],
    },
    {
        id: 'pe-system',
        title: 'System Overlay (CoM / p / L)',
        visibleWhen: (hub) => !!hub.s1?._overlaySystemOn,
        rows: [
            { id: 'l-com-note', label: 'L (about CoM, this overlay)', unit: 'sim',
              compute: (hub) => hub.s1._overlaySystemL ?? 0 },
            { id: 'l-origin-xref', label: 'cf. L (about origin, Conservation table)', unit: 'sim',
              compute: (hub) => hub.peAngMom.last() },
        ],
    },
    {
        id: 'pe-provenance',
        title: 'Provenance Overlay',
        visibleWhen: (hub) => !!hub.s1?._overlayProvenanceOn,
        rows: [
            { id: 'source-scenario', label: 'Source scenario', unit: '', format: 'text',
              compute: () => scale1LastPromotionField('sourceScenario') },
            { id: 'source-tick', label: 'Source tick', unit: '', format: 'text',
              compute: () => scale1LastPromotionField('sourceTick') },
            { id: 'cluster-source', label: 'Cluster source', unit: '', format: 'text',
              compute: () => scale1LastPromotionField('clusterSource') },
        ],
    },
];
