/**
 * Scale 1 diagnostics table descriptor.
 * These rows summarize the current ParticleEngine scenario using the same
 * descriptor-driven diagnostics surface as Scale 0.
 */

import { G_PE, ALPHA_G_ELECTRON } from '../../../../constants.js';

export const sections = [
    {
        id: 'pe-runtime',
        title: 'Scenario Dynamics',
        rows: [
            { id: 'scenario', label: 'Scenario', unit: '', format: 'text',
              source: 's1.runtime.scenario' },
            { id: 'dt', label: 'Time Step', unit: 'tick', source: 's1.runtime.dt' },
            { id: 'softening', label: 'Softening', unit: 'lu', source: 's1.runtime.softening' },
            { id: 'coulomb-on', label: 'Coulomb', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.coulomb' },
            { id: 'gravity-on', label: 'Gravity', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.gravity' },
            { id: 'damping-on', label: 'Damping', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.damping' },
            { id: 'exchange-on', label: 'Exchange', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.exchange' },
            { id: 'strong-on', label: 'Strong', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.strong' },
            { id: 'lorentz-on', label: 'Lorentz', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.lorentz' },
            { id: 'magdip-on', label: 'Mag. Dipole', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.magnetic_dipole' },
            { id: 'spinorbit-on', label: 'Spin-Orbit', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.spin_orbit' },
            { id: 'radiation-on', label: 'Radiation', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.radiation' },
            { id: 'relativistic-on', label: 'Relativistic', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.relativistic' },
            { id: 'rel-verlet-on', label: 'Rel. Verlet', unit: '', format: 'boolean',
              source: 's1.runtime.toggles.relativistic_verlet' },
            { id: 'g-pe', label: 'G_PE (derived)', unit: 'MeV⁻²',
              compute: () => G_PE },
            { id: 'alpha-g-ee', label: 'α_G(e,e)', unit: '',
              compute: () => ALPHA_G_ELECTRON },
        ],
    },
    {
        id: 'pe-hamiltonian',
        title: 'Active Hamiltonian',
        rows: [
            { id: 'count', label: 'Particles', unit: 'ct',
              source: 's1.diag.particleCount', trend: 'peCount' },
            { id: 'locked', label: 'Locked / Mobile', unit: 'ct', format: 'pair',
              compute: (hub) => [hub.peLockedCount.last(), hub.peMobileCount.last()] },
            { id: 'charge-comp', label: 'Charge +/0/-', unit: '', format: 'triple',
              compute: (hub) => [hub.pePosCount.last(), hub.peZeroCount.last(), hub.peNegCount.last()] },
            { id: 'ke', label: 'Kinetic Energy', unit: 'MeV',
              source: 's1.diag.totalKE', trend: 'peKE' },
            { id: 'pe', label: 'Potential (active terms)', unit: 'MeV',
              source: 's1.diag.totalPE', trend: 'pePE' },
            { id: 'coulomb-pe', label: 'Coulomb PE', unit: 'MeV',
              source: 's1.diag.coulombPE', trend: 'peCoulombPE' },
            { id: 'gravity-pe', label: 'Gravity PE', unit: 'MeV',
              source: 's1.diag.gravityPE', trend: 'peGravityPE' },
            { id: 'total', label: 'Total Energy', unit: 'MeV',
              source: 's1.diag.totalEnergy', trend: 'peTotal' },
            { id: 'drift', label: 'Energy Drift', unit: '%',
              compute: (hub) => hub.peEnergyDrift.last(), trend: 'peEnergyDrift' },
        ],
    },
    {
        id: 'pe-conservation',
        title: 'Conservation',
        rows: [
            { id: 'momentum', label: 'Momentum', unit: 'sim', format: 'vector',
              source: ['s1.diag.momentumX', 's1.diag.momentumY', 's1.diag.momentumZ'] },
            { id: 'momentum-mag', label: '|p|', unit: 'sim',
              compute: (hub) => hub.peMomentum.last(), trend: 'peMomentum' },
            { id: 'angmom', label: 'Angular Mom (origin)', unit: 'sim', format: 'vector',
              source: ['s1.diag.angMomX', 's1.diag.angMomY', 's1.diag.angMomZ'] },
            { id: 'angmom-mag', label: '|L| (origin)', unit: 'sim',
              compute: (hub) => hub.peAngMom.last(), trend: 'peAngMom' },
            { id: 'virial', label: 'Virial 2K/|U|', unit: '',
              compute: (hub) => hub.peVirial.last(), trend: 'peVirial' },
            { id: 'net-charge', label: 'Net Charge Q', unit: 'e',
              compute: (hub) => hub.peNetCharge.last(), trend: 'peNetCharge' },
        ],
    },
    {
        id: 'pe-field-forces',
        title: 'Forces & Geometry',
        rows: [
            { id: 'max-beta', label: 'Max |v|/c', unit: 'c',
              compute: (hub) => hub.peMaxBeta.last(), trend: 'peMaxBeta' },
            { id: 'cap-count', label: 'At Causal Cap', unit: 'ct',
              compute: (hub) => hub.peCapCount.last(), trend: 'peCapCount' },
            { id: 'max-force', label: 'Max Net Force', unit: 'sim',
              compute: (hub) => hub.peMaxForce.last(), trend: 'peMaxForce' },
            { id: 'mean-force', label: 'Mean Net Force', unit: 'sim',
              compute: (hub) => hub.peMeanForce.last(), trend: 'peMeanForce' },
            { id: 'vrms', label: 'RMS Velocity', unit: 'c',
              compute: (hub) => hub.peRmsVelocity.last(), trend: 'peRmsVelocity' },
            { id: 'temperature', label: 'Temperature', unit: 'MeV',
              compute: (hub) => hub.peTemperature.last(), trend: 'peTemperature' },
            { id: 'radius', label: 'System Radius', unit: 'lu',
              compute: (hub) => hub.peSystemRadius.last(), trend: 'peSystemRadius' },
            { id: 'separation', label: '2-Body Separation', unit: 'lu',
              compute: (hub) => hub.peSeparation.last(), trend: 'peSeparation' },
            { id: 'radial-velocity', label: 'Radial Velocity', unit: 'c',
              compute: (hub) => hub.peRadialVelocity.last(), trend: 'peRadialVelocity' },
        ],
    },
];
