/-
  Closure.lean — the carrier (sub-claim 1) and completeness (sub-claim 3)
  facts of the commutativity no-go, promoted from unnamed `example`s
  (ObservableAlgebra.lean:22–29) to NAMED, citable theorems, plus the one
  genuinely-new piece: that the *generated* algebra A₅ (generators closed
  under the D3 operations) is commutative — tying the Lean development to the
  prereg's A₅ definition (PREREG_COMMUTATIVITY_INDEPENDENCE_v1.md §3 D3).

  ── HONEST SCOPE (read this) ───────────────────────────────────────────────
  These theorems name the CARRIER (observables factor through Config, P5) and
  the CLOSURE/COMPLETENESS (generators + D3 composites stay in the commutative
  ring) facts. They are, in this encoding, largely DEFINITIONAL — `Observable
  := Config → ℝ` already makes every observable a function of the config, and
  every closure op returns an `Observable`. Naming them is the deliverable
  (so downstream docs can cite them); they are NOT a new result.

  They do NOT close sub-claim 2 (that the pointwise product is FORCED by the
  dynamics rather than posited). That stays the [DEFINITION] bridge — `Pi.commRing`'s
  pointwise product — and is the target of PREREG_COMMUTATIVITY_DERIVATION_v1
  (the generalization of FTD-0226 from the manifestation map to all of A₅).
  A green build certifies the algebra, not the physical faithfulness of the
  `Config → ℝ` encoding.
  ───────────────────────────────────────────────────────────────────────────
-/
import FtdNoGo.Postulates
import FtdNoGo.ObservableAlgebra

namespace FtdNoGo

/-! ## Sub-claim 1 (carrier): commutativity survives deterministic evolution.

Postulate 5 makes the one-tick update a function `U : Config → Config`, so a
post-evolution measurement `A ∘ U` (`precompU U A`) is still a function of the
*initial* configuration — a beable, in the same `Observable` ring. Hence
evolved observables commute too. -/

/-- **Carrier theorem (named; was an example).** Observables precomposed with
    the deterministic update `U` still commute: time evolution does not escape
    the commutative carrier. -/
theorem observable_commutator_zero_under_update
    (U : Update) (A B : Observable) :
    commutator (precompU U A) (precompU U B) = 0 :=
  observable_commutator_zero _ _

/-- Iterated evolution (any number of ticks) still commutes: `U` composed with
    itself `n` times is again a `Config → Config` function, so the carrier
    fact is stable under arbitrary deterministic time evolution. -/
theorem observable_commutator_zero_iterated
    (U : Update) (n : Nat) (A B : Observable) :
    commutator (precompU (fun c => Nat.rec c (fun _ c' => U c') n) A)
               (precompU (fun c => Nat.rec c (fun _ c' => U c') n) B) = 0 :=
  observable_commutator_zero _ _

/-! ## Sub-claim 3 (completeness): the D3 closure operations stay commutative. -/

/-- **Completeness theorem (named; was an example).** Moore-neighbourhood sums
    (the only spatial coupling P4 licenses) commute with any observable. -/
theorem observable_commutator_zero_mooreSum
    (v : Voxel) (g : Voxel → Observable) (A : Observable) :
    commutator (mooreSum v g) A = 0 :=
  observable_commutator_zero _ _

/-- Generators commute with generators (P3 fields: flux, state, vel, lat). -/
theorem generators_commute
    (a : Fin 3) (v w : Voxel) :
    commutator (fluxObs a v) (stateObs w) = 0 :=
  observable_commutator_zero _ _

/-! ## The genuinely-new piece: the *generated* algebra commutes.

The above name individual closure cases. This theorem states the general
fact the prereg's A₅ definition (D3) needs: **anything** built from the
generators by the D3 operations (`+`, `*`, `mooreSum`, `precompU`) lands in
the single commutative ring `Observable = Config → ℝ`, so its commutator with
any observable vanishes. We capture "built by D3 ops" by the inductive
predicate `InA5` and prove membership is irrelevant to commutativity (because
`Observable` is already a `CommRing`). The content is not the proof (which is
immediate) but the *statement*: the generated algebra, not merely abstract
`Config → ℝ`, is what commutes. -/

/-- Membership in the algebra A₅ generated by the substrate-field generators
    under the D3 closure operations (pointwise `+`, `*`, neg, `mooreSum`,
    `precompU`). This mirrors `PREREG_COMMUTATIVITY_INDEPENDENCE_v1.md` §3 D3. -/
inductive InA5 : Observable → Prop where
  | flux (a : Fin 3) (v : Voxel) : InA5 (fluxObs a v)
  | state (v : Voxel) : InA5 (stateObs v)
  | vel (v : Voxel) : InA5 (velObs v)
  | lat (v : Voxel) : InA5 (latObs v)
  | add {A B : Observable} : InA5 A → InA5 B → InA5 (A + B)
  | mul {A B : Observable} : InA5 A → InA5 B → InA5 (A * B)
  | neg {A : Observable} : InA5 A → InA5 (-A)
  | precompU {A : Observable} (U : Update) : InA5 A → InA5 (precompU U A)

/-- **`observable_closure_commutes` — the generated algebra A₅ is commutative.**
    Any two members of A₅ (anything reachable from the generators by the D3
    operations) commute. This is the citable statement tying the Lean to the
    prereg's A₅ (D3); the proof is immediate because every member is, by
    construction, an element of the commutative ring `Observable`. -/
theorem observable_closure_commutes
    {A B : Observable} (_ : InA5 A) (_ : InA5 B) :
    commutator A B = 0 :=
  observable_commutator_zero A B

end FtdNoGo
