/-
  Main.lean — the bundled algebraic core of the FTD Commutativity Independence
  No-Go, assembling the three machine-checked pillars into one theorem.

  Honest scope (see README.md and Postulates.lean): this proves the ALGEBRA.
  It does not prove that the `Config → ℝ` model faithfully encodes the five
  postulates — that is the [DEFINITION] bridge, by design.
-/
import FtdNoGo.Commutator
import FtdNoGo.Postulates
import FtdNoGo.ObservableAlgebra
import FtdNoGo.Closure
import FtdNoGo.Poisson
import FtdNoGo.Independence

namespace FtdNoGo

/-- ## The Commutativity Independence No-Go — algebraic core.

Three machine-checked conjuncts, matching
`PREREG_COMMUTATIVITY_INDEPENDENCE_v1.md`:

1. **Claim A + C** — the observable algebra generated by the five postulates'
   fields is commutative, so every commutator vanishes.
2. **F-a** — a nonzero Poisson/symplectic bracket coexists with a zero
   commutator on a commutative algebra: the symplectic structure is *not*
   quantum non-commutativity.
3. **Claim B + independence** — non-commutativity is realizable, but only in a
   non-commutative ring *outside* the observable algebra; its existence shows
   the non-commutative extension (the candidate 6th postulate `M`) is
   consistent.

Together: non-commutativity is **independent** of the five postulates — not
derivable from the (commutative) observable algebra, and consistently
addable. The pre-reg's strong-forbiddance reading is deliberately *not*
asserted (conjunct 3 shows `M` is always consistently addable). -/
theorem commutativity_independence_core :
    (∀ A B : Observable, commutator A B = 0)
  ∧ (∃ (P : Type) (_ : CommRing P) (pb : P → P → P) (a b : P),
        pb a b ≠ 0 ∧ commutator a b = 0)
  ∧ (∃ (R : Type) (_ : Ring R) (a b : R), commutator a b ≠ 0) :=
  ⟨observable_commutator_zero, poisson_witness, noncommutativity_is_external⟩

/-- ## Certified carrier + completeness core (Closure.lean).

The "certify the physics" companion to `commutativity_independence_core`,
bundling the carrier (sub-claim 1) and completeness (sub-claim 3) facts as
named theorems:

1. **Carrier** — commutativity survives deterministic evolution `∘U`
   (`observable_commutator_zero_under_update`).
2. **Completeness** — Moore-sum composites commute
   (`observable_commutator_zero_mooreSum`).
3. **Generated algebra** — anything in A₅ (generators closed under the D3
   operations) commutes (`observable_closure_commutes`).

**Honest scope:** this does NOT close sub-claim 2 (that the pointwise product
is *forced* by the dynamics). That is the `[DEFINITION]` bridge (`Pi.commRing`),
targeted by `PREREG_COMMUTATIVITY_DERIVATION_v1` (the generalization of
FTD-0226 to all of A₅). These facts are largely definitional in this encoding;
naming them is the deliverable. -/
theorem commutativity_certified_core :
    (∀ (U : Update) (A B : Observable),
        commutator (precompU U A) (precompU U B) = 0)
  ∧ (∀ (v : Voxel) (g : Voxel → Observable) (A : Observable),
        commutator (mooreSum v g) A = 0)
  ∧ (∀ {A B : Observable}, InA5 A → InA5 B → commutator A B = 0) :=
  ⟨observable_commutator_zero_under_update,
   observable_commutator_zero_mooreSum,
   observable_closure_commutes⟩

end FtdNoGo
