/-
  ObservableAlgebra.lean — Claim A + C, machine-checked: the observable
  algebra generated by the five postulates' fields is commutative, so every
  commutator vanishes (generators, products, Moore-sums, update-composites).
-/
import FtdNoGo.Postulates

namespace FtdNoGo

/-- **Claim A + C (the core result).** Any two observables commute. The
    observable algebra `A₅ = Config → ℝ` is commutative (`Pi.commRing`), so
    every commutator vanishes — and this covers *all* of A₅: the field
    generators, their pointwise products, Moore-neighbourhood sums, and
    update-composites are all elements of this one commutative ring. -/
theorem observable_commutator_zero (A B : Observable) :
    commutator A B = 0 :=
  commutator_eq_zero_of_comm A B

/-- Full generator coverage (pre-reg falsifier F-e): even the manifestation
    field `s` (Postulate 3, a function of `J`) commutes with the flux
    generators. -/
example (v : Voxel) (a : Fin 3) (w : Voxel) :
    commutator (stateObs v) (fluxObs a w) = 0 :=
  observable_commutator_zero _ _

/-- Closure coverage: update-composites and Moore-sums commute too. -/
example (U : Update) (A : Observable) (v : Voxel) (g : Voxel → Observable) :
    commutator (precompU U A) (mooreSum v g) = 0 :=
  observable_commutator_zero _ _

end FtdNoGo
