option(FTD_STRICT_CUDA "Build optional exact staged research CUDA kernels" OFF)
if(FTD_STRICT_CUDA)
  enable_language(CUDA)
  add_library(ftd_strict_cuda STATIC staged_cuda.cu)
  target_link_libraries(ftd_strict_cuda PUBLIC ftd_strict_candidate)
  target_include_directories(ftd_strict_cuda PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
  set_target_properties(ftd_strict_cuda PROPERTIES CUDA_STANDARD 17 CUDA_STANDARD_REQUIRED ON)
  add_executable(ftd_strict_cuda_cli cuda_main.cpp)
  target_link_libraries(ftd_strict_cuda_cli PRIVATE ftd_strict_cuda)
endif()
