"""Deterministically export the hash-validated finite Python law to C++17.

Run from any directory; --check verifies the checked-in header without writing.
No coefficient search or physical target enters this table transcription.
"""
from pathlib import Path
import argparse
import hashlib
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))
from phi_v2_lattice import channels as C, state as S
from phi_v2_lattice.checkpoint import ENCODING_HASH
from phi_v2_lattice.staged import LAW_ID
from phi_v2_lattice._proofs import readout, rotate, phase_index, encode


def render():
    tables = C.load_collision_tables()
    lines = ["// Generated by generate_tables.py; do not edit by hand.",
             "#pragma once", "#include <cstdint>", "namespace ftd::strict::frozen {"]

    def array(ctype, name, values):
        values = list(values)
        lines.append(f"inline constexpr {ctype} {name}[{len(values)}] = {{")
        lines.extend("    " + ",".join(map(str, values[i:i+24])) + "," for i in range(0, len(values), 24))
        lines.append("};")

    for name, hexdigest in (("COLLISION_HASH", C.COLLISION_HASH), ("ENCODING_HASH", ENCODING_HASH),
                            ("LAW_HASH", hashlib.sha256(LAW_ID.encode()).hexdigest())):
        array("std::uint8_t", name, bytes.fromhex(hexdigest))
    for layer, table in enumerate(tables):
        array("std::uint16_t", f"COLLISION_{layer}",
              (table[a, b][0] * 192 + table[a, b][1] for a in range(192) for b in range(a+1, 192)))
    lines.append("inline constexpr const std::uint16_t* COLLISION[3] = {COLLISION_0,COLLISION_1,COLLISION_2};")
    array("std::uint16_t", "U", (C.U(c) for c in range(C.N_CHANNELS)))
    array("std::uint16_t", "HALF_TURN", (C.half_turn(c) for c in range(C.N_CHANNELS)))
    array("std::uint8_t", "CHANNEL_PHASE", (C.phase(c) for c in range(C.N_CHANNELS)))
    array("std::int8_t", "TANGENT", (d for c in range(C.N_CHANNELS) for d in C.tangent(c)))
    array("std::uint8_t", "ROTATE", (S.idx_of(rotate(z)) for z in S.A9_LIST))
    array("std::int8_t", "PHASE", (-1 if phase_index(z) is None else phase_index(z) for z in S.A9_LIST))
    array("std::int8_t", "EPS", (readout(z)[1] if readout(z)[0] else 0 for z in S.A9_LIST))
    lines.append(f"inline constexpr std::uint8_t BLANK = {S.BLANK_IDX};")
    array("std::uint8_t", "ABSORBED_RESERVE", (S.idx_of(rotate(encode(2, eps))) for eps in (1, -1)))
    lines.append("}  // namespace ftd::strict::frozen")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = Path(__file__).with_name("frozen_tables.h")
    expected = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            raise SystemExit("frozen table header is absent or stale")
        print("Frozen C++ table transcription matches validated Python law.")
    else:
        path.write_text(expected, encoding="utf-8", newline="\n")
        print(path)
