// Auto-generated by scripts/proofs/generate_phase_i_lattice_green_fixtures.py
// SC7 Poisson Green's function values at selected (L, r) pairs along x-axis.
// Ground truth for Phase I cross-check (FTD-0125).

namespace phase_i {

struct GreenFixture { int L; int r; double G_L_r; double two_r_G; };

// L, r, G_L(r), 2*r*G_L(r)
inline constexpr GreenFixture kFixtures[] = {
    { 32, 4, 1.331758081340302e-02, 1.065406465072242e-01 },
    { 32, 8, 3.289580185062063e-03, 5.263328296099301e-02 },
    { 32, 8, 3.289580185062063e-03, 5.263328296099301e-02 },
    { 32, 10, 1.508160968993006e-03, 3.016321937986012e-02 },
    { 64, 4, 1.677136929818906e-02, 1.341709543855125e-01 },
    { 64, 8, 6.501945489828894e-03, 1.040311278372623e-01 },
    { 64, 16, 1.628849023368240e-03, 5.212316874778367e-02 },
    { 64, 21, 5.904768912808639e-04, 2.480002943379628e-02 },
};

inline constexpr int kNumFixtures = 8;

}  // namespace phase_i
