// Auto-generated by scripts/proofs/generate_phase_i_lattice_green_fixtures.py
// G18 Poisson Green's function values at selected (L, r) pairs along x-axis.
// Matches engine's sor_sweep_18pt stencil per engine/src/poisson_solvers.cpp.
// Ground truth for Phase I cross-check (FTD-0125).

namespace phase_i {

struct GreenFixture { int L; int r; double G_L_r; double two_r_G; };

// L, r, G_L(r), 2*r*G_L(r)
inline constexpr GreenFixture kFixtures[] = {
    { 32, 4, 4.359781149997190e-02, 3.487824919997752e-01 },
    { 32, 8, 1.030714080870934e-02, 1.649142529393495e-01 },
    { 32, 8, 1.030714080870934e-02, 1.649142529393495e-01 },
    { 32, 10, 4.754373119918250e-03, 9.508746239836499e-02 },
    { 64, 4, 5.392941776711373e-02, 4.314353421369098e-01 },
    { 64, 8, 1.991530269622128e-02, 3.186448431395404e-01 },
    { 64, 16, 4.935736381903200e-03, 1.579435642209024e-01 },
    { 64, 21, 1.795428024176140e-03, 7.540797701539789e-02 },
};

inline constexpr int kNumFixtures = 8;

}  // namespace phase_i
