// FTD-0640: complete analytic matter-mode response about the FTD-0638 center.

#define FTD_0639_EMBEDDED
#include "test_connected_block_analytic_dynamical_rest.cpp"
#undef FTD_0639_EMBEDDED

#include <set>

namespace {
constexpr char mode_protocol_sha256[] =
    "203168B41C4B611695A7DF0AA9D311EF2A23AED10CA69900B46C834BA1DD7BDC";
constexpr char mode_parent_result_sha256[] =
    "DFA39E27F0317165D2A85E7778BBC7DA5691D1449DEEF20B4990C2AB9A1E7BD6";
constexpr int mode_ticks=256;
constexpr double full_target=8e-6,half_target=4e-6;
constexpr std::array<int,13> representative{{0,1,3,5,6,8,12,18,24,31,39,45,47}};

struct FullMode { double hessian_eigen=0,lambda=0,omega=0,phase=0,max_component=0;int group=0;std::vector<double> vector; };
struct FullModes { bool valid=false;double residual=INFINITY,orthogonality=INFINITY;std::vector<FullMode> modes; };
struct ModeSpec { std::string label,kind;int orientation=0,mode=0,sign=1;double target=0; };
struct ModeTick { int tick=0;double center=0,state=0,drift=0,residual=0;int multiplicity=0;double separation=INFINITY;std::vector<double> q; };
struct ModeArm {
  ModeSpec spec;bool initialization=false,forward=false,reverse=false,bounded=false,sector=false,no_hops=false;
  int max_multiplicity=0,total_hops=0,jacobian_refreshes=0,jacobian_reuses=0;double min_separation=INFINITY,initial_max_displacement=INFINITY,initial_excess=INFINITY,phase=INFINITY,phase_error=INFINITY,leakage=INFINITY,max_center=0,max_state=0,max_drift=0,max_common=0,recovery=INFINITY,modal_amplitude=0;std::vector<ModeTick> ticks;
};
struct ModeSummary {
  bool parent=false,normalization=false,eigensystem=false,coverage=false,execution=false,bounded=false,frequency=false,purity=false,amplitude=false,sign=false,covariance=false;
  double beta=0,spectrum_covariance=INFINITY,amplitude_residual=INFINITY,sign_residual=INFINITY,covariance_residual=INFINITY,worst_common=0,worst_drift=0,worst_recovery=0;
  std::string verdict="CONNECTED_BLOCK_ANALYTIC_MATTER_MODES_EXECUTION_INVALID";std::array<FullModes,2> eig;std::vector<ModeArm> arms;
};

bool mode_parent_fingerprint(){const auto path=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0639/ftd_0639_connected_block_analytic_dynamical_rest_v1.json";std::ifstream input(path,std::ios::binary);const std::string bytes((std::istreambuf_iterator<char>(input)),{});return bytes.find(rest_protocol_sha256)!=std::string::npos&&bytes.find("CONNECTED_BLOCK_ANALYTIC_DYNAMICAL_REST_CONSTRUCTIVE")!=std::string::npos;}

FullModes full_modes(const Matrix& hessian){FullModes result;Matrix a(N,std::vector<double>(N)),vectors(N,std::vector<double>(N));for(int i=0;i<N;++i){vectors[i][i]=1;for(int j=0;j<N;++j)a[i][j]=hessian[i][j]/ftd::M_INERTIAL;}
  for(int iteration=0;iteration<200000;++iteration){int p=0,q=1;double largest=std::abs(a[p][q]);for(int i=0;i<N;++i)for(int j=i+1;j<N;++j)if(std::abs(a[i][j])>largest){largest=std::abs(a[i][j]);p=i;q=j;}if(largest<1e-12)break;const double angle=.5*std::atan2(2*a[p][q],a[q][q]-a[p][p]),c=std::cos(angle),s=std::sin(angle);for(int k=0;k<N;++k)if(k!=p&&k!=q){const double kp=a[k][p],kq=a[k][q];a[k][p]=a[p][k]=c*kp-s*kq;a[k][q]=a[q][k]=s*kp+c*kq;}const double pp=a[p][p],qq=a[q][q],pq=a[p][q];a[p][p]=c*c*pp-2*c*s*pq+s*s*qq;a[q][q]=s*s*pp+2*c*s*pq+c*c*qq;a[p][q]=a[q][p]=0;for(int k=0;k<N;++k){const double kp=vectors[k][p],kq=vectors[k][q];vectors[k][p]=c*kp-s*kq;vectors[k][q]=s*kp+c*kq;}}
  std::vector<int> order(N);std::iota(order.begin(),order.end(),0);std::sort(order.begin(),order.end(),[&](int x,int y){return a[x][x]<a[y][y];});result.modes.resize(N);int group=-1;double prior=0;for(int m=0;m<N;++m){const int column=order[m];auto& mode=result.modes[m];mode.lambda=a[column][column];mode.hessian_eigen=mode.lambda*ftd::M_INERTIAL;mode.omega=std::sqrt(mode.lambda);mode.phase=2*std::atan(mode.omega/2);mode.vector.resize(N);for(int i=0;i<N;++i){mode.vector[i]=vectors[i][column]/std::sqrt(ftd::M_INERTIAL);mode.max_component=std::max(mode.max_component,std::abs(mode.vector[i]));}int pivot=0;for(int i=1;i<N;++i)if(std::abs(mode.vector[i])>std::abs(mode.vector[pivot]))pivot=i;if(mode.vector[pivot]<0)for(double& value:mode.vector)value=-value;if(m==0||std::abs(mode.hessian_eigen-prior)>1e-10)++group;mode.group=group;prior=mode.hessian_eigen;}
  result.residual=0;result.orthogonality=0;for(int m=0;m<N;++m){for(int i=0;i<N;++i){long double hv=0;for(int j=0;j<N;++j)hv+=static_cast<long double>(hessian[i][j])*result.modes[m].vector[j];result.residual=std::max(result.residual,std::abs(static_cast<double>(hv)-result.modes[m].lambda*ftd::M_INERTIAL*result.modes[m].vector[i]));}for(int n=0;n<N;++n){long double inner=0;for(int i=0;i<N;++i)inner+=static_cast<long double>(result.modes[m].vector[i])*ftd::M_INERTIAL*result.modes[n].vector[i];result.orthogonality=std::max(result.orthogonality,std::abs(static_cast<double>(inner)-(m==n?1.0:0.0)));}}
  result.valid=result.modes.front().hessian_eigen>1e-5&&result.residual<=1e-7&&result.orthogonality<=1e-10;return result;}

ftd::eft::ConnectedMooreBlockState displaced_mode(const ftd::eft::ConnectedMooreBlockState& reference,const FullMode& mode,double target,int sign,double& amplitude,double& maximum){auto geometry=reference;amplitude=target/mode.max_component;maximum=0;for(int p=0;p<count;++p){Vec3 x=position(reference.constituents[p]);for(int axis=0;axis<3;++axis){const double dx=sign*amplitude*mode.vector[3*p+axis];set_component(x,axis,component(x,axis)+dx);maximum=std::max(maximum,std::abs(dx));}geometry.constituents[p]=point_at(x);geometry.constituents[p].momentum={};}const auto dressed=ftd::eft::redress_connected_moore_block_with_fibre_limit(geometry,8,1e-13,4096);return dressed.valid?dressed.state:ftd::eft::ConnectedMooreBlockState{};}
std::vector<double> project_modes(const ftd::eft::ConnectedMooreBlockState& reference,const ftd::eft::ConnectedMooreBlockState& state,const FullModes& modes){std::vector<double> q(N,0);for(int m=0;m<N;++m)for(int p=0;p<count;++p){const Vec3 dx=position(state.constituents[p])-position(reference.constituents[p]);for(int axis=0;axis<3;++axis)q[m]+=modes.modes[m].vector[3*p+axis]*ftd::M_INERTIAL*component(dx,axis);}return q;}
double mode_energy(const ftd::eft::ConnectedMooreBlockState& state,double beta,const ftd::eft::ConnectedMooreBlockOptions& options){long double kinetic=0;for(const auto&p:state.constituents)kinetic+=ftd::eft::production_flat_energy_from_momentum(p.momentum);return static_cast<double>(kinetic)+ftd::eft::connected_moore_block_binding_energy(state,options)+beta*ftd::eft::matched_modified_energy(state.electric,state.magnetic_half,ftd::C_SPEED);}
std::tuple<int,double> mode_fibre(const ftd::eft::ConnectedMooreBlockState& state){std::map<std::tuple<int,int,int>,std::vector<int>> groups;for(int p=0;p<count;++p){const auto&a=state.constituents[p].anchor;groups[{a.x,a.y,a.z}].push_back(p);}int maximum=1;double separation=INFINITY;for(const auto&g:groups){maximum=std::max(maximum,static_cast<int>(g.second.size()));for(std::size_t i=0;i<g.second.size();++i)for(std::size_t j=i+1;j<g.second.size();++j)separation=std::min(separation,(position(state.constituents[g.second[i]])-position(state.constituents[g.second[j]])).mag());}return {maximum,separation};}
double estimate_mode_phase(const ModeArm& arm){long double numerator=0,denominator=0;for(int n=1;n<mode_ticks-1;++n){const double q=arm.ticks[n].q[arm.spec.mode];numerator+=q*(arm.ticks[n+1].q[arm.spec.mode]+arm.ticks[n-1].q[arm.spec.mode]);denominator+=2*q*q;}if(!(denominator>0))return INFINITY;return std::acos(std::clamp(static_cast<double>(numerator/denominator),-1.0,1.0));}
double group_leakage(const ModeArm& arm,const FullModes& modes){const int target_group=modes.modes[arm.spec.mode].group;std::map<int,long double> sums;for(const auto&t:arm.ticks)for(int m=0;m<N;++m)sums[modes.modes[m].group]+=static_cast<long double>(t.q[m])*t.q[m];const double target=std::sqrt(static_cast<double>(sums[target_group]/arm.ticks.size()));double leak=0;for(const auto&entry:sums)if(entry.first!=target_group)leak=std::max(leak,std::sqrt(static_cast<double>(entry.second/arm.ticks.size())));return target>0?leak/target:INFINITY;}

ModeArm run_mode(const ModeSpec& spec,const FullModes& modes,double beta,const ftd::eft::ConnectedMooreBlockOptions& options){ModeArm arm;arm.spec=spec;const auto reference=load_refined_state(spec.orientation);if(reference.electric.L!=L)return arm;auto initial=displaced_mode(reference,modes.modes[spec.mode],spec.target,spec.sign,arm.modal_amplitude,arm.initial_max_displacement);arm.initialization=initial.electric.L==L&&std::abs(arm.initial_max_displacement-spec.target)<=1e-12;if(!arm.initialization)return arm;const auto initial_sector=sector_signature(initial);auto state=initial;const double e0=mode_energy(initial,beta,options),eref=mode_energy(reference,beta,options);arm.initial_excess=e0-eref;arm.sector=true;arm.forward=true;
  ftd::eft::ConnectedMooreBlockSolveCache forward_cache,reverse_cache;
  for(int tick=1;tick<=mode_ticks;++tick){const auto step=ftd::eft::solve_connected_moore_block_forward(state,options,&forward_cache);arm.jacobian_refreshes+=step.solve.jacobian_refreshes;arm.jacobian_reuses+=step.solve.jacobian_reuses;const double residual=common_residual(step);if(!step.valid||!step.common_action_gates_pass||residual>1e-10){arm.forward=false;break;}state=step.later;arm.total_hops+=step.site_hops;arm.sector=arm.sector&&sector_signature(state)==initial_sector;int mult=0;double separation=INFINITY;std::tie(mult,separation)=mode_fibre(state);arm.max_multiplicity=std::max(arm.max_multiplicity,mult);if(std::isfinite(separation))arm.min_separation=std::min(arm.min_separation,separation);ModeTick record;record.tick=tick;record.center=(center(state)-center(reference)).mag();record.state=ftd::eft::connected_moore_block_state_max_difference(reference,state);record.drift=std::abs(mode_energy(state,beta,options)-e0);record.residual=residual;record.multiplicity=mult;record.separation=separation;record.q=project_modes(reference,state,modes);arm.max_center=std::max(arm.max_center,record.center);arm.max_state=std::max(arm.max_state,record.state);arm.max_drift=std::max(arm.max_drift,record.drift);arm.max_common=std::max(arm.max_common,residual);arm.ticks.push_back(std::move(record));}
  arm.forward=arm.forward&&arm.ticks.size()==mode_ticks;if(arm.forward){arm.phase=estimate_mode_phase(arm);arm.phase_error=std::abs(arm.phase-modes.modes[spec.mode].phase)/modes.modes[spec.mode].phase;arm.leakage=group_leakage(arm,modes);}arm.reverse=arm.forward;for(int tick=mode_ticks;arm.reverse&&tick>=1;--tick){const auto step=ftd::eft::solve_connected_moore_block_reverse(state,options,&reverse_cache);arm.jacobian_refreshes+=step.solve.jacobian_refreshes;arm.jacobian_reuses+=step.solve.jacobian_reuses;arm.max_common=std::max(arm.max_common,common_residual(step));if(!step.valid||!step.common_action_gates_pass||common_residual(step)>1e-10){arm.reverse=false;break;}state=step.earlier;arm.total_hops+=step.site_hops;arm.sector=arm.sector&&sector_signature(state)==initial_sector;}if(arm.reverse)arm.recovery=ftd::eft::connected_moore_block_state_max_difference(initial,state);arm.no_hops=arm.total_hops==0;arm.bounded=arm.forward&&arm.reverse&&arm.sector&&arm.no_hops&&arm.max_multiplicity<=8&&(!std::isfinite(arm.min_separation)||arm.min_separation>=.9)&&arm.max_center<=1e-4&&arm.max_state<=1e-3&&arm.max_drift<=1e-12&&arm.max_common<=1e-10&&arm.recovery<=1e-10;return arm;}

const ModeArm* find_arm(const ModeSummary&s,int orientation,int mode,const std::string&kind){for(const auto&a:s.arms)if(a.spec.orientation==orientation&&a.spec.mode==mode&&a.spec.kind==kind)return &a;return nullptr;}
double relative_value(double a,double b){return std::abs(a-b)/std::max({1e-300,std::abs(a),std::abs(b)});}
void evaluate_modes(ModeSummary&s){s.coverage=s.arms.size()==87;for(int m=0;m<N;++m)s.coverage=s.coverage&&find_arm(s,0,m,"primary");for(int m:representative)s.coverage=s.coverage&&find_arm(s,0,m,"half")&&find_arm(s,0,m,"negative")&&find_arm(s,1,m,"cyclic");s.execution=s.coverage&&std::all_of(s.arms.begin(),s.arms.end(),[](const ModeArm&a){return a.initialization&&a.forward&&a.reverse;});s.bounded=s.execution&&std::all_of(s.arms.begin(),s.arms.end(),[](const ModeArm&a){return a.bounded;});s.frequency=s.execution;for(int m=0;m<N;++m){const auto*a=find_arm(s,0,m,"primary");s.frequency=s.frequency&&a&&std::isfinite(a->phase)&&a->phase_error<=.02;}s.purity=s.execution&&std::all_of(s.arms.begin(),s.arms.end(),[](const ModeArm&a){return std::isfinite(a.leakage)&&a.leakage<=.10;});s.amplitude=s.sign=s.covariance=s.execution;s.amplitude_residual=s.sign_residual=s.covariance_residual=0;
  for(int m:representative){const auto*a=find_arm(s,0,m,"primary"),*h=find_arm(s,0,m,"half"),*n=find_arm(s,0,m,"negative"),*y=find_arm(s,1,m,"cyclic");if(!a||!h||!n||!y){s.amplitude=s.sign=s.covariance=false;continue;}const double phase_amp=relative_value(a->phase,h->phase),energy_ratio=a->initial_excess/h->initial_excess;s.amplitude_residual=std::max({s.amplitude_residual,phase_amp,std::abs(energy_ratio-4)});s.amplitude=s.amplitude&&phase_amp<=.005&&energy_ratio>=3.9&&energy_ratio<=4.1;double sign_res=relative_value(a->phase,n->phase);for(int t=0;t<mode_ticks;++t)sign_res=std::max(sign_res,std::abs(a->ticks[t].q[m]+n->ticks[t].q[m])/std::abs(a->modal_amplitude));s.sign_residual=std::max(s.sign_residual,sign_res);s.sign=s.sign&&relative_value(a->phase,n->phase)<=.005&&sign_res<=.05;const double cov=relative_value(a->phase,y->phase);s.covariance_residual=std::max(s.covariance_residual,cov);s.covariance=s.covariance&&cov<=.005;}
  s.spectrum_covariance=0;for(int m=0;m<N;++m)s.spectrum_covariance=std::max(s.spectrum_covariance,relative_value(s.eig[0].modes[m].hessian_eigen,s.eig[1].modes[m].hessian_eigen));s.covariance=s.covariance&&s.spectrum_covariance<=1e-9;for(const auto&a:s.arms){s.worst_common=std::max(s.worst_common,a.max_common);s.worst_drift=std::max(s.worst_drift,a.max_drift);if(std::isfinite(a.recovery))s.worst_recovery=std::max(s.worst_recovery,a.recovery);}if(!s.parent||!s.normalization||!s.eigensystem||!s.coverage)s.verdict="CONNECTED_BLOCK_ANALYTIC_MATTER_MODES_EXECUTION_INVALID";else if(!s.bounded)s.verdict="CONNECTED_BLOCK_ANALYTIC_MATTER_MODE_STABILITY_CLOSED_NEGATIVE";else if(s.frequency&&s.purity&&s.amplitude&&s.sign&&s.covariance)s.verdict="CONNECTED_BLOCK_ANALYTIC_MATTER_MODES_CONSTRUCTIVE";else s.verdict="CONNECTED_BLOCK_ANALYTIC_MATTER_MODES_MIXED";}
void write_modes(const ModeSummary&s){const auto dir=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0640";std::filesystem::create_directories(dir);std::ofstream json(dir/"ftd_0640_connected_block_analytic_matter_modes_v1.json");json<<std::setprecision(17)<<"{\n  \"ftd_id\": \"FTD-0640\",\n  \"protocol_sha256\": \""<<mode_protocol_sha256<<"\",\n  \"parent_result_sha256\": \""<<mode_parent_result_sha256<<"\",\n  \"verdict\": \""<<s.verdict<<"\",\n  \"production_changed\": false,\n  \"arm_count\": "<<s.arms.size()<<",\n  \"ticks_each_direction\": "<<mode_ticks<<",\n  \"coverage_pass\": "<<s.coverage<<",\n  \"execution_pass\": "<<s.execution<<",\n  \"bounded_pass\": "<<s.bounded<<",\n  \"frequency_pass\": "<<s.frequency<<",\n  \"purity_pass\": "<<s.purity<<",\n  \"amplitude_pass\": "<<s.amplitude<<",\n  \"sign_pass\": "<<s.sign<<",\n  \"covariance_pass\": "<<s.covariance<<",\n  \"spectrum_covariance\": "<<s.spectrum_covariance<<",\n  \"amplitude_residual\": "<<s.amplitude_residual<<",\n  \"sign_residual\": "<<s.sign_residual<<",\n  \"covariance_residual\": "<<s.covariance_residual<<",\n  \"worst_common_residual\": "<<s.worst_common<<",\n  \"worst_energy_drift\": "<<s.worst_drift<<",\n  \"worst_recovery\": "<<s.worst_recovery<<"\n}\n";
  std::ofstream modes(dir/"ftd_0640_connected_block_analytic_matter_modes_modes_v1.csv");modes<<"ftd_id,orientation,mode,group,hessian_eigen,lambda,omega,phase,period,max_component";for(int i=0;i<N;++i)modes<<",v"<<i;modes<<'\n';for(int orientation=0;orientation<2;++orientation)for(int m=0;m<N;++m){const auto&x=s.eig[orientation].modes[m];modes<<std::setprecision(17)<<"FTD-0640,"<<orientation<<','<<m<<','<<x.group<<','<<x.hessian_eigen<<','<<x.lambda<<','<<x.omega<<','<<x.phase<<','<<2*std::acos(-1.0)/x.phase<<','<<x.max_component;for(double value:x.vector)modes<<','<<value;modes<<'\n';}
  std::ofstream arms(dir/"ftd_0640_connected_block_analytic_matter_modes_arms_v1.csv");arms<<"ftd_id,label,kind,orientation,mode,sign,target,initialization,forward,reverse,bounded,sector,no_hops,max_multiplicity,min_separation,modal_amplitude,initial_max_displacement,initial_excess,phase,predicted_phase,phase_error,leakage,max_center,max_state,max_drift,max_common,recovery,jacobian_refreshes,jacobian_reuses\n";for(const auto&a:s.arms)arms<<std::setprecision(17)<<"FTD-0640,"<<a.spec.label<<','<<a.spec.kind<<','<<a.spec.orientation<<','<<a.spec.mode<<','<<a.spec.sign<<','<<a.spec.target<<','<<a.initialization<<','<<a.forward<<','<<a.reverse<<','<<a.bounded<<','<<a.sector<<','<<a.no_hops<<','<<a.max_multiplicity<<','<<a.min_separation<<','<<a.modal_amplitude<<','<<a.initial_max_displacement<<','<<a.initial_excess<<','<<a.phase<<','<<s.eig[a.spec.orientation].modes[a.spec.mode].phase<<','<<a.phase_error<<','<<a.leakage<<','<<a.max_center<<','<<a.max_state<<','<<a.max_drift<<','<<a.max_common<<','<<a.recovery<<','<<a.jacobian_refreshes<<','<<a.jacobian_reuses<<'\n';
  std::ofstream ticks(dir/"ftd_0640_connected_block_analytic_matter_modes_ticks_v1.csv");ticks<<"ftd_id,label,tick,center,state,drift,residual,multiplicity,separation";for(int m=0;m<N;++m)ticks<<",q"<<m;ticks<<'\n';for(const auto&a:s.arms)for(const auto&t:a.ticks){ticks<<std::setprecision(17)<<"FTD-0640,"<<a.spec.label<<','<<t.tick<<','<<t.center<<','<<t.state<<','<<t.drift<<','<<t.residual<<','<<t.multiplicity<<','<<t.separation;for(double q:t.q)ticks<<','<<q;ticks<<'\n';}}
}

#ifdef FTD_0640_EMBEDDED
int ftd_0640_embedded_main(){
#else
int main(){
#endif
  ModeSummary summary;summary.parent=mode_parent_fingerprint();const auto normalization=ftd::eft::measure_face_flux_normalization();summary.normalization=normalization.valid;summary.beta=normalization.mapped_field_work_coefficient;ftd::eft::ConnectedMooreBlockOptions options;options.allow_shared_anchor_chart=true;if(summary.parent&&summary.normalization){for(int orientation=0;orientation<2;++orientation){const auto state=load_refined_state(orientation);const auto analytic=analytic_at(orientation==0?"mode_x":"mode_y",orientation,state,summary.beta,options);if(analytic.valid)summary.eig[orientation]=full_modes(analytic.hessian);}summary.eigensystem=summary.eig[0].valid&&summary.eig[1].valid;}
  std::vector<ModeSpec> specs;if(summary.eigensystem){for(int m=0;m<N;++m)specs.push_back({"x_m"+std::to_string(m)+"_full","primary",0,m,+1,full_target});for(int m:representative){specs.push_back({"x_m"+std::to_string(m)+"_half","half",0,m,+1,half_target});specs.push_back({"x_m"+std::to_string(m)+"_negative","negative",0,m,-1,full_target});specs.push_back({"y_m"+std::to_string(m)+"_cyclic","cyclic",1,m,+1,full_target});}}
  if(summary.eigensystem){constexpr std::size_t batch=24;for(std::size_t start=0;start<specs.size();start+=batch){std::vector<std::future<ModeArm>> futures;const auto end=std::min(specs.size(),start+batch);for(std::size_t i=start;i<end;++i)futures.push_back(std::async(std::launch::async,[&,spec=specs[i]](){return run_mode(spec,summary.eig[spec.orientation],summary.beta,options);}));for(std::size_t i=start;i<end;++i){summary.arms.push_back(futures[i-start].get());std::cout<<"completed "<<specs[i].label<<std::endl;}}}
  evaluate_modes(summary);write_modes(summary);std::cout<<std::setprecision(17)<<"protocol_sha256="<<mode_protocol_sha256<<'\n'<<"verdict="<<summary.verdict<<'\n'<<"coverage="<<summary.coverage<<" bounded="<<summary.bounded<<" frequency="<<summary.frequency<<" purity="<<summary.purity<<" amplitude="<<summary.amplitude<<" sign="<<summary.sign<<" covariance="<<summary.covariance<<'\n'<<"spectrum_covariance="<<summary.spectrum_covariance<<" amplitude_residual="<<summary.amplitude_residual<<" sign_residual="<<summary.sign_residual<<" covariance_residual="<<summary.covariance_residual<<'\n';for(const auto&a:summary.arms)if(a.phase_error>.02||a.leakage>.10||!a.bounded)std::cout<<a.spec.label<<" bounded="<<a.bounded<<" phase="<<a.phase<<" error="<<a.phase_error<<" leakage="<<a.leakage<<" state="<<a.max_state<<" recovery="<<a.recovery<<'\n';return summary.verdict=="CONNECTED_BLOCK_ANALYTIC_MATTER_MODES_EXECUTION_INVALID"?1:0;}
