// FTD-0694: indexed local-root execution of the L=113 discriminator.
#define FTD_SEPARATION_PROTOCOL_SHA256 \
  "29DE3DCA11FEC2C77F5A765F89CCF4FDD06379CD23FE9A9EE73B044025B5025A"
#define FTD_SEPARATION_IDENTIFIER "FTD-0694"
#define FTD_SEPARATION_RESULT_DIRECTORY "results/ftd_0694"
#define FTD_SEPARATION_RESULT_STEM \
  "ftd_0694_causal_excitation_separation_indexed_local_v1"
#define FTD_SEPARATION_CENTER_TOLERANCE 1e-12
#define FTD_SEPARATION_USE_BATCHED_REGIONAL 1
#define FTD_SEPARATION_USE_LOCAL_RESIDUAL 1
#define FTD_SEPARATION_VOLUME 113
#define FTD_SEPARATION_HORIZON 96
#define FTD_SEPARATION_LATE_START 80
#define FTD_SEPARATION_LATE_END 96
#define FTD_SEPARATION_PROGRESS_INTERVAL 1
#define FTD_SEPARATION_OBSERVATION_CADENCE 4
#include "test_causal_excitation_separation_v1.cpp"

