// FTD-0642: coupled response of exact-center matter to transverse field modes.

#define FTD_0640_EMBEDDED
#include "test_connected_block_analytic_matter_modes.cpp"
#undef FTD_0640_EMBEDDED

namespace {

constexpr char coupled_protocol_sha256[] =
    "74CA689FEF47322CA54AC9C2A9C412B895CA0CC94BFAB5AEE63404355E031A78";
constexpr char coupled_matter_parent_sha256[] =
    "AB43D342CFE48BEF452955E56B1EDC34F9EE51911F7D899932E7E542877E6B9A";
constexpr char coupled_field_parent_sha256[] =
    "EA24EF12476533DB8395C0E64C1E381A6605662EAA9ED35C1E38D66D560189E6";
constexpr int coupled_ticks=256;
constexpr double coupled_full=1e-7,coupled_half=5e-8;

struct CoupledSpec { std::string label,kind,family;std::array<int,3>wave{};int polarization=0,sign=1;double target=0; };
struct CoupledTick { int tick=0;double field_q=0,bare_q=0,electric_orthogonal2=0,matter_coordinate_rms=0,center=0,state=0,drift=0,residual=0;std::vector<double> matter_q; };
struct CoupledArm {
  CoupledSpec spec;bool initialized=false,forward=false,reverse=false,bounded=false,sector=false,no_hops=false;
  int max_multiplicity=0,total_hops=0;double min_separation=INFINITY,phase=INFINITY,bare_phase=INFINITY,phase_shift=INFINITY,field_distortion=INFINITY,field_leakage=INFINITY,matter_rms=INFINITY,max_center=0,max_state=0,max_drift=0,max_common=0,recovery=INFINITY;std::vector<CoupledTick> ticks;
};
struct CoupledSummary {
  bool matter_parent=false,field_parent=false,eigensystem=false,coverage=false,execution=false,bounded=false,coupling=false,decoupled=false,linearity=false,weak=false;
  double worst_phase_shift=0,worst_distortion=0,worst_leakage=0,worst_common=0,worst_drift=0,worst_recovery=0,amplitude_residual=0,sign_residual=0;
  std::string verdict="CONNECTED_BLOCK_COUPLED_TRANSVERSE_EXECUTION_INVALID";FullModes modes;std::vector<CoupledArm> arms;
};

bool coupled_parent(const std::string& folder,const std::string& file,const std::string& hash,const std::string& verdict){const auto path=std::filesystem::path(__FILE__).parent_path().parent_path()/"results"/folder/file;std::ifstream input(path,std::ios::binary);const std::string bytes((std::istreambuf_iterator<char>(input)),{});return bytes.find(hash)!=std::string::npos||bytes.find(verdict)!=std::string::npos;}
void coupled_add(ftd::eft::MatchedFaceFlux& target,const ftd::eft::MatchedFaceFlux& delta,double scale=1){for(std::size_t i=0;i<target.x.size();++i){target.x[i]+=scale*delta.x[i];target.y[i]+=scale*delta.y[i];target.z[i]+=scale*delta.z[i];}}
ftd::eft::MatchedFaceFlux coupled_difference(const ftd::eft::MatchedFaceFlux&a,const ftd::eft::MatchedFaceFlux&b){ftd::eft::MatchedFaceFlux d(a.L);for(std::size_t i=0;i<d.x.size();++i){d.x[i]=a.x[i]-b.x[i];d.y[i]=a.y[i]-b.y[i];d.z[i]=a.z[i]-b.z[i];}return d;}
double coupled_face_dot(const ftd::eft::MatchedFaceFlux&a,const ftd::eft::MatchedFaceFlux&b){return static_cast<double>(ftd::eft::matched_face_dot(a,b));}
double coupled_field_max(const ftd::eft::MatchedFaceFlux&e){double r=0;for(std::size_t i=0;i<e.x.size();++i)r=std::max({r,std::abs(e.x[i]),std::abs(e.y[i]),std::abs(e.z[i])});return r;}
void coupled_advance_field(ftd::eft::MatchedFaceFlux&e,ftd::eft::MatchedEdgeField&b){const auto ce=ftd::eft::matched_curl_adjoint(e);for(std::size_t i=0;i<b.x.size();++i){b.x[i]-=ftd::C_SPEED*ce.x[i];b.y[i]-=ftd::C_SPEED*ce.y[i];b.z[i]-=ftd::C_SPEED*ce.z[i];}const auto cb=ftd::eft::matched_curl(b);for(std::size_t i=0;i<e.x.size();++i){e.x[i]+=ftd::C_SPEED*cb.x[i];e.y[i]+=ftd::C_SPEED*cb.y[i];e.z[i]+=ftd::C_SPEED*cb.z[i];}}

ftd::eft::MatchedFaceFlux coupled_shape(const CoupledSpec&spec){ftd::eft::MatchedEdgeField potential(L);int accepted=-1;for(int axis=0,count_axis=0;axis<3;++axis){ftd::eft::MatchedEdgeField candidate(L);for(int x=0;x<L;++x)for(int y=0;y<L;++y)for(int z=0;z<L;++z){const int i=candidate.index(x,y,z);const double phase=2*ftd::PI*(spec.wave[0]*x+spec.wave[1]*y+spec.wave[2]*z)/L;const double value=std::cos(phase);if(axis==0)candidate.x[i]=value;if(axis==1)candidate.y[i]=value;if(axis==2)candidate.z[i]=value;}const auto curl=ftd::eft::matched_curl(candidate);if(coupled_field_max(curl)>1e-12){if(count_axis==spec.polarization){potential=std::move(candidate);accepted=axis;break;}++count_axis;}}auto result=ftd::eft::matched_curl(potential);const double maximum=coupled_field_max(result);if(accepted<0||maximum<=0)return ftd::eft::MatchedFaceFlux{};for(std::size_t i=0;i<result.x.size();++i){result.x[i]/=maximum;result.y[i]/=maximum;result.z[i]/=maximum;}return result;}
double coupled_phase(const std::vector<CoupledTick>&ticks,bool bare){long double numerator=0,denominator=0;for(int n=1;n<coupled_ticks-1;++n){const double q=bare?ticks[n].bare_q:ticks[n].field_q,qp=bare?ticks[n+1].bare_q:ticks[n+1].field_q,qm=bare?ticks[n-1].bare_q:ticks[n-1].field_q;numerator+=q*(qp+qm);denominator+=2*q*q;}return denominator>0?std::acos(std::clamp(static_cast<double>(numerator/denominator),-1.0,1.0)):INFINITY;}

CoupledArm run_coupled(const CoupledSpec&spec,const FullModes&modes,double beta,const ftd::eft::ConnectedMooreBlockOptions&options){CoupledArm arm;arm.spec=spec;const auto reference=load_refined_state(0);const auto unit=coupled_shape(spec);if(reference.electric.L!=L||unit.L!=L)return arm;auto initial=reference;coupled_add(initial.electric,unit,spec.sign*spec.target);const double seeded=coupled_field_max(coupled_difference(initial.electric,reference.electric));arm.initialized=std::abs(seeded-spec.target)<=1e-14&&ftd::eft::max_divergence(coupled_difference(initial.electric,reference.electric))<=1e-12;if(!arm.initialized)return arm;auto state=initial;const auto initial_sector=sector_signature(initial);const double e0=mode_energy(initial,beta,options),denominator=coupled_face_dot(unit,unit);ftd::eft::MatchedFaceFlux bare_e(L);ftd::eft::MatchedEdgeField bare_b(L);coupled_add(bare_e,unit,spec.sign*spec.target);ftd::eft::ConnectedMooreBlockSolveCache forward_cache,reverse_cache;arm.sector=true;arm.forward=true;long double matter_power=0,field_difference_power=0,bare_power=0,orthogonal_power=0,projected_power=0;
  for(int tick=1;tick<=coupled_ticks;++tick){const auto step=ftd::eft::solve_connected_moore_block_forward(state,options,&forward_cache);const double residual=common_residual(step);if(!step.valid||!step.common_action_gates_pass||residual>1e-10){arm.forward=false;break;}state=step.later;coupled_advance_field(bare_e,bare_b);const auto delta=coupled_difference(state.electric,reference.electric);CoupledTick row;row.tick=tick;row.field_q=coupled_face_dot(delta,unit)/denominator;row.bare_q=coupled_face_dot(bare_e,unit)/denominator;const double total2=std::max(0.0,coupled_face_dot(delta,delta)),projected2=row.field_q*row.field_q*denominator;row.electric_orthogonal2=std::max(0.0,total2-projected2);row.matter_q=project_modes(reference,state,modes);long double coordinate2=0;for(int p=0;p<count;++p){const Vec3 dx=position(state.constituents[p])-position(reference.constituents[p]);coordinate2+=dx.dot(dx);}row.matter_coordinate_rms=std::sqrt(static_cast<double>(coordinate2/N));row.center=(center(state)-center(reference)).mag();row.state=ftd::eft::connected_moore_block_state_max_difference(reference,state);row.drift=std::abs(total_after(step)-e0);row.residual=residual;for(double q:row.matter_q)matter_power+=static_cast<long double>(q)*q;field_difference_power+=static_cast<long double>(row.field_q-row.bare_q)*(row.field_q-row.bare_q);bare_power+=static_cast<long double>(row.bare_q)*row.bare_q;orthogonal_power+=row.electric_orthogonal2;projected_power+=projected2;arm.max_center=std::max(arm.max_center,row.center);arm.max_state=std::max(arm.max_state,row.state);arm.max_drift=std::max(arm.max_drift,row.drift);arm.max_common=std::max(arm.max_common,residual);arm.total_hops+=step.site_hops;arm.sector=arm.sector&&sector_signature(state)==initial_sector;int mult=0;double separation=INFINITY;std::tie(mult,separation)=mode_fibre(state);arm.max_multiplicity=std::max(arm.max_multiplicity,mult);if(std::isfinite(separation))arm.min_separation=std::min(arm.min_separation,separation);arm.ticks.push_back(std::move(row));}
  arm.forward=arm.forward&&arm.ticks.size()==coupled_ticks;if(arm.forward){arm.phase=coupled_phase(arm.ticks,false);arm.bare_phase=coupled_phase(arm.ticks,true);arm.phase_shift=relative_value(arm.phase,arm.bare_phase);arm.field_distortion=bare_power>0?std::sqrt(static_cast<double>(field_difference_power/bare_power)):INFINITY;arm.field_leakage=projected_power>0?std::sqrt(static_cast<double>(orthogonal_power/projected_power)):INFINITY;arm.matter_rms=std::sqrt(static_cast<double>(matter_power/coupled_ticks));}arm.reverse=arm.forward;for(int tick=coupled_ticks;arm.reverse&&tick>=1;--tick){const auto step=ftd::eft::solve_connected_moore_block_reverse(state,options,&reverse_cache);arm.max_common=std::max(arm.max_common,common_residual(step));if(!step.valid||!step.common_action_gates_pass||common_residual(step)>1e-10){arm.reverse=false;break;}state=step.earlier;arm.total_hops+=step.site_hops;arm.sector=arm.sector&&sector_signature(state)==initial_sector;}if(arm.reverse)arm.recovery=ftd::eft::connected_moore_block_state_max_difference(initial,state);arm.no_hops=arm.total_hops==0;arm.bounded=arm.forward&&arm.reverse&&arm.sector&&arm.no_hops&&arm.max_multiplicity<=8&&(!std::isfinite(arm.min_separation)||arm.min_separation>=.9)&&arm.max_center<=1e-3&&arm.max_state<=1e-3&&arm.max_drift<=1e-12&&arm.max_common<=1e-10&&arm.recovery<=1e-10;return arm;}

const CoupledArm* find_coupled(const CoupledSummary&s,const std::string&family,int pol,const std::string&kind){for(const auto&a:s.arms)if(a.spec.family==family&&a.spec.polarization==pol&&a.spec.kind==kind)return &a;return nullptr;}
void evaluate_coupled(CoupledSummary&s){s.coverage=s.arms.size()==18;s.execution=s.coverage&&std::all_of(s.arms.begin(),s.arms.end(),[](const CoupledArm&a){return a.initialized&&a.forward&&a.reverse;});s.bounded=s.execution&&std::all_of(s.arms.begin(),s.arms.end(),[](const CoupledArm&a){return a.bounded;});s.coupling=s.bounded;s.decoupled=s.bounded;s.linearity=s.bounded;s.weak=s.bounded;s.amplitude_residual=s.sign_residual=0;for(const auto&a:s.arms)if(a.spec.kind=="primary"){s.coupling=s.coupling&&a.matter_rms>1e-9;s.decoupled=s.decoupled&&a.matter_rms<=1e-9;s.weak=s.weak&&std::isfinite(a.phase)&&a.phase_shift<=.05&&a.field_distortion<=.25&&a.field_leakage<=.25;s.worst_phase_shift=std::max(s.worst_phase_shift,a.phase_shift);s.worst_distortion=std::max(s.worst_distortion,a.field_distortion);s.worst_leakage=std::max(s.worst_leakage,a.field_leakage);}for(const std::string family:{"100","110","111"})for(int pol=0;pol<2;++pol){const auto*f=find_coupled(s,family,pol,"primary"),*h=find_coupled(s,family,pol,"half"),*n=find_coupled(s,family,pol,"negative");if(!f||!h||!n||!(h->matter_rms>0)){s.linearity=false;continue;}const double ratio=f->matter_rms/h->matter_rms,phase_amp=relative_value(f->phase,h->phase),phase_sign=relative_value(f->phase,n->phase);double field_sign=0;long double matter_num=0,matter_den=0;for(int t=0;t<coupled_ticks;++t){field_sign=std::max(field_sign,std::abs(f->ticks[t].field_q+n->ticks[t].field_q)/coupled_full);for(int m=0;m<N;++m){const double sum=f->ticks[t].matter_q[m]+n->ticks[t].matter_q[m];matter_num+=static_cast<long double>(sum)*sum;matter_den+=static_cast<long double>(f->ticks[t].matter_q[m])*f->ticks[t].matter_q[m];}}const double matter_sign=matter_den>0?std::sqrt(static_cast<double>(matter_num/matter_den)):INFINITY;s.amplitude_residual=std::max({s.amplitude_residual,std::abs(ratio-2),phase_amp});s.sign_residual=std::max({s.sign_residual,phase_sign,field_sign,matter_sign});s.linearity=s.linearity&&ratio>=1.8&&ratio<=2.2&&phase_amp<=.01&&phase_sign<=.01&&field_sign<=.1&&matter_sign<=.1;}for(const auto&a:s.arms){s.worst_common=std::max(s.worst_common,a.max_common);s.worst_drift=std::max(s.worst_drift,a.max_drift);if(std::isfinite(a.recovery))s.worst_recovery=std::max(s.worst_recovery,a.recovery);}if(!s.matter_parent||!s.field_parent||!s.eigensystem||!s.coverage)s.verdict="CONNECTED_BLOCK_COUPLED_TRANSVERSE_EXECUTION_INVALID";else if(!s.bounded)s.verdict="CONNECTED_BLOCK_COUPLED_TRANSVERSE_CLOSED_NEGATIVE";else if(s.coupling&&s.linearity&&s.weak)s.verdict="CONNECTED_BLOCK_COUPLED_TRANSVERSE_WEAK_HYBRID_CONSTRUCTIVE";else if(s.coupling&&s.linearity)s.verdict="CONNECTED_BLOCK_COUPLED_TRANSVERSE_STRONG_HYBRID_CONSTRUCTIVE";else if(s.decoupled)s.verdict="CONNECTED_BLOCK_COUPLED_TRANSVERSE_DECOUPLED";else s.verdict="CONNECTED_BLOCK_COUPLED_TRANSVERSE_MIXED";}

void write_coupled(const CoupledSummary&s){const auto dir=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0642";std::filesystem::create_directories(dir);std::ofstream json(dir/"ftd_0642_connected_block_coupled_transverse_response_v1.json");json<<std::setprecision(17)<<"{\n  \"ftd_id\": \"FTD-0642\",\n  \"protocol_sha256\": \""<<coupled_protocol_sha256<<"\",\n  \"matter_parent_sha256\": \""<<coupled_matter_parent_sha256<<"\",\n  \"field_parent_sha256\": \""<<coupled_field_parent_sha256<<"\",\n  \"verdict\": \""<<s.verdict<<"\",\n  \"production_changed\": false,\n  \"arm_count\": "<<s.arms.size()<<",\n  \"ticks_each_direction\": "<<coupled_ticks<<",\n  \"coverage_pass\": "<<s.coverage<<",\n  \"execution_pass\": "<<s.execution<<",\n  \"bounded_pass\": "<<s.bounded<<",\n  \"coupling_pass\": "<<s.coupling<<",\n  \"decoupled_pass\": "<<s.decoupled<<",\n  \"linearity_pass\": "<<s.linearity<<",\n  \"weak_hybrid_pass\": "<<s.weak<<",\n  \"worst_phase_shift\": "<<s.worst_phase_shift<<",\n  \"worst_field_distortion\": "<<s.worst_distortion<<",\n  \"worst_field_leakage\": "<<s.worst_leakage<<",\n  \"amplitude_residual\": "<<s.amplitude_residual<<",\n  \"sign_residual\": "<<s.sign_residual<<",\n  \"worst_common_residual\": "<<s.worst_common<<",\n  \"worst_energy_drift\": "<<s.worst_drift<<",\n  \"worst_recovery\": "<<s.worst_recovery<<"\n}\n";
  std::ofstream arms(dir/"ftd_0642_connected_block_coupled_transverse_response_arms_v1.csv");arms<<"ftd_id,label,kind,family,nx,ny,nz,polarization,sign,target,initialized,forward,reverse,bounded,sector,no_hops,max_multiplicity,min_separation,phase,bare_phase,phase_shift,field_distortion,field_leakage,matter_rms,max_center,max_state,max_drift,max_common,recovery\n";for(const auto&a:s.arms)arms<<std::setprecision(17)<<"FTD-0642,"<<a.spec.label<<','<<a.spec.kind<<','<<a.spec.family<<','<<a.spec.wave[0]<<','<<a.spec.wave[1]<<','<<a.spec.wave[2]<<','<<a.spec.polarization<<','<<a.spec.sign<<','<<a.spec.target<<','<<a.initialized<<','<<a.forward<<','<<a.reverse<<','<<a.bounded<<','<<a.sector<<','<<a.no_hops<<','<<a.max_multiplicity<<','<<a.min_separation<<','<<a.phase<<','<<a.bare_phase<<','<<a.phase_shift<<','<<a.field_distortion<<','<<a.field_leakage<<','<<a.matter_rms<<','<<a.max_center<<','<<a.max_state<<','<<a.max_drift<<','<<a.max_common<<','<<a.recovery<<'\n';
  std::ofstream ticks(dir/"ftd_0642_connected_block_coupled_transverse_response_ticks_v1.csv");ticks<<"ftd_id,label,tick,field_q,bare_q,electric_orthogonal2,matter_coordinate_rms,center,state,drift,residual";for(int m=0;m<N;++m)ticks<<",matter_q"<<m;ticks<<'\n';for(const auto&a:s.arms)for(const auto&t:a.ticks){ticks<<std::setprecision(17)<<"FTD-0642,"<<a.spec.label<<','<<t.tick<<','<<t.field_q<<','<<t.bare_q<<','<<t.electric_orthogonal2<<','<<t.matter_coordinate_rms<<','<<t.center<<','<<t.state<<','<<t.drift<<','<<t.residual;for(double q:t.matter_q)ticks<<','<<q;ticks<<'\n';}}

std::vector<CoupledSpec> coupled_specs(){std::vector<CoupledSpec>s;for(const auto&entry:std::vector<std::pair<std::string,std::array<int,3>>>{{"100",{1,0,0}},{"110",{1,1,0}},{"111",{1,1,1}}})for(int pol=0;pol<2;++pol){const auto prefix=entry.first+"_e"+std::to_string(pol);s.push_back({prefix+"_full","primary",entry.first,entry.second,pol,+1,coupled_full});s.push_back({prefix+"_half","half",entry.first,entry.second,pol,+1,coupled_half});s.push_back({prefix+"_negative","negative",entry.first,entry.second,pol,-1,coupled_full});}return s;}
}

int main(){CoupledSummary summary;summary.matter_parent=coupled_parent("ftd_0640","ftd_0640_connected_block_analytic_matter_modes_v1.json",coupled_matter_parent_sha256,"CONNECTED_BLOCK_ANALYTIC_MATTER_MODES_CONSTRUCTIVE");summary.field_parent=coupled_parent("ftd_0641","ftd_0641_connected_block_independent_field_modes_v1.json",coupled_field_parent_sha256,"CONNECTED_BLOCK_INDEPENDENT_FIELD_MODES_CONSTRUCTIVE");const auto normalization=ftd::eft::measure_face_flux_normalization();ftd::eft::ConnectedMooreBlockOptions options;options.allow_shared_anchor_chart=true;if(summary.matter_parent&&summary.field_parent&&normalization.valid){const auto reference=load_refined_state(0);const auto analytic=analytic_at("coupled",0,reference,normalization.mapped_field_work_coefficient,options);if(analytic.valid)summary.modes=full_modes(analytic.hessian);summary.eigensystem=summary.modes.valid;}if(summary.eigensystem){const auto specs=coupled_specs();constexpr std::size_t batch=6;for(std::size_t start=0;start<specs.size();start+=batch){std::vector<std::future<CoupledArm>> futures;const auto end=std::min(specs.size(),start+batch);for(std::size_t i=start;i<end;++i)futures.push_back(std::async(std::launch::async,[&,spec=specs[i]](){return run_coupled(spec,summary.modes,normalization.mapped_field_work_coefficient,options);}));for(std::size_t i=start;i<end;++i){summary.arms.push_back(futures[i-start].get());std::cout<<"completed "<<specs[i].label<<std::endl;}}}evaluate_coupled(summary);write_coupled(summary);std::cout<<std::setprecision(17)<<"protocol_sha256="<<coupled_protocol_sha256<<'\n'<<"verdict="<<summary.verdict<<'\n'<<"coverage="<<summary.coverage<<" bounded="<<summary.bounded<<" coupling="<<summary.coupling<<" decoupled="<<summary.decoupled<<" linearity="<<summary.linearity<<" weak="<<summary.weak<<'\n'<<"phase_shift="<<summary.worst_phase_shift<<" distortion="<<summary.worst_distortion<<" leakage="<<summary.worst_leakage<<" amplitude="<<summary.amplitude_residual<<" sign="<<summary.sign_residual<<'\n';for(const auto&a:summary.arms)std::cout<<a.spec.label<<" bounded="<<a.bounded<<" matter="<<a.matter_rms<<" phase_shift="<<a.phase_shift<<" distortion="<<a.field_distortion<<" leakage="<<a.field_leakage<<" recovery="<<a.recovery<<'\n';return summary.verdict=="CONNECTED_BLOCK_COUPLED_TRANSVERSE_EXECUTION_INVALID"?1:0;}
