// FTD-0645: covariant soft-basis correction for the collective boost ladder.

#define FTD_0644_EMBEDDED
#include "test_analytic_center_collective_boost_ladder_v2.cpp"
#undef FTD_0644_EMBEDDED

namespace {
constexpr char boost_v3_protocol_sha256[]="7E8C98F2ECABC80DE4D27ECA21CFA151922C16CADF0DFC05FD30DD0902B14A1D";

void write_boost_v3(const BoostSummary&s,bool rotation_preflight,double rotation_energy,double rotation_spectrum){const auto dir=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0645";std::filesystem::create_directories(dir);std::ofstream json(dir/"ftd_0645_analytic_center_collective_boost_ladder_v3.json");json<<std::setprecision(17)<<"{\n  \"ftd_id\": \"FTD-0645\",\n  \"protocol_sha256\": \""<<boost_v3_protocol_sha256<<"\",\n  \"parent_result_sha256\": \""<<boost_parent_sha256<<"\",\n  \"verdict\": \""<<s.verdict<<"\",\n  \"production_changed\": false,\n  \"arm_count\": "<<s.arms.size()<<",\n  \"ticks_each_direction\": "<<boost_ticks<<",\n  \"rotation_preflight_pass\": "<<rotation_preflight<<",\n  \"rotation_energy_residual\": "<<rotation_energy<<",\n  \"rotation_spectrum_residual\": "<<rotation_spectrum<<",\n  \"coverage_pass\": "<<s.coverage<<",\n  \"execution_pass\": "<<s.execution<<",\n  \"coherence_pass\": "<<s.coherence<<",\n  \"rest_pass\": "<<s.rest<<",\n  \"high_boost_pass\": "<<s.high<<",\n  \"monotonic_pass\": "<<s.monotonic<<",\n  \"mirror_pass\": "<<s.mirror<<",\n  \"cubic_pass\": "<<s.cubic<<",\n  \"last_pinned_100\": "<<s.last_pinned[0]<<",\n  \"last_pinned_110\": "<<s.last_pinned[1]<<",\n  \"last_pinned_111\": "<<s.last_pinned[2]<<",\n  \"first_mobile_100\": "<<s.first_mobile[0]<<",\n  \"first_mobile_110\": "<<s.first_mobile[1]<<",\n  \"first_mobile_111\": "<<s.first_mobile[2]<<",\n  \"mirror_residual\": "<<s.mirror_residual<<",\n  \"cubic_residual\": "<<s.cubic_residual<<",\n  \"worst_common_residual\": "<<s.worst_common<<",\n  \"worst_energy_drift\": "<<s.worst_drift<<",\n  \"worst_recovery\": "<<s.worst_recovery<<",\n  \"worst_shape\": "<<s.worst_shape<<",\n  \"worst_strain\": "<<s.worst_strain<<",\n  \"worst_dressing\": "<<s.worst_dressing<<"\n}\n";
  std::ofstream arms(dir/"ftd_0645_analytic_center_collective_boost_ladder_arms_v3.csv");arms<<"ftd_id,label,kind,family,p,dir_x,dir_y,dir_z,map_count,initialized,forward,reverse,coherent,rest,high,onset,total_hops,free_displacement,projected,transverse,mobility,soft_fraction,max_dressing,max_shape,max_strain,max_drift,max_common,recovery,disp_x,disp_y,disp_z,momentum_x,momentum_y,momentum_z,final_velocity,max_multiplicity,min_separation\n";for(const auto&a:s.arms)arms<<std::setprecision(17)<<"FTD-0645,"<<a.spec.label<<','<<a.spec.kind<<','<<a.spec.family<<','<<a.spec.p<<','<<a.spec.direction.x<<','<<a.spec.direction.y<<','<<a.spec.direction.z<<','<<a.spec.map_count<<','<<a.initialized<<','<<a.forward<<','<<a.reverse<<','<<a.coherent<<','<<a.rest<<','<<a.high<<','<<a.onset<<','<<a.total_hops<<','<<a.free_displacement<<','<<a.projected<<','<<a.transverse<<','<<a.mobility<<','<<a.soft_fraction<<','<<a.max_dressing<<','<<a.max_shape<<','<<a.max_strain<<','<<a.max_drift<<','<<a.max_common<<','<<a.recovery<<','<<a.displacement.x<<','<<a.displacement.y<<','<<a.displacement.z<<','<<a.final_momentum.x<<','<<a.final_momentum.y<<','<<a.final_momentum.z<<','<<a.final_velocity<<','<<a.max_multiplicity<<','<<a.min_separation<<'\n';
  std::ofstream ticks(dir/"ftd_0645_analytic_center_collective_boost_ladder_ticks_v3.csv");ticks<<"ftd_id,label,tick,hops,disp_x,disp_y,disp_z,momentum_x,momentum_y,momentum_z,velocity_x,velocity_y,velocity_z,shape,strain,field_energy,drift,residual,multiplicity,separation,dressing,soft_fraction";for(int i=0;i<N;++i)ticks<<",q"<<i;ticks<<'\n';for(const auto&a:s.arms)for(const auto&t:a.ticks){ticks<<std::setprecision(17)<<"FTD-0645,"<<a.spec.label<<','<<t.tick<<','<<t.hops<<','<<t.displacement.x<<','<<t.displacement.y<<','<<t.displacement.z<<','<<t.momentum.x<<','<<t.momentum.y<<','<<t.momentum.z<<','<<t.velocity.x<<','<<t.velocity.y<<','<<t.velocity.z<<','<<t.shape<<','<<t.strain<<','<<t.field_energy<<','<<t.drift<<','<<t.residual<<','<<t.multiplicity<<','<<t.separation<<','<<t.dressing<<','<<t.soft_fraction;for(double q:t.q)ticks<<','<<q;ticks<<'\n';}}
}
int main(){BoostSummary s;s.parent=boost_parent();const auto normalization=ftd::eft::measure_face_flux_normalization();s.beta=normalization.mapped_field_work_coefficient;ftd::eft::ConnectedMooreBlockOptions options;options.allow_shared_anchor_chart=true;double rotation_energy=0,rotation_spectrum=0;bool rotation_preflight=false;std::array<FullModes,3> bases;if(s.parent&&normalization.valid){for(int maps=0;maps<3;++maps){const auto r=rotated_boost_reference(maps);const auto ar=analytic_at("boost_v3",0,r,s.beta,options);if(ar.valid)bases[maps]=full_modes(ar.hessian);}s.modes=bases[0];s.eigensystem=std::all_of(bases.begin(),bases.end(),[](const FullModes&m){return m.valid;});rotation_preflight=s.eigensystem;const auto base=rotated_boost_reference(0);for(int maps:{1,2}){const auto r=rotated_boost_reference(maps);rotation_energy=std::max(rotation_energy,std::abs(mode_energy(r,s.beta,options)-mode_energy(base,s.beta,options)));for(int i=0;i<N;++i)rotation_spectrum=std::max(rotation_spectrum,relative_value(bases[maps].modes[i].hessian_eigen,bases[0].modes[i].hessian_eigen));}rotation_preflight=rotation_preflight&&rotation_energy<=1e-9&&rotation_spectrum<=1e-9;}if(s.eigensystem&&rotation_preflight){const auto specs=boost_specs();constexpr std::size_t batch=8;for(std::size_t start=0;start<specs.size();start+=batch){std::vector<std::future<BoostArm>> futures;const auto end=std::min(specs.size(),start+batch);for(std::size_t i=start;i<end;++i)futures.push_back(std::async(std::launch::async,[&,spec=specs[i]](){return run_boost_v2(spec,bases[spec.kind=="cyclic"?spec.map_count:0],s.beta,options);}));for(std::size_t i=start;i<end;++i){s.arms.push_back(futures[i-start].get());std::cout<<"completed "<<specs[i].label<<std::endl;}}}evaluate_boost_v2(s,rotation_preflight);if(s.verdict.rfind("ANALYTIC_CENTER_V2_",0)==0)s.verdict.replace(0,std::string("ANALYTIC_CENTER_V2_").size(),"ANALYTIC_CENTER_V3_");write_boost_v3(s,rotation_preflight,rotation_energy,rotation_spectrum);std::cout<<std::setprecision(17)<<"protocol_sha256="<<boost_v3_protocol_sha256<<'\n'<<"verdict="<<s.verdict<<'\n'<<"rotation="<<rotation_preflight<<" energy="<<rotation_energy<<" spectrum="<<rotation_spectrum<<'\n'<<"coverage="<<s.coverage<<" execution="<<s.execution<<" coherence="<<s.coherence<<" rest="<<s.rest<<" high="<<s.high<<" monotonic="<<s.monotonic<<" mirror="<<s.mirror<<" cubic="<<s.cubic<<'\n'<<"pinned="<<s.last_pinned[0]<<','<<s.last_pinned[1]<<','<<s.last_pinned[2]<<" mobile="<<s.first_mobile[0]<<','<<s.first_mobile[1]<<','<<s.first_mobile[2]<<'\n';for(const auto&a:s.arms)std::cout<<a.spec.label<<" coherent="<<a.coherent<<" onset="<<a.onset<<" D="<<a.projected<<" mu="<<a.mobility<<" hops="<<a.total_hops<<" soft="<<a.soft_fraction<<" dressing="<<a.max_dressing<<" recovery="<<a.recovery<<'\n';return s.verdict=="ANALYTIC_CENTER_V3_BOOST_EXECUTION_INVALID"?1:0;}
