// FTD-0646: long-horizon low-momentum transport discriminator.

#define FTD_0644_EMBEDDED
#include "test_analytic_center_collective_boost_ladder_v2.cpp"
#undef FTD_0644_EMBEDDED

namespace {
constexpr char long_protocol_sha256[]="AFE7AD10F6A3935D882EE327F08FDA721ABF19A223029201EACB24FC98C989AF";
constexpr char long_parent_sha256[]="694D46A2EBA1D5ABC96A6525B253737359BCD43F442277F2231150DBEBE8CFD4";
constexpr int long_ticks=256;

struct LongSpec{std::string label,kind,family;Vec3 direction{};double p=0;int map_count=0;};
struct LongTick{int tick=0,hops=0,multiplicity=0;Vec3 displacement{},momentum{},velocity{};double projected=0,shape=0,strain=0,field_energy=0,drift=0,residual=0,separation=INFINITY,dressing=INFINITY,soft_fraction=0;std::vector<double>q;};
struct LongArm{LongSpec spec;bool initialized=false,forward=false,reverse=false,coherent=false,rest=false,persistent=false,bounded_reversal=false;int total_hops=0,max_multiplicity=0;double min_separation=INFINITY,max_shape=0,max_strain=0,max_drift=0,max_common=0,max_dressing=0,recovery=INFINITY,free_speed=0,mobility=INFINITY,fit_velocity=NAN,fit_r2=NAN,soft_fraction=0;std::array<double,4> checkpoints{},increments{};std::string classification="na";std::vector<LongTick>ticks;};
struct LongSummary{bool parent=false,bases=false,coverage=false,execution=false,coherence=false,rest=false,mirror=false,cubic=false;int persistent_count=0,reversal_count=0;double beta=0,mirror_residual=0,cubic_residual=0,worst_common=0,worst_drift=0,worst_recovery=0,worst_shape=0,worst_strain=0,worst_dressing=0,min_r2=1,min_mobility=INFINITY;std::string verdict="ANALYTIC_CENTER_LONG_HORIZON_EXECUTION_INVALID";std::array<FullModes,3>modes;std::vector<LongArm>arms;};

bool long_parent(){const auto path=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0645/ftd_0645_analytic_center_collective_boost_ladder_v3.json";std::ifstream input(path,std::ios::binary);const std::string bytes((std::istreambuf_iterator<char>(input)),{});return bytes.find(long_parent_sha256)!=std::string::npos||bytes.find("ANALYTIC_CENTER_V3_COHERENT_NO_THRESHOLD_AT_LADDER_RESOLUTION")!=std::string::npos;}
void long_fit(LongArm&a){long double mt=0,my=0;int n=0;for(const auto&r:a.ticks)if(r.tick>=65){mt+=r.tick;my+=r.projected;++n;}mt/=n;my/=n;long double covariance=0,variance=0,total=0,residual=0;for(const auto&r:a.ticks)if(r.tick>=65){const long double dt=r.tick-mt,dy=r.projected-my;covariance+=dt*dy;variance+=dt*dt;total+=dy*dy;}a.fit_velocity=static_cast<double>(covariance/variance);const long double intercept=my-a.fit_velocity*mt;for(const auto&r:a.ticks)if(r.tick>=65){const long double e=r.projected-(intercept+a.fit_velocity*r.tick);residual+=e*e;}a.fit_r2=total>0?static_cast<double>(1-residual/total):1;for(int i=0;i<4;++i)a.checkpoints[i]=a.ticks[64*(i+1)-1].projected;a.increments[0]=a.checkpoints[0];for(int i=1;i<4;++i)a.increments[i]=a.checkpoints[i]-a.checkpoints[i-1];a.mobility=a.free_speed>0?a.checkpoints[3]/(long_ticks*a.free_speed):0;const double block_free=64*a.free_speed;a.persistent=std::all_of(a.increments.begin(),a.increments.end(),[&](double d){return d>=.25*block_free;})&&a.fit_velocity>=.5*a.free_speed&&a.fit_r2>=.98&&a.mobility>=.5&&a.increments[3]>0;const double prior=std::max({a.checkpoints[0],a.checkpoints[1],a.checkpoints[2]});a.bounded_reversal=std::any_of(a.increments.begin(),a.increments.end(),[&](double d){return d<-.01*block_free;})&&std::abs(a.checkpoints[3])<std::abs(prior);a.classification=a.persistent?"persistent":(a.bounded_reversal?"bounded_reversal":"mixed");}

LongArm run_long(const LongSpec&spec,const FullModes&modes,double beta,const ftd::eft::ConnectedMooreBlockOptions&options){LongArm a;a.spec=spec;BoostSpec seed{spec.label,spec.kind,spec.family,spec.direction,spec.p,spec.map_count};const auto reference=spec.kind=="cyclic"?rotated_boost_reference(spec.map_count):load_refined_state(0);if(reference.electric.L!=L)return a;auto initial=reference;for(auto&p:initial.constituents)p.momentum=spec.direction*spec.p;a.initialized=initial.constituents.size()==count;auto state=initial;const double e0=mode_energy(initial,beta,options);const Vec3 c0=center(initial);a.free_speed=ftd::eft::production_flat_velocity_from_momentum(spec.direction*spec.p).mag();a.forward=a.initialized;ftd::eft::ConnectedMooreBlockSolveCache forward_cache,reverse_cache;
  for(int tick=1;a.forward&&tick<=long_ticks;++tick){const auto step=ftd::eft::solve_connected_moore_block_forward(state,options,&forward_cache);const double residual=common_residual(step);if(!step.valid||!step.common_action_gates_pass||residual>1e-10){a.forward=false;break;}state=step.later;LongTick row;row.tick=tick;row.hops=step.site_hops;row.displacement=center(state)-c0;row.projected=row.displacement.dot(spec.direction);row.momentum=boost_momentum(state);row.velocity=boost_velocity(state);row.shape=boost_shape(initial,state);row.strain=step.maximum_edge_strain;row.field_energy=beta*ftd::eft::matched_modified_energy(state.electric,state.magnetic_half,ftd::C_SPEED);row.drift=std::abs(mode_energy(state,beta,options)-e0);row.residual=residual;std::tie(row.multiplicity,row.separation)=mode_fibre(state);row.dressing=boost_dressing(state);row.q=project_modes(reference,state,modes);long double soft=0,total=0;for(int i=0;i<N;++i){const long double v=static_cast<long double>(row.q[i])*row.q[i];total+=v;if(i<6)soft+=v;}row.soft_fraction=total>0?static_cast<double>(soft/total):1;a.total_hops+=row.hops;a.max_multiplicity=std::max(a.max_multiplicity,row.multiplicity);if(std::isfinite(row.separation))a.min_separation=std::min(a.min_separation,row.separation);a.max_shape=std::max(a.max_shape,row.shape);a.max_strain=std::max(a.max_strain,row.strain);a.max_drift=std::max(a.max_drift,row.drift);a.max_common=std::max(a.max_common,row.residual);a.max_dressing=std::max(a.max_dressing,row.dressing);a.ticks.push_back(std::move(row));}
  a.forward=a.forward&&a.ticks.size()==long_ticks;a.reverse=a.forward;for(int tick=long_ticks;a.reverse&&tick>=1;--tick){const auto step=ftd::eft::solve_connected_moore_block_reverse(state,options,&reverse_cache);a.max_common=std::max(a.max_common,common_residual(step));if(!step.valid||!step.common_action_gates_pass||common_residual(step)>1e-10){a.reverse=false;break;}state=step.earlier;}if(a.reverse)a.recovery=ftd::eft::connected_moore_block_state_max_difference(initial,state);long double soft=0,total=0;for(const auto&t:a.ticks)for(int i=0;i<N;++i){const long double v=static_cast<long double>(t.q[i])*t.q[i];total+=v;if(i<6)soft+=v;}a.soft_fraction=total>0?static_cast<double>(soft/total):1;a.coherent=a.initialized&&a.forward&&a.reverse&&a.max_multiplicity<=8&&(!std::isfinite(a.min_separation)||a.min_separation>=.9)&&a.max_shape<=.05&&a.max_strain<=.05&&a.max_drift<=1e-9&&a.max_common<=1e-10&&a.recovery<=1e-8&&(spec.p==0||(a.soft_fraction>=.95&&a.max_dressing<=.50));if(spec.p==0)a.rest=a.coherent&&a.ticks.back().displacement.mag()<=1e-9&&a.ticks.back().velocity.mag()<=1e-9&&a.total_hops==0;else if(a.forward)long_fit(a);return a;}

std::vector<LongSpec>long_specs(){const double r2=1/std::sqrt(2.0),r3=1/std::sqrt(3.0);const std::vector<std::pair<std::string,Vec3>>families{{"100",{1,0,0}},{"110",{r2,r2,0}},{"111",{r3,r3,r3}}};const std::array<double,4>ladder{{.001875,.00375,.0075,.015}};std::vector<LongSpec>s{{"rest","rest","rest",{},0,0}};for(const auto&f:families){for(double p:ladder)s.push_back({f.first+"_p"+std::to_string(p),"ladder",f.first,f.second,p,0});for(double p:{.001875,.0075})s.push_back({f.first+"_n"+std::to_string(p),"mirror",f.first,f.second*(-1),p,0});}s.push_back({"100_y","cyclic","100",{0,1,0},.0075,1});s.push_back({"100_z","cyclic","100",{0,0,1},.0075,2});s.push_back({"110_yz","cyclic","110",{0,r2,r2},.0075,1});s.push_back({"110_xz","cyclic","110",{r2,0,r2},.0075,2});return s;}
const LongArm*long_find(const LongSummary&s,const std::string&family,const std::string&kind,double p,int map=0){for(const auto&a:s.arms)if(a.spec.family==family&&a.spec.kind==kind&&std::abs(a.spec.p-p)<1e-15&&a.spec.map_count==map)return&a;return nullptr;}
void evaluate_long(LongSummary&s){s.coverage=s.arms.size()==23;s.execution=s.coverage&&std::all_of(s.arms.begin(),s.arms.end(),[](const LongArm&a){return a.initialized&&a.forward&&a.reverse&&std::isfinite(a.recovery);});s.coherence=s.execution&&std::all_of(s.arms.begin(),s.arms.end(),[](const LongArm&a){return a.coherent;});const auto*r=long_find(s,"rest","rest",0);s.rest=r&&r->rest;s.persistent_count=s.reversal_count=0;for(const auto&a:s.arms)if(a.spec.kind=="ladder"){s.persistent_count+=a.persistent;s.reversal_count+=a.bounded_reversal;s.min_r2=std::min(s.min_r2,a.fit_r2);s.min_mobility=std::min(s.min_mobility,a.mobility);}
  s.mirror=s.coherence;s.mirror_residual=0;for(const std::string family:{"100","110","111"})for(double p:{.001875,.0075}){const auto*a=long_find(s,family,"ladder",p),*n=long_find(s,family,"mirror",p);if(!a||!n){s.mirror=false;continue;}for(int i=0;i<4;++i)s.mirror_residual=std::max(s.mirror_residual,std::abs(a->checkpoints[i]-n->checkpoints[i]));s.mirror_residual=std::max({s.mirror_residual,std::abs(a->fit_velocity-n->fit_velocity),std::abs(a->max_shape-n->max_shape),std::abs(a->ticks.back().field_energy-n->ticks.back().field_energy),std::abs(a->max_dressing-n->max_dressing),std::abs(a->soft_fraction-n->soft_fraction),std::abs(a->recovery-n->recovery)});s.mirror=s.mirror&&a->total_hops==n->total_hops&&s.mirror_residual<=1e-6;}
  s.cubic=s.coherence;s.cubic_residual=0;for(const auto&a:s.arms)if(a.spec.kind=="cyclic"){const auto*c=long_find(s,a.spec.family,"ladder",.0075);if(!c){s.cubic=false;continue;}for(int i=0;i<4;++i)s.cubic_residual=std::max(s.cubic_residual,std::abs(a.checkpoints[i]-c->checkpoints[i]));s.cubic_residual=std::max({s.cubic_residual,std::abs(a.fit_velocity-c->fit_velocity),std::abs(a.max_shape-c->max_shape),std::abs(a.ticks.back().field_energy-c->ticks.back().field_energy),std::abs(a.max_dressing-c->max_dressing),std::abs(a.soft_fraction-c->soft_fraction),std::abs(a.recovery-c->recovery)});s.cubic=s.cubic&&a.total_hops==c->total_hops&&s.cubic_residual<=1e-6;}
  for(const auto&a:s.arms){s.worst_common=std::max(s.worst_common,a.max_common);s.worst_drift=std::max(s.worst_drift,a.max_drift);if(std::isfinite(a.recovery))s.worst_recovery=std::max(s.worst_recovery,a.recovery);s.worst_shape=std::max(s.worst_shape,a.max_shape);s.worst_strain=std::max(s.worst_strain,a.max_strain);s.worst_dressing=std::max(s.worst_dressing,a.max_dressing);}if(!s.parent||!s.bases||!s.coverage||!s.execution||!s.rest)s.verdict="ANALYTIC_CENTER_LONG_HORIZON_EXECUTION_INVALID";else if(!s.coherence||!s.mirror||!s.cubic)s.verdict="ANALYTIC_CENTER_LONG_HORIZON_COHERENCE_CLOSED";else if(s.persistent_count==12)s.verdict="ANALYTIC_CENTER_LONG_HORIZON_TRANSPORT_CONSTRUCTIVE";else if(s.reversal_count==12)s.verdict="ANALYTIC_CENTER_LONG_HORIZON_BOUNDED_OSCILLATION";else s.verdict="ANALYTIC_CENTER_LONG_HORIZON_MIXED";}

void write_long(const LongSummary&s){const auto dir=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0646";std::filesystem::create_directories(dir);std::ofstream json(dir/"ftd_0646_analytic_center_long_horizon_transport_v1.json");json<<std::setprecision(17)<<"{\n  \"ftd_id\": \"FTD-0646\",\n  \"protocol_sha256\": \""<<long_protocol_sha256<<"\",\n  \"parent_result_sha256\": \""<<long_parent_sha256<<"\",\n  \"verdict\": \""<<s.verdict<<"\",\n  \"production_changed\": false,\n  \"arm_count\": "<<s.arms.size()<<",\n  \"ticks_each_direction\": "<<long_ticks<<",\n  \"coverage_pass\": "<<s.coverage<<",\n  \"execution_pass\": "<<s.execution<<",\n  \"coherence_pass\": "<<s.coherence<<",\n  \"rest_pass\": "<<s.rest<<",\n  \"mirror_pass\": "<<s.mirror<<",\n  \"cubic_pass\": "<<s.cubic<<",\n  \"persistent_count\": "<<s.persistent_count<<",\n  \"bounded_reversal_count\": "<<s.reversal_count<<",\n  \"minimum_fit_r2\": "<<s.min_r2<<",\n  \"minimum_mobility\": "<<s.min_mobility<<",\n  \"mirror_residual\": "<<s.mirror_residual<<",\n  \"cubic_residual\": "<<s.cubic_residual<<",\n  \"worst_common_residual\": "<<s.worst_common<<",\n  \"worst_energy_drift\": "<<s.worst_drift<<",\n  \"worst_recovery\": "<<s.worst_recovery<<",\n  \"worst_shape\": "<<s.worst_shape<<",\n  \"worst_strain\": "<<s.worst_strain<<",\n  \"worst_dressing\": "<<s.worst_dressing<<"\n}\n";
  std::ofstream arms(dir/"ftd_0646_analytic_center_long_horizon_transport_arms_v1.csv");arms<<"ftd_id,label,kind,family,p,dir_x,dir_y,dir_z,map_count,initialized,forward,reverse,coherent,rest,classification,persistent,bounded_reversal,total_hops,free_speed,mobility,fit_velocity,fit_r2,checkpoint64,checkpoint128,checkpoint192,checkpoint256,increment1,increment2,increment3,increment4,soft_fraction,max_dressing,max_shape,max_strain,max_drift,max_common,recovery,max_multiplicity,min_separation\n";for(const auto&a:s.arms){arms<<std::setprecision(17)<<"FTD-0646,"<<a.spec.label<<','<<a.spec.kind<<','<<a.spec.family<<','<<a.spec.p<<','<<a.spec.direction.x<<','<<a.spec.direction.y<<','<<a.spec.direction.z<<','<<a.spec.map_count<<','<<a.initialized<<','<<a.forward<<','<<a.reverse<<','<<a.coherent<<','<<a.rest<<','<<a.classification<<','<<a.persistent<<','<<a.bounded_reversal<<','<<a.total_hops<<','<<a.free_speed<<','<<a.mobility<<','<<a.fit_velocity<<','<<a.fit_r2;for(double x:a.checkpoints)arms<<','<<x;for(double x:a.increments)arms<<','<<x;arms<<','<<a.soft_fraction<<','<<a.max_dressing<<','<<a.max_shape<<','<<a.max_strain<<','<<a.max_drift<<','<<a.max_common<<','<<a.recovery<<','<<a.max_multiplicity<<','<<a.min_separation<<'\n';}
  std::ofstream ticks(dir/"ftd_0646_analytic_center_long_horizon_transport_ticks_v1.csv");ticks<<"ftd_id,label,tick,hops,disp_x,disp_y,disp_z,projected,momentum_x,momentum_y,momentum_z,velocity_x,velocity_y,velocity_z,shape,strain,field_energy,drift,residual,multiplicity,separation,dressing,soft_fraction";for(int i=0;i<N;++i)ticks<<",q"<<i;ticks<<'\n';for(const auto&a:s.arms)for(const auto&t:a.ticks){ticks<<std::setprecision(17)<<"FTD-0646,"<<a.spec.label<<','<<t.tick<<','<<t.hops<<','<<t.displacement.x<<','<<t.displacement.y<<','<<t.displacement.z<<','<<t.projected<<','<<t.momentum.x<<','<<t.momentum.y<<','<<t.momentum.z<<','<<t.velocity.x<<','<<t.velocity.y<<','<<t.velocity.z<<','<<t.shape<<','<<t.strain<<','<<t.field_energy<<','<<t.drift<<','<<t.residual<<','<<t.multiplicity<<','<<t.separation<<','<<t.dressing<<','<<t.soft_fraction;for(double q:t.q)ticks<<','<<q;ticks<<'\n';}}
}

int main(){LongSummary s;s.parent=long_parent();const auto normalization=ftd::eft::measure_face_flux_normalization();s.beta=normalization.mapped_field_work_coefficient;ftd::eft::ConnectedMooreBlockOptions options;options.allow_shared_anchor_chart=true;if(s.parent&&normalization.valid){for(int maps=0;maps<3;++maps){const auto r=rotated_boost_reference(maps);const auto ar=analytic_at("long",0,r,s.beta,options);if(ar.valid)s.modes[maps]=full_modes(ar.hessian);}s.bases=std::all_of(s.modes.begin(),s.modes.end(),[](const FullModes&m){return m.valid;});}if(s.bases){const auto specs=long_specs();constexpr std::size_t batch=6;for(std::size_t start=0;start<specs.size();start+=batch){std::vector<std::future<LongArm>>futures;const auto end=std::min(specs.size(),start+batch);for(std::size_t i=start;i<end;++i)futures.push_back(std::async(std::launch::async,[&,spec=specs[i]](){return run_long(spec,s.modes[spec.kind=="cyclic"?spec.map_count:0],s.beta,options);}));for(std::size_t i=start;i<end;++i){s.arms.push_back(futures[i-start].get());std::cout<<"completed "<<specs[i].label<<std::endl;}}}evaluate_long(s);write_long(s);std::cout<<std::setprecision(17)<<"protocol_sha256="<<long_protocol_sha256<<'\n'<<"verdict="<<s.verdict<<'\n'<<"coverage="<<s.coverage<<" execution="<<s.execution<<" coherence="<<s.coherence<<" rest="<<s.rest<<" mirror="<<s.mirror<<" cubic="<<s.cubic<<" persistent="<<s.persistent_count<<" reversal="<<s.reversal_count<<'\n';for(const auto&a:s.arms)std::cout<<a.spec.label<<" coherent="<<a.coherent<<" class="<<a.classification<<" D="<<a.checkpoints[3]<<" mu="<<a.mobility<<" vfit="<<a.fit_velocity<<" r2="<<a.fit_r2<<" soft="<<a.soft_fraction<<" dressing="<<a.max_dressing<<" recovery="<<a.recovery<<'\n';return s.verdict=="ANALYTIC_CENTER_LONG_HORIZON_EXECUTION_INVALID"?1:0;}

