// FTD-0699: corrected discrete-phase classifier at a fresh amplitude.
#define FTD_SEPARATION_PROTOCOL_SHA256 \
  "C1609A6060C5148A0D5B4B6334B862E2212C2C55B22579A25BC34858F7610858"
#define FTD_SEPARATION_IDENTIFIER "FTD-0699"
#define FTD_SEPARATION_RESULT_DIRECTORY "results/ftd_0699"
#define FTD_SEPARATION_RESULT_STEM \
  "ftd_0699_internal_excitation_symmetry_ray_parent_v2"
#define FTD_SEPARATION_CENTER_TOLERANCE 1e-12
#define FTD_SEPARATION_USE_BATCHED_REGIONAL 1
#define FTD_SEPARATION_USE_LOCAL_RESIDUAL 1
#define FTD_SEPARATION_VOLUME 113
#define FTD_SEPARATION_HORIZON 96
#define FTD_SEPARATION_LATE_START 80
#define FTD_SEPARATION_LATE_END 96
#define FTD_SEPARATION_PROGRESS_INTERVAL 1
#define FTD_SEPARATION_OBSERVATION_CADENCE 4
#define FTD_SEPARATION_MOMENTUM 5.0e-8
#define FTD_SEPARATION_EXTRA_HEADER \
  "internal_excitation_symmetry_ray_spectrum_hook_v2.h"
#define FTD_SEPARATION_EXTRA_OBSERVE(...) ftd0699::observe(__VA_ARGS__)
#define FTD_SEPARATION_EXTRA_FINALIZE(...) ftd0699::finalize(__VA_ARGS__)
#define FTD_SEPARATION_EXTRA_EXECUTION_VALID ftd0699::execution_valid()
#include "test_causal_excitation_separation_v1.cpp"
