// FTD-0630: three-axis translation curvature and fully-half control.

#include "ftd/eft/connected_moore_block_action.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <future>
#include <iomanip>
#include <iostream>
#include <map>
#include <string>
#include <tuple>
#include <vector>

namespace {

using ftd::Vec3;using Theta=std::array<double,4>;
constexpr char protocol_sha256[]="4BF3F43F841ABC653611E40FA74B6BF0AB7FEEE14C5F226062D456B34DB76586";
constexpr char parent_result_sha256[]="6343684A3427AC5CEA57EFA22C591A4702E1B2D78B82F0461A5F372AE23E91C8";
constexpr char parent_protocol_sha256[]="BF823BB629BFAB7FA385E39AB83E4BDCC2DCA3E857EE424FAF65C3280898CB4F";
constexpr int L=17,width=2;constexpr double h=2e-4;
constexpr Theta theta0{{1.4993153663084844,0.4994670538459639,0.50006590532229034,0.50018096647517352}};

struct Evaluation{bool valid=false;double energy=INFINITY,gauss=INFINITY;int multiplicity=0,pairs=0;double separation=INFINITY;};
struct Curvature{std::string state;int axis=0;double minus=INFINITY,center=INFINITY,plus=INFINITY,gradient=INFINITY,curvature=INFINITY;};
struct Arm{std::string label;int orientation=0;bool valid=false;int evaluations=0;double body_energy=INFINITY,full_energy=INFINITY,max_gauss=0;int max_multiplicity=1;double min_separation=INFINITY;std::vector<Curvature> curves;};
struct Summary{bool parent=false,normalization=false,coverage=false,execution=false,body_saddle=false,body_stable=false,full_basin=false,covariance=false;double beta=0,covariance_residual=INFINITY,max_gauss=0,min_separation=INFINITY;int max_multiplicity=1;std::string verdict;std::vector<Arm> arms;};

double component(const Vec3&v,int a){return a==0?v.x:(a==1?v.y:v.z);}void set_component(Vec3&v,int a,double x){if(a==0)v.x=x;else if(a==1)v.y=x;else v.z=x;}
Vec3 position(const ftd::eft::MatchedMatterPoint&p){return {p.anchor.x+p.remainder.x,p.anchor.y+p.remainder.y,p.anchor.z+p.remainder.z};}
Vec3 center(const ftd::eft::ConnectedMooreBlockState&s){Vec3 c{};for(const auto&p:s.constituents)c+=position(p);return c*(1.0/s.constituents.size());}
int wrap(int x){const int r=x%L;return r<0?r+L:r;}ftd::eft::MatchedMatterPoint point_at(const Vec3&x){ftd::eft::MatchedMatterPoint p;const long long ax=std::llround(x.x),ay=std::llround(x.y),az=std::llround(x.z);p.anchor={wrap(static_cast<int>(ax)),wrap(static_cast<int>(ay)),wrap(static_cast<int>(az))};p.remainder={x.x-ax,x.y-ay,x.z-az};return p;}
ftd::eft::ConnectedMooreBlockState geometry_from(const ftd::eft::ConnectedMooreBlockState&base,const Theta&t,int axis){auto r=base;const Vec3 c=center(base);for(std::size_t i=0;i<r.constituents.size();++i){const Vec3 d0=position(base.constituents[i])-c;const bool outer=std::abs(component(d0,axis))>1;Vec3 d{};set_component(d,axis,std::copysign(outer?t[0]:t[1],component(d0,axis)));const double q=outer?t[2]:t[3];for(int k=0;k<3;++k)if(k!=axis)set_component(d,k,std::copysign(q,component(d0,k)));r.constituents[i]=point_at(c+d);}return r;}
ftd::eft::ConnectedMooreBlockState translate(const ftd::eft::ConnectedMooreBlockState&s,const Vec3&d){auto r=s;for(auto&p:r.constituents)p=point_at(position(p)+d);return r;}
std::tuple<int,int,double> fibre(const ftd::eft::ConnectedMooreBlockState&s){std::map<std::tuple<int,int,int>,std::vector<std::size_t>>g;for(std::size_t i=0;i<s.constituents.size();++i){const auto&a=s.constituents[i].anchor;g[{a.x,a.y,a.z}].push_back(i);}int maximum=1,pairs=0;double separation=INFINITY;for(const auto&x:g){maximum=std::max(maximum,static_cast<int>(x.second.size()));for(std::size_t i=0;i<x.second.size();++i)for(std::size_t j=i+1;j<x.second.size();++j){++pairs;separation=std::min(separation,(position(s.constituents[x.second[i]])-position(s.constituents[x.second[j]])).mag());}}return {maximum,pairs,separation};}
Evaluation evaluate(const ftd::eft::ConnectedMooreBlockState&geometry,double beta,const ftd::eft::ConnectedMooreBlockOptions&options,int&count){Evaluation e;++count;const auto d=ftd::eft::redress_connected_moore_block(geometry,true);if(!d.valid)return e;e.valid=true;e.gauss=d.gauss_residual;e.energy=ftd::eft::connected_moore_block_binding_energy(d.state,options)+beta*ftd::eft::matched_modified_energy(d.state.electric,d.state.magnetic_half,ftd::C_SPEED);std::tie(e.multiplicity,e.pairs,e.separation)=fibre(d.state);return e;}
void accumulate(Arm&a,const Evaluation&e){a.valid=a.valid&&e.valid;a.max_gauss=std::max(a.max_gauss,e.gauss);a.max_multiplicity=std::max(a.max_multiplicity,e.multiplicity);if(std::isfinite(e.separation))a.min_separation=std::min(a.min_separation,e.separation);}
Arm run(std::string label,int orientation,double beta,const ftd::eft::ConnectedMooreBlockOptions&options){Arm a;a.label=std::move(label);a.orientation=orientation;a.valid=true;const auto parent=ftd::eft::initialize_connected_moore_block(L,width,orientation,orientation,.5);if(!parent.valid){a.valid=false;return a;}const auto body=geometry_from(parent.state,theta0,orientation);Vec3 transverse{};for(int axis=0;axis<3;++axis)if(axis!=orientation)set_component(transverse,axis,.5);const auto full=translate(body,transverse);
  for(const auto&entry:std::array<std::pair<std::string,ftd::eft::ConnectedMooreBlockState>,2>{{{"body_half",body},{"full_half",full}}}){const auto e0=evaluate(entry.second,beta,options,a.evaluations);accumulate(a,e0);if(entry.first=="body_half")a.body_energy=e0.energy;else a.full_energy=e0.energy;for(int axis=0;axis<3;++axis){Vec3 delta{};set_component(delta,axis,h);const auto ep=evaluate(translate(entry.second,delta),beta,options,a.evaluations);const auto em=evaluate(translate(entry.second,delta*(-1)),beta,options,a.evaluations);accumulate(a,ep);accumulate(a,em);Curvature c;c.state=entry.first;c.axis=axis;c.minus=em.energy;c.center=e0.energy;c.plus=ep.energy;c.gradient=(ep.energy-em.energy)/(2*h);c.curvature=(ep.energy-2*e0.energy+em.energy)/(h*h);a.curves.push_back(c);}}
  a.valid=a.valid&&a.evaluations==14&&a.max_gauss<=1e-11&&a.max_multiplicity<=2&&(!std::isfinite(a.min_separation)||a.min_separation>=.9);return a;}
const Curvature* find(const Arm&a,const std::string&state,int axis){for(const auto&c:a.curves)if(c.state==state&&c.axis==axis)return &c;return nullptr;}
double relative(double a,double b){return std::abs(a-b)/std::max({1.0,std::abs(a),std::abs(b)});}int cycle_axis(int axis){return axis==0?1:(axis==1?2:0);}
void evaluate_summary(Summary&s){s.coverage=s.arms.size()==2&&s.arms[0].orientation==0&&s.arms[1].orientation==1;s.execution=s.coverage&&std::all_of(s.arms.begin(),s.arms.end(),[](const Arm&a){return a.valid;});s.body_saddle=s.body_stable=s.full_basin=s.execution;for(const auto&a:s.arms){for(int axis=0;axis<3;++axis){const auto*b=find(a,"body_half",axis),*f=find(a,"full_half",axis);if(!b||!f){s.body_saddle=s.body_stable=s.full_basin=false;continue;}const bool body_axis=axis==a.orientation;s.body_saddle=s.body_saddle&&std::abs(b->gradient)<=1e-8&&(body_axis?b->curvature>1e-6:b->curvature<-1e-6);s.body_stable=s.body_stable&&std::abs(b->gradient)<=1e-8&&b->curvature>1e-6;s.full_basin=s.full_basin&&std::abs(f->gradient)<=1e-8&&f->curvature>1e-6;}s.full_basin=s.full_basin&&a.full_energy<a.body_energy;s.max_gauss=std::max(s.max_gauss,a.max_gauss);s.max_multiplicity=std::max(s.max_multiplicity,a.max_multiplicity);if(std::isfinite(a.min_separation))s.min_separation=std::min(s.min_separation,a.min_separation);}
  if(s.coverage){s.covariance_residual=0;const auto&x=s.arms[0];const auto&y=s.arms[1];for(const auto&c:x.curves){const auto*d=find(y,c.state,cycle_axis(c.axis));if(!d){s.covariance_residual=INFINITY;break;}s.covariance_residual=std::max({s.covariance_residual,relative(c.gradient,d->gradient),relative(c.curvature,d->curvature),relative(c.center,d->center)});}s.covariance=s.covariance_residual<=1e-8;}
  if(!s.parent||!s.normalization||!s.coverage||!s.execution||!s.covariance)s.verdict="CONNECTED_BLOCK_TRANSLATION_CURVATURE_EXECUTION_INVALID";else if(s.body_saddle&&s.full_basin)s.verdict="BODY_HALF_TRANSLATION_SADDLE_FULL_HALF_BASIN_CONSTRUCTIVE";else if(s.body_stable)s.verdict="BODY_HALF_FULL_TRANSLATION_STABLE";else if(s.body_saddle)s.verdict="FULL_HALF_TRANSLATION_REPAIR_CLOSED_NEGATIVE";else s.verdict="CONNECTED_BLOCK_TRANSLATION_CURVATURE_INCONCLUSIVE";}
bool parent(){const auto path=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0629/ftd_0629_connected_block_linear_modes_v1.json";std::ifstream in(path,std::ios::binary);const std::string bytes((std::istreambuf_iterator<char>(in)),{});return bytes.find(parent_protocol_sha256)!=std::string::npos&&bytes.find("CONNECTED_BLOCK_ADIABATIC_LINEAR_MODES_CONSTRUCTIVE")!=std::string::npos;}
void number(std::ostream&o,double x){if(std::isfinite(x))o<<x;else o<<"null";}void write(const Summary&s){const auto dir=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0630";std::filesystem::create_directories(dir);std::ofstream json(dir/"ftd_0630_connected_block_translation_curvature_v1.json");json<<std::setprecision(17)<<"{\n  \"ftd_id\": \"FTD-0630\",\n  \"protocol_sha256\": \""<<protocol_sha256<<"\",\n  \"parent_result_sha256\": \""<<parent_result_sha256<<"\",\n  \"verdict\": \""<<s.verdict<<"\",\n  \"production_changed\": false,\n  \"coverage_pass\": "<<s.coverage<<",\n  \"execution_pass\": "<<s.execution<<",\n  \"body_saddle_pass\": "<<s.body_saddle<<",\n  \"body_stable_pass\": "<<s.body_stable<<",\n  \"full_half_basin_pass\": "<<s.full_basin<<",\n  \"covariance_pass\": "<<s.covariance<<",\n  \"covariance_residual\": ";number(json,s.covariance_residual);json<<",\n  \"max_gauss_residual\": "<<s.max_gauss<<",\n  \"max_multiplicity\": "<<s.max_multiplicity<<",\n  \"min_separation\": ";number(json,s.min_separation);json<<"\n}\n";std::ofstream arms(dir/"ftd_0630_connected_block_translation_states_v1.csv");arms<<"ftd_id,label,orientation,valid,evaluations,body_energy,full_energy,max_gauss,max_multiplicity,min_separation\n";for(const auto&a:s.arms)arms<<std::setprecision(17)<<"FTD-0630,"<<a.label<<','<<a.orientation<<','<<a.valid<<','<<a.evaluations<<','<<a.body_energy<<','<<a.full_energy<<','<<a.max_gauss<<','<<a.max_multiplicity<<','<<a.min_separation<<'\n';std::ofstream curves(dir/"ftd_0630_connected_block_translation_curvatures_v1.csv");curves<<"ftd_id,label,orientation,state,axis,minus,center,plus,gradient,curvature\n";for(const auto&a:s.arms)for(const auto&c:a.curves)curves<<std::setprecision(17)<<"FTD-0630,"<<a.label<<','<<a.orientation<<','<<c.state<<','<<c.axis<<','<<c.minus<<','<<c.center<<','<<c.plus<<','<<c.gradient<<','<<c.curvature<<'\n';}
}
int main(){std::cout<<std::setprecision(17);Summary s;s.parent=parent();const auto n=ftd::eft::measure_face_flux_normalization();s.normalization=n.valid;s.beta=n.mapped_field_work_coefficient;ftd::eft::ConnectedMooreBlockOptions options;options.allow_shared_anchor_chart=true;if(s.parent&&s.normalization){auto x=std::async(std::launch::async,[&](){return run("translation_x",0,s.beta,options);});auto y=std::async(std::launch::async,[&](){return run("translation_y",1,s.beta,options);});s.arms.push_back(x.get());s.arms.push_back(y.get());}evaluate_summary(s);write(s);std::cout<<"protocol_sha256="<<protocol_sha256<<'\n'<<"verdict="<<s.verdict<<'\n'<<"body_saddle="<<s.body_saddle<<" full_basin="<<s.full_basin<<" covariance="<<s.covariance_residual<<'\n';for(const auto&a:s.arms){std::cout<<a.label<<" body="<<a.body_energy<<" full="<<a.full_energy<<'\n';for(const auto&c:a.curves)std::cout<<"  "<<c.state<<" axis="<<c.axis<<" gradient="<<c.gradient<<" curvature="<<c.curvature<<'\n';}return s.verdict=="CONNECTED_BLOCK_TRANSLATION_CURVATURE_EXECUTION_INVALID"?1:0;}
