// FTD-0644: corrected finite collective boost ladder.

#define FTD_0643_EMBEDDED
#include "test_analytic_center_collective_boost_ladder.cpp"
#undef FTD_0643_EMBEDDED

namespace {
constexpr char boost_v2_protocol_sha256[]="24464297DBB82B8D14E143CADB593D49EA07DFDC42648D57350CEF66971B1DD3";

ftd::eft::ConnectedMooreBlockState rotated_boost_reference(int maps){auto reference=load_refined_state(0);if(maps==0)return reference;auto geometry=reference;for(auto&p:geometry.constituents){Vec3 x=position(p);for(int i=0;i<maps;++i)x={x.z,x.x,x.y};p=point_at(x);p.momentum={};}const auto dressed=ftd::eft::redress_connected_moore_block_with_fibre_limit(geometry,8,1e-13,4096);return dressed.valid?dressed.state:ftd::eft::ConnectedMooreBlockState{};}

BoostArm run_boost_v2(const BoostSpec&spec,const FullModes&modes,double beta,const ftd::eft::ConnectedMooreBlockOptions&options){if(spec.kind!="cyclic")return run_boost(spec,modes,beta,options);BoostArm arm;arm.spec=spec;const auto reference=rotated_boost_reference(spec.map_count);if(reference.electric.L!=L)return arm;auto initial=reference;for(auto&p:initial.constituents)p.momentum=spec.direction*spec.p;arm.initialized=initial.constituents.size()==count;auto state=initial;const double e0=mode_energy(initial,beta,options);const Vec3 c0=center(initial);arm.free_displacement=boost_ticks*ftd::eft::production_flat_velocity_from_momentum(spec.direction*spec.p).mag();arm.forward=arm.initialized;ftd::eft::ConnectedMooreBlockSolveCache forward_cache,reverse_cache;
  for(int tick=1;arm.forward&&tick<=boost_ticks;++tick){const auto step=ftd::eft::solve_connected_moore_block_forward(state,options,&forward_cache);const double residual=common_residual(step);if(!step.valid||!step.common_action_gates_pass||residual>1e-10){arm.forward=false;break;}state=step.later;BoostTick row;row.tick=tick;row.hops=step.site_hops;row.displacement=center(state)-c0;row.momentum=boost_momentum(state);row.velocity=boost_velocity(state);row.shape=boost_shape(initial,state);row.strain=step.maximum_edge_strain;row.field_energy=beta*ftd::eft::matched_modified_energy(state.electric,state.magnetic_half,ftd::C_SPEED);row.drift=std::abs(mode_energy(state,beta,options)-e0);row.residual=residual;std::tie(row.multiplicity,row.separation)=mode_fibre(state);row.dressing=boost_dressing(state);row.q=project_modes(reference,state,modes);long double soft=0,total=0;for(int i=0;i<N;++i){const long double v=static_cast<long double>(row.q[i])*row.q[i];total+=v;if(i<6)soft+=v;}row.soft_fraction=total>0?static_cast<double>(soft/total):1;arm.total_hops+=row.hops;arm.max_multiplicity=std::max(arm.max_multiplicity,row.multiplicity);if(std::isfinite(row.separation))arm.min_separation=std::min(arm.min_separation,row.separation);arm.max_shape=std::max(arm.max_shape,row.shape);arm.max_strain=std::max(arm.max_strain,row.strain);arm.max_drift=std::max(arm.max_drift,row.drift);arm.max_common=std::max(arm.max_common,row.residual);arm.max_dressing=std::max(arm.max_dressing,row.dressing);arm.ticks.push_back(std::move(row));}
  arm.forward=arm.forward&&arm.ticks.size()==boost_ticks;arm.reverse=arm.forward;for(int tick=boost_ticks;arm.reverse&&tick>=1;--tick){const auto step=ftd::eft::solve_connected_moore_block_reverse(state,options,&reverse_cache);arm.max_common=std::max(arm.max_common,common_residual(step));if(!step.valid||!step.common_action_gates_pass||common_residual(step)>1e-10){arm.reverse=false;break;}state=step.earlier;}if(arm.reverse)arm.recovery=ftd::eft::connected_moore_block_state_max_difference(initial,state);arm.displacement=arm.ticks.empty()?Vec3{}:arm.ticks.back().displacement;arm.final_momentum=arm.ticks.empty()?Vec3{}:arm.ticks.back().momentum;arm.projected=arm.displacement.dot(spec.direction);arm.transverse=(arm.displacement-spec.direction*arm.projected).mag();arm.mobility=arm.free_displacement>0?arm.projected/arm.free_displacement:0;arm.final_velocity=arm.ticks.empty()?0:arm.ticks.back().velocity.dot(spec.direction);arm.soft_fraction=boost_soft_fraction(arm.ticks);arm.coherent=arm.initialized&&arm.forward&&arm.reverse&&arm.max_multiplicity<=8&&(!std::isfinite(arm.min_separation)||arm.min_separation>=.9)&&arm.max_shape<=.05&&arm.max_strain<=.05&&arm.max_drift<=1e-10&&arm.max_common<=1e-10&&arm.recovery<=1e-9;return arm;}

void evaluate_boost_v2(BoostSummary&s,bool rotation_preflight){s.coverage=s.arms.size()==32;s.execution=s.coverage&&rotation_preflight&&std::all_of(s.arms.begin(),s.arms.end(),[](const BoostArm&a){return a.initialized&&a.forward&&a.reverse;});s.coherence=s.execution&&std::all_of(s.arms.begin(),s.arms.end(),[](const BoostArm&a){return a.coherent;});const auto*rest=boost_find(s,"rest","rest",0);s.rest=rest&&rest->rest;s.high=s.monotonic=s.coherence;const std::array<double,7> ladder{{.001875,.00375,.0075,.015,.03,.06,.12}};int fi=0;bool all_finite=true,all_mobile=true;for(const std::string family:{"100","110","111"}){double prior=-INFINITY;s.last_pinned[fi]=-1;s.first_mobile[fi]=-1;for(double p:ladder){const auto*a=boost_find(s,family,"ladder",p);if(!a){s.monotonic=false;continue;}s.monotonic=s.monotonic&&a->projected>=-1e-10&&a->projected+1e-6>=prior;prior=a->projected;if(a->onset=="pinned")s.last_pinned[fi]=p;if(a->onset=="mobile"&&s.first_mobile[fi]<0)s.first_mobile[fi]=p;}const auto*h=boost_find(s,family,"ladder",.12);s.high=s.high&&h&&h->high;all_finite=all_finite&&s.last_pinned[fi]>0&&s.first_mobile[fi]>0;all_mobile=all_mobile&&s.last_pinned[fi]<0&&std::all_of(ladder.begin(),ladder.end(),[&](double p){const auto*a=boost_find(s,family,"ladder",p);return a&&a->onset=="mobile";});++fi;}
  s.mirror=s.coherence;s.mirror_residual=0;for(const std::string family:{"100","110","111"})for(double p:{.03,.12}){const auto*a=boost_find(s,family,"ladder",p),*n=boost_find(s,family,"mirror",p);if(!a||!n){s.mirror=false;continue;}for(int t=0;t<boost_ticks;++t){const auto&x=a->ticks[t];const auto&y=n->ticks[t];s.mirror_residual=std::max({s.mirror_residual,boost_max(x.displacement+y.displacement),std::abs(x.shape-y.shape),std::abs(x.field_energy-y.field_energy),std::abs(x.soft_fraction-y.soft_fraction),std::abs(x.dressing-y.dressing)});}s.mirror=s.mirror&&s.mirror_residual<=1e-7;}
  s.cubic=s.coherence;s.cubic_residual=0;for(const auto&a:s.arms)if(a.spec.kind=="cyclic"){const auto*c=boost_find(s,a.spec.family,"ladder",.12);if(!c){s.cubic=false;continue;}for(int t=0;t<boost_ticks;++t){const auto&x=c->ticks[t];const auto&y=a.ticks[t];s.cubic_residual=std::max({s.cubic_residual,boost_max(y.displacement-boost_cycle(x.displacement,a.spec.map_count)),boost_max(y.momentum-boost_cycle(x.momentum,a.spec.map_count)),std::abs(x.shape-y.shape),std::abs(x.field_energy-y.field_energy),std::abs(x.soft_fraction-y.soft_fraction),std::abs(x.dressing-y.dressing)});}s.cubic_residual=std::max(s.cubic_residual,std::abs(a.recovery-c->recovery));s.cubic=s.cubic&&a.total_hops==c->total_hops&&s.cubic_residual<=1e-7;}
  for(const auto&a:s.arms){s.worst_common=std::max(s.worst_common,a.max_common);s.worst_drift=std::max(s.worst_drift,a.max_drift);if(std::isfinite(a.recovery))s.worst_recovery=std::max(s.worst_recovery,a.recovery);s.worst_shape=std::max(s.worst_shape,a.max_shape);s.worst_strain=std::max(s.worst_strain,a.max_strain);s.worst_dressing=std::max(s.worst_dressing,a.max_dressing);}if(!s.parent||!s.eigensystem||!s.coverage||!s.execution||!s.coherence||!s.rest)s.verdict="ANALYTIC_CENTER_V2_BOOST_EXECUTION_INVALID";else if(!s.high||!s.monotonic||!s.mirror||!s.cubic)s.verdict="ANALYTIC_CENTER_V2_DIRECTIONAL_TRANSPORT_CLOSED";else if(all_finite)s.verdict="ANALYTIC_CENTER_V2_COHERENT_FINITE_DEPINNING_CONSTRUCTIVE";else if(all_mobile)s.verdict="ANALYTIC_CENTER_V2_COHERENT_NO_THRESHOLD_AT_LADDER_RESOLUTION";else s.verdict="ANALYTIC_CENTER_V2_COHERENT_MIXED_ONSET";}

void write_boost_v2(const BoostSummary&s,bool rotation_preflight,double rotation_energy,double rotation_spectrum){const auto dir=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0644";std::filesystem::create_directories(dir);std::ofstream json(dir/"ftd_0644_analytic_center_collective_boost_ladder_v2.json");json<<std::setprecision(17)<<"{\n  \"ftd_id\": \"FTD-0644\",\n  \"protocol_sha256\": \""<<boost_v2_protocol_sha256<<"\",\n  \"parent_result_sha256\": \""<<boost_parent_sha256<<"\",\n  \"verdict\": \""<<s.verdict<<"\",\n  \"production_changed\": false,\n  \"arm_count\": "<<s.arms.size()<<",\n  \"ticks_each_direction\": "<<boost_ticks<<",\n  \"rotation_preflight_pass\": "<<rotation_preflight<<",\n  \"rotation_energy_residual\": "<<rotation_energy<<",\n  \"rotation_spectrum_residual\": "<<rotation_spectrum<<",\n  \"coverage_pass\": "<<s.coverage<<",\n  \"execution_pass\": "<<s.execution<<",\n  \"coherence_pass\": "<<s.coherence<<",\n  \"rest_pass\": "<<s.rest<<",\n  \"high_boost_pass\": "<<s.high<<",\n  \"monotonic_pass\": "<<s.monotonic<<",\n  \"mirror_pass\": "<<s.mirror<<",\n  \"cubic_pass\": "<<s.cubic<<",\n  \"last_pinned_100\": "<<s.last_pinned[0]<<",\n  \"last_pinned_110\": "<<s.last_pinned[1]<<",\n  \"last_pinned_111\": "<<s.last_pinned[2]<<",\n  \"first_mobile_100\": "<<s.first_mobile[0]<<",\n  \"first_mobile_110\": "<<s.first_mobile[1]<<",\n  \"first_mobile_111\": "<<s.first_mobile[2]<<",\n  \"mirror_residual\": "<<s.mirror_residual<<",\n  \"cubic_residual\": "<<s.cubic_residual<<",\n  \"worst_common_residual\": "<<s.worst_common<<",\n  \"worst_energy_drift\": "<<s.worst_drift<<",\n  \"worst_recovery\": "<<s.worst_recovery<<",\n  \"worst_shape\": "<<s.worst_shape<<",\n  \"worst_strain\": "<<s.worst_strain<<",\n  \"worst_dressing\": "<<s.worst_dressing<<"\n}\n";
  std::ofstream arms(dir/"ftd_0644_analytic_center_collective_boost_ladder_arms_v2.csv");arms<<"ftd_id,label,kind,family,p,dir_x,dir_y,dir_z,map_count,initialized,forward,reverse,coherent,rest,high,onset,total_hops,free_displacement,projected,transverse,mobility,soft_fraction,max_dressing,max_shape,max_strain,max_drift,max_common,recovery,disp_x,disp_y,disp_z,momentum_x,momentum_y,momentum_z,final_velocity,max_multiplicity,min_separation\n";for(const auto&a:s.arms)arms<<std::setprecision(17)<<"FTD-0644,"<<a.spec.label<<','<<a.spec.kind<<','<<a.spec.family<<','<<a.spec.p<<','<<a.spec.direction.x<<','<<a.spec.direction.y<<','<<a.spec.direction.z<<','<<a.spec.map_count<<','<<a.initialized<<','<<a.forward<<','<<a.reverse<<','<<a.coherent<<','<<a.rest<<','<<a.high<<','<<a.onset<<','<<a.total_hops<<','<<a.free_displacement<<','<<a.projected<<','<<a.transverse<<','<<a.mobility<<','<<a.soft_fraction<<','<<a.max_dressing<<','<<a.max_shape<<','<<a.max_strain<<','<<a.max_drift<<','<<a.max_common<<','<<a.recovery<<','<<a.displacement.x<<','<<a.displacement.y<<','<<a.displacement.z<<','<<a.final_momentum.x<<','<<a.final_momentum.y<<','<<a.final_momentum.z<<','<<a.final_velocity<<','<<a.max_multiplicity<<','<<a.min_separation<<'\n';
  std::ofstream ticks(dir/"ftd_0644_analytic_center_collective_boost_ladder_ticks_v2.csv");ticks<<"ftd_id,label,tick,hops,disp_x,disp_y,disp_z,momentum_x,momentum_y,momentum_z,velocity_x,velocity_y,velocity_z,shape,strain,field_energy,drift,residual,multiplicity,separation,dressing,soft_fraction";for(int i=0;i<N;++i)ticks<<",q"<<i;ticks<<'\n';for(const auto&a:s.arms)for(const auto&t:a.ticks){ticks<<std::setprecision(17)<<"FTD-0644,"<<a.spec.label<<','<<t.tick<<','<<t.hops<<','<<t.displacement.x<<','<<t.displacement.y<<','<<t.displacement.z<<','<<t.momentum.x<<','<<t.momentum.y<<','<<t.momentum.z<<','<<t.velocity.x<<','<<t.velocity.y<<','<<t.velocity.z<<','<<t.shape<<','<<t.strain<<','<<t.field_energy<<','<<t.drift<<','<<t.residual<<','<<t.multiplicity<<','<<t.separation<<','<<t.dressing<<','<<t.soft_fraction;for(double q:t.q)ticks<<','<<q;ticks<<'\n';}}
}

#ifdef FTD_0644_EMBEDDED
int ftd_0644_embedded_main(){
#else
int main(){
#endif
BoostSummary s;s.parent=boost_parent();const auto normalization=ftd::eft::measure_face_flux_normalization();s.beta=normalization.mapped_field_work_coefficient;ftd::eft::ConnectedMooreBlockOptions options;options.allow_shared_anchor_chart=true;double rotation_energy=0,rotation_spectrum=0;bool rotation_preflight=false;if(s.parent&&normalization.valid){const auto base=load_refined_state(0);const auto analytic=analytic_at("boost_v2",0,base,s.beta,options);if(analytic.valid)s.modes=full_modes(analytic.hessian);s.eigensystem=s.modes.valid;rotation_preflight=s.eigensystem;for(int maps:{1,2}){const auto r=rotated_boost_reference(maps);rotation_energy=std::max(rotation_energy,std::abs(mode_energy(r,s.beta,options)-mode_energy(base,s.beta,options)));const auto ar=analytic_at("boost_v2_rot",0,r,s.beta,options);if(!ar.valid){rotation_preflight=false;continue;}const auto mr=full_modes(ar.hessian);if(!mr.valid){rotation_preflight=false;continue;}for(int i=0;i<N;++i)rotation_spectrum=std::max(rotation_spectrum,relative_value(mr.modes[i].hessian_eigen,s.modes.modes[i].hessian_eigen));}rotation_preflight=rotation_preflight&&rotation_energy<=1e-9&&rotation_spectrum<=1e-9;}if(s.eigensystem&&rotation_preflight){const auto specs=boost_specs();constexpr std::size_t batch=8;for(std::size_t start=0;start<specs.size();start+=batch){std::vector<std::future<BoostArm>> futures;const auto end=std::min(specs.size(),start+batch);for(std::size_t i=start;i<end;++i)futures.push_back(std::async(std::launch::async,[&,spec=specs[i]](){return run_boost_v2(spec,s.modes,s.beta,options);}));for(std::size_t i=start;i<end;++i){s.arms.push_back(futures[i-start].get());std::cout<<"completed "<<specs[i].label<<std::endl;}}}evaluate_boost_v2(s,rotation_preflight);write_boost_v2(s,rotation_preflight,rotation_energy,rotation_spectrum);std::cout<<std::setprecision(17)<<"protocol_sha256="<<boost_v2_protocol_sha256<<'\n'<<"verdict="<<s.verdict<<'\n'<<"rotation="<<rotation_preflight<<" energy="<<rotation_energy<<" spectrum="<<rotation_spectrum<<'\n'<<"coverage="<<s.coverage<<" execution="<<s.execution<<" coherence="<<s.coherence<<" rest="<<s.rest<<" high="<<s.high<<" monotonic="<<s.monotonic<<" mirror="<<s.mirror<<" cubic="<<s.cubic<<'\n'<<"pinned="<<s.last_pinned[0]<<','<<s.last_pinned[1]<<','<<s.last_pinned[2]<<" mobile="<<s.first_mobile[0]<<','<<s.first_mobile[1]<<','<<s.first_mobile[2]<<'\n';for(const auto&a:s.arms)std::cout<<a.spec.label<<" coherent="<<a.coherent<<" onset="<<a.onset<<" D="<<a.projected<<" mu="<<a.mobility<<" hops="<<a.total_hops<<" soft="<<a.soft_fraction<<" dressing="<<a.max_dressing<<" recovery="<<a.recovery<<'\n';return s.verdict=="ANALYTIC_CENTER_V2_BOOST_EXECUTION_INVALID"?1:0;}
