// FTD-0632: finite cubic chart-fibre derivation and qualification.

#include "ftd/eft/connected_moore_block_action.h"

#include <algorithm>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <string>
#include <tuple>
#include <vector>

namespace {
using ftd::Vec3;using Theta=std::array<double,4>;
constexpr char protocol_sha256[]="EAB5EA583966BB1FA7C2F8AD7CAFAB66111407F1F6F477F87293F1B7B374C8AD";
constexpr char parent_protocol_sha256[]="ADB2F73EDF9092C8DA0E0446BD26450432698CCA88A2B2CECF204C105FF00EE8";
constexpr int L=17,width=2;constexpr double h=2e-4;
constexpr Theta theta0{{1.4993153663084844,0.4994670538459639,0.50006590532229034,0.50018096647517352}};

struct Record{std::string label;int orientation=0,index=0,i=-1,j=-1,si=0,sj=0,multiplicity=0;double separation=INFINITY,unique_separation=INFINITY,gauss2=INFINITY,gauss4=INFINITY,gauss8=INFINITY;bool positions=false,cap2=false,cap4=false,cap8=false,law=false;};
struct Summary{bool parent=false,coverage=false,positions=false,separation=false,cap8=false,law=false,covariance=false,discriminator=false;int geometries=0,max_multiplicity=0,cap2_failures=0,cap4_failures=0,cap8_failures=0;double minimum_separation=INFINITY,maximum_gauss=0;std::string verdict;std::vector<Record>records;};

double component(const Vec3&v,int a){return a==0?v.x:(a==1?v.y:v.z);}void set_component(Vec3&v,int a,double x){if(a==0)v.x=x;else if(a==1)v.y=x;else v.z=x;}
Vec3 position(const ftd::eft::MatchedMatterPoint&p){return {p.anchor.x+p.remainder.x,p.anchor.y+p.remainder.y,p.anchor.z+p.remainder.z};}
Vec3 center(const ftd::eft::ConnectedMooreBlockState&s){Vec3 c{};for(const auto&p:s.constituents)c+=position(p);return c*(1.0/s.constituents.size());}
int wrap(int x){const int r=x%L;return r<0?r+L:r;}ftd::eft::MatchedMatterPoint point_at(const Vec3&x){ftd::eft::MatchedMatterPoint p;const long long ax=std::llround(x.x),ay=std::llround(x.y),az=std::llround(x.z);p.anchor={wrap(static_cast<int>(ax)),wrap(static_cast<int>(ay)),wrap(static_cast<int>(az))};p.remainder={x.x-ax,x.y-ay,x.z-az};return p;}
ftd::eft::ConnectedMooreBlockState geometry_from(const ftd::eft::ConnectedMooreBlockState&base,const Theta&t,int orientation){auto r=base;const Vec3 c=center(base);Vec3 shift{};for(int axis=0;axis<3;++axis)if(axis!=orientation)set_component(shift,axis,.5);for(std::size_t k=0;k<r.constituents.size();++k){const Vec3 d0=position(base.constituents[k])-c;const bool outer=std::abs(component(d0,orientation))>1;Vec3 d{};set_component(d,orientation,std::copysign(outer?t[0]:t[1],component(d0,orientation)));const double q=outer?t[2]:t[3];for(int axis=0;axis<3;++axis)if(axis!=orientation)set_component(d,axis,std::copysign(q,component(d0,axis)));r.constituents[k]=point_at(c+shift+d);}return r;}
std::tuple<int,double,double,bool> chart(const ftd::eft::ConnectedMooreBlockState&s){std::map<std::tuple<int,int,int>,std::vector<std::size_t>>g;for(std::size_t i=0;i<s.constituents.size();++i){const auto&a=s.constituents[i].anchor;g[{a.x,a.y,a.z}].push_back(i);}int maximum=1;double same=INFINITY,unique=INFINITY;bool finite=true;for(std::size_t i=0;i<s.constituents.size();++i){const Vec3 a=position(s.constituents[i]);finite=finite&&std::isfinite(a.x)&&std::isfinite(a.y)&&std::isfinite(a.z);for(std::size_t j=i+1;j<s.constituents.size();++j)unique=std::min(unique,(a-position(s.constituents[j])).mag());}for(const auto&x:g){maximum=std::max(maximum,static_cast<int>(x.second.size()));for(std::size_t i=0;i<x.second.size();++i)for(std::size_t j=i+1;j<x.second.size();++j)same=std::min(same,(position(s.constituents[x.second[i]])-position(s.constituents[x.second[j]])).mag());}return {maximum,same,unique,finite&&unique>1e-12};}
Record evaluate(std::string label,int orientation,int index,int i,int j,int si,int sj,const ftd::eft::ConnectedMooreBlockState&base){Theta t=theta0;if(i>=0)t[i]+=si*h;if(j>=0)t[j]+=sj*h;const auto geometry=geometry_from(base,t,orientation);Record r;r.label=std::move(label);r.orientation=orientation;r.index=index;r.i=i;r.j=j;r.si=si;r.sj=sj;std::tie(r.multiplicity,r.separation,r.unique_separation,r.positions)=chart(geometry);const auto d2=ftd::eft::redress_connected_moore_block_with_fibre_limit(geometry,2,1e-13,4096),d4=ftd::eft::redress_connected_moore_block_with_fibre_limit(geometry,4,1e-13,4096),d8=ftd::eft::redress_connected_moore_block_with_fibre_limit(geometry,8,1e-13,4096);r.cap2=d2.valid;r.cap4=d4.valid;r.cap8=d8.valid;r.gauss2=d2.gauss_residual;r.gauss4=d4.gauss_residual;r.gauss8=d8.gauss_residual;r.law=r.cap2==(r.multiplicity<=2)&&r.cap4==(r.multiplicity<=4)&&r.cap8==(r.multiplicity<=8);return r;}
void run_orientation(Summary&s,int orientation){const auto parent=ftd::eft::initialize_connected_moore_block(L,width,orientation,orientation,.5,1e-13,4096);if(!parent.valid)return;int index=0;s.records.push_back(evaluate("center",orientation,index++,-1,-1,0,0,parent.state));for(int i=0;i<4;++i)for(int si:{-1,+1})s.records.push_back(evaluate("axis",orientation,index++,i,-1,si,0,parent.state));for(int i=0;i<4;++i)for(int j=i+1;j<4;++j)for(int si:{-1,+1})for(int sj:{-1,+1})s.records.push_back(evaluate("pair",orientation,index++,i,j,si,sj,parent.state));}
bool fingerprint(){const auto path=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0631/ftd_0631_connected_block_full_half_static_refinement_v1.json";std::ifstream in(path,std::ios::binary);const std::string bytes((std::istreambuf_iterator<char>(in)),{});return bytes.find(parent_protocol_sha256)!=std::string::npos&&bytes.find("CONNECTED_BLOCK_FULL_HALF_STATIC_REFINEMENT_CLOSED_NEGATIVE")!=std::string::npos;}
void summarize(Summary&s){s.geometries=static_cast<int>(s.records.size());s.coverage=s.parent&&s.geometries==66;s.positions=s.separation=s.cap8=s.law=s.coverage;std::map<int,int>hx,hy;for(const auto&r:s.records){s.max_multiplicity=std::max(s.max_multiplicity,r.multiplicity);if(std::isfinite(r.separation))s.minimum_separation=std::min(s.minimum_separation,r.separation);s.positions=s.positions&&r.positions;s.separation=s.separation&&(!std::isfinite(r.separation)||r.separation>=.9);s.cap8=s.cap8&&r.cap8&&r.gauss8<=1e-11;s.law=s.law&&r.law;s.cap2_failures+=!r.cap2;s.cap4_failures+=!r.cap4;s.cap8_failures+=!r.cap8;if(r.cap2)s.maximum_gauss=std::max(s.maximum_gauss,r.gauss2);if(r.cap4)s.maximum_gauss=std::max(s.maximum_gauss,r.gauss4);if(r.cap8)s.maximum_gauss=std::max(s.maximum_gauss,r.gauss8);(r.orientation==0?hx:hy)[r.multiplicity]++;}s.covariance=s.coverage&&hx==hy;s.discriminator=s.max_multiplicity==8&&s.cap2_failures>0&&s.cap4_failures>0&&s.cap8_failures==0;if(!s.coverage||!s.positions||!s.separation||!s.covariance)s.verdict="CONNECTED_BLOCK_CUBIC_EIGHT_FIBRE_EXECUTION_INVALID";else if(s.cap8&&s.law&&s.discriminator)s.verdict="CUBIC_EIGHT_FIBRE_NECESSARY_AND_SUFFICIENT_FOR_LOCKED_CHART";else if(s.cap8&&s.law)s.verdict="FINITE_FIBRE_BOUND_DIFFERENT_FROM_EIGHT";else s.verdict="CUBIC_EIGHT_FIBRE_CLOSED_NEGATIVE";}
void number(std::ostream&o,double x){if(std::isfinite(x))o<<x;else o<<"null";}void write(const Summary&s){const auto dir=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0632";std::filesystem::create_directories(dir);std::ofstream json(dir/"ftd_0632_connected_block_cubic_eight_fibre_v1.json");json<<std::setprecision(17)<<"{\n  \"ftd_id\": \"FTD-0632\",\n  \"protocol_sha256\": \""<<protocol_sha256<<"\",\n  \"verdict\": \""<<s.verdict<<"\",\n  \"production_changed\": false,\n  \"coverage_pass\": "<<s.coverage<<",\n  \"positions_pass\": "<<s.positions<<",\n  \"separation_pass\": "<<s.separation<<",\n  \"cap8_pass\": "<<s.cap8<<",\n  \"multiplicity_law_pass\": "<<s.law<<",\n  \"covariance_pass\": "<<s.covariance<<",\n  \"discriminator_pass\": "<<s.discriminator<<",\n  \"geometries\": "<<s.geometries<<",\n  \"maximum_multiplicity\": "<<s.max_multiplicity<<",\n  \"cap2_failures\": "<<s.cap2_failures<<",\n  \"cap4_failures\": "<<s.cap4_failures<<",\n  \"cap8_failures\": "<<s.cap8_failures<<",\n  \"minimum_same_anchor_separation\": ";number(json,s.minimum_separation);json<<",\n  \"maximum_gauss_residual\": "<<s.maximum_gauss<<"\n}\n";std::ofstream csv(dir/"ftd_0632_connected_block_cubic_eight_fibre_stencil_v1.csv");csv<<"ftd_id,label,orientation,index,i,j,si,sj,multiplicity,same_anchor_separation,unique_separation,positions,cap2,cap4,cap8,gauss2,gauss4,gauss8,law\n";for(const auto&r:s.records)csv<<std::setprecision(17)<<"FTD-0632,"<<r.label<<','<<r.orientation<<','<<r.index<<','<<r.i<<','<<r.j<<','<<r.si<<','<<r.sj<<','<<r.multiplicity<<','<<r.separation<<','<<r.unique_separation<<','<<r.positions<<','<<r.cap2<<','<<r.cap4<<','<<r.cap8<<','<<r.gauss2<<','<<r.gauss4<<','<<r.gauss8<<','<<r.law<<'\n';}
}
int main(){Summary s;s.parent=fingerprint();if(s.parent){run_orientation(s,0);run_orientation(s,1);}summarize(s);write(s);std::cout<<std::setprecision(17)<<"protocol_sha256="<<protocol_sha256<<'\n'<<"verdict="<<s.verdict<<'\n'<<"geometries="<<s.geometries<<" max_multiplicity="<<s.max_multiplicity<<" failures=("<<s.cap2_failures<<','<<s.cap4_failures<<','<<s.cap8_failures<<") min_separation="<<s.minimum_separation<<" gauss="<<s.maximum_gauss<<'\n';return s.verdict=="CONNECTED_BLOCK_CUBIC_EIGHT_FIBRE_EXECUTION_INVALID"?1:0;}
