// FTD-0698: fresh held-out amplitude symmetry-ray matter spectrum.
#define FTD_SEPARATION_PROTOCOL_SHA256 \
  "2C48B1788191F83C3C92F01F1AF78F21F4590F4D27F0CF381C1D3BFEECFFF5E0"
#define FTD_SEPARATION_IDENTIFIER "FTD-0698"
#define FTD_SEPARATION_RESULT_DIRECTORY "results/ftd_0698"
#define FTD_SEPARATION_RESULT_STEM \
  "ftd_0698_internal_excitation_symmetry_ray_parent_v1"
#define FTD_SEPARATION_CENTER_TOLERANCE 1e-12
#define FTD_SEPARATION_USE_BATCHED_REGIONAL 1
#define FTD_SEPARATION_USE_LOCAL_RESIDUAL 1
#define FTD_SEPARATION_VOLUME 113
#define FTD_SEPARATION_HORIZON 96
#define FTD_SEPARATION_LATE_START 80
#define FTD_SEPARATION_LATE_END 96
#define FTD_SEPARATION_PROGRESS_INTERVAL 1
#define FTD_SEPARATION_OBSERVATION_CADENCE 4
#define FTD_SEPARATION_MOMENTUM 7.5e-8
#define FTD_SEPARATION_EXTRA_HEADER \
  "internal_excitation_symmetry_ray_spectrum_hook.h"
#define FTD_SEPARATION_EXTRA_OBSERVE(...) ftd0698::observe(__VA_ARGS__)
#define FTD_SEPARATION_EXTRA_FINALIZE(...) ftd0698::finalize(__VA_ARGS__)
#define FTD_SEPARATION_EXTRA_EXECUTION_VALID ftd0698::execution_valid()
#include "test_causal_excitation_separation_v1.cpp"
