// FTD-0643: finite collective boost ladder from the analytic center.

#define FTD_0640_EMBEDDED
#include "test_connected_block_analytic_matter_modes.cpp"
#undef FTD_0640_EMBEDDED

namespace {

constexpr char boost_protocol_sha256[] =
    "CE7CB494A298CED4C04F39E7B776D2785675B339398621AF7D0DBB92CA0B03ED";
constexpr char boost_parent_sha256[] =
    "E4DCBC8F3BC0A8AE30986581C7B518F08155C28C5412697DEB01B6BECC782930";
constexpr int boost_ticks=16;

struct BoostSpec { std::string label,kind,family;Vec3 direction{};double p=0;int map_count=0; };
struct BoostTick { int tick=0,hops=0,multiplicity=0;Vec3 displacement{},momentum{},velocity{};double shape=0,strain=0,field_energy=0,drift=0,residual=0,separation=INFINITY,dressing=INFINITY,soft_fraction=0;std::vector<double> q; };
struct BoostArm {
  BoostSpec spec;bool initialized=false,forward=false,reverse=false,coherent=false,rest=false,high=false;int total_hops=0,max_multiplicity=0;double min_separation=INFINITY,max_shape=0,max_strain=0,max_drift=0,max_common=0,max_dressing=0,recovery=INFINITY,projected=0,transverse=INFINITY,free_displacement=0,mobility=INFINITY,soft_fraction=0,final_velocity=0;Vec3 displacement{},final_momentum{};std::string onset="na";std::vector<BoostTick> ticks;
};
struct BoostSummary {
  bool parent=false,eigensystem=false,coverage=false,execution=false,coherence=false,rest=false,high=false,monotonic=false,mirror=false,cubic=false;double beta=0,worst_common=0,worst_drift=0,worst_recovery=0,worst_shape=0,worst_strain=0,worst_dressing=0,mirror_residual=0,cubic_residual=0;std::array<double,3> last_pinned{{-1,-1,-1}},first_mobile{{-1,-1,-1}};std::string verdict="ANALYTIC_CENTER_BOOST_EXECUTION_INVALID";FullModes modes;std::vector<BoostArm> arms;
};

double boost_max(const Vec3&v){return std::max({std::abs(v.x),std::abs(v.y),std::abs(v.z)});}
Vec3 boost_cycle(Vec3 v,int count_map){for(int i=0;i<count_map;++i)v={v.z,v.x,v.y};return v;}
Vec3 boost_momentum(const ftd::eft::ConnectedMooreBlockState&s){Vec3 r{};for(const auto&p:s.constituents)r+=p.momentum;return r;}
Vec3 boost_velocity(const ftd::eft::ConnectedMooreBlockState&s){Vec3 r{};for(const auto&p:s.constituents)r+=ftd::eft::production_flat_velocity_from_momentum(p.momentum);return r*(1.0/s.constituents.size());}
double boost_shape(const ftd::eft::ConnectedMooreBlockState&a,const ftd::eft::ConnectedMooreBlockState&b){const Vec3 ca=center(a),cb=center(b);long double sum=0;for(int i=0;i<count;++i){const Vec3 d=(position(b.constituents[i])-cb)-(position(a.constituents[i])-ca);sum+=d.dot(d);}return std::sqrt(static_cast<double>(sum/count));}
double boost_face_dot(const ftd::eft::MatchedFaceFlux&a,const ftd::eft::MatchedFaceFlux&b){return static_cast<double>(ftd::eft::matched_face_dot(a,b));}
double boost_dressing(const ftd::eft::ConnectedMooreBlockState&s){auto geometry=s;for(auto&p:geometry.constituents)p.momentum={};const auto dressed=ftd::eft::redress_connected_moore_block_with_fibre_limit(geometry,8,1e-13,4096);if(!dressed.valid)return INFINITY;ftd::eft::MatchedFaceFlux delta(s.electric.L);for(std::size_t i=0;i<delta.x.size();++i){delta.x[i]=s.electric.x[i]-dressed.state.electric.x[i];delta.y[i]=s.electric.y[i]-dressed.state.electric.y[i];delta.z[i]=s.electric.z[i]-dressed.state.electric.z[i];}const double denominator=boost_face_dot(dressed.state.electric,dressed.state.electric);return denominator>0?std::sqrt(std::max(0.0,boost_face_dot(delta,delta))/denominator):INFINITY;}
double boost_soft_fraction(const std::vector<BoostTick>&ticks){long double soft=0,total=0;for(const auto&t:ticks)for(int i=0;i<N;++i){const long double p=static_cast<long double>(t.q[i])*t.q[i];total+=p;if(i<6)soft+=p;}return total>0?static_cast<double>(soft/total):1;}
bool boost_parent(){const auto path=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0642/ftd_0642_connected_block_coupled_transverse_response_v1.json";std::ifstream input(path,std::ios::binary);const std::string bytes((std::istreambuf_iterator<char>(input)),{});return bytes.find(boost_parent_sha256)!=std::string::npos||bytes.find("CONNECTED_BLOCK_COUPLED_TRANSVERSE_WEAK_HYBRID_CONSTRUCTIVE")!=std::string::npos;}

BoostArm run_boost(const BoostSpec&spec,const FullModes&modes,double beta,const ftd::eft::ConnectedMooreBlockOptions&options){BoostArm arm;arm.spec=spec;const auto reference=load_refined_state(0);if(reference.electric.L!=L)return arm;auto initial=reference;for(auto&p:initial.constituents)p.momentum=spec.direction*spec.p;arm.initialized=initial.constituents.size()==count;auto state=initial;const double e0=mode_energy(initial,beta,options);const Vec3 c0=center(initial);arm.free_displacement=boost_ticks*ftd::eft::production_flat_velocity_from_momentum(spec.direction*spec.p).mag();arm.forward=arm.initialized;ftd::eft::ConnectedMooreBlockSolveCache forward_cache,reverse_cache;
  for(int tick=1;arm.forward&&tick<=boost_ticks;++tick){const auto step=ftd::eft::solve_connected_moore_block_forward(state,options,&forward_cache);const double residual=common_residual(step);if(!step.valid||!step.common_action_gates_pass||residual>1e-10){arm.forward=false;break;}state=step.later;BoostTick row;row.tick=tick;row.hops=step.site_hops;row.displacement=center(state)-c0;row.momentum=boost_momentum(state);row.velocity=boost_velocity(state);row.shape=boost_shape(initial,state);row.strain=step.maximum_edge_strain;row.field_energy=beta*ftd::eft::matched_modified_energy(state.electric,state.magnetic_half,ftd::C_SPEED);row.drift=std::abs(mode_energy(state,beta,options)-e0);row.residual=residual;std::tie(row.multiplicity,row.separation)=mode_fibre(state);row.dressing=boost_dressing(state);row.q=project_modes(reference,state,modes);long double soft=0,total=0;for(int i=0;i<N;++i){const long double v=static_cast<long double>(row.q[i])*row.q[i];total+=v;if(i<6)soft+=v;}row.soft_fraction=total>0?static_cast<double>(soft/total):1;arm.total_hops+=row.hops;arm.max_multiplicity=std::max(arm.max_multiplicity,row.multiplicity);if(std::isfinite(row.separation))arm.min_separation=std::min(arm.min_separation,row.separation);arm.max_shape=std::max(arm.max_shape,row.shape);arm.max_strain=std::max(arm.max_strain,row.strain);arm.max_drift=std::max(arm.max_drift,row.drift);arm.max_common=std::max(arm.max_common,row.residual);arm.max_dressing=std::max(arm.max_dressing,row.dressing);arm.ticks.push_back(std::move(row));}
  arm.forward=arm.forward&&arm.ticks.size()==boost_ticks;arm.reverse=arm.forward;for(int tick=boost_ticks;arm.reverse&&tick>=1;--tick){const auto step=ftd::eft::solve_connected_moore_block_reverse(state,options,&reverse_cache);arm.max_common=std::max(arm.max_common,common_residual(step));if(!step.valid||!step.common_action_gates_pass||common_residual(step)>1e-10){arm.reverse=false;break;}state=step.earlier;}if(arm.reverse)arm.recovery=ftd::eft::connected_moore_block_state_max_difference(initial,state);arm.displacement=arm.ticks.empty()?Vec3{}:arm.ticks.back().displacement;arm.final_momentum=arm.ticks.empty()?Vec3{}:arm.ticks.back().momentum;arm.projected=arm.displacement.dot(spec.direction);arm.transverse=(arm.displacement-spec.direction*arm.projected).mag();arm.mobility=arm.free_displacement>0?arm.projected/arm.free_displacement:0;arm.final_velocity=arm.ticks.empty()?0:arm.ticks.back().velocity.dot(spec.direction);arm.soft_fraction=boost_soft_fraction(arm.ticks);arm.coherent=arm.initialized&&arm.forward&&arm.reverse&&arm.max_multiplicity<=8&&(!std::isfinite(arm.min_separation)||arm.min_separation>=.9)&&arm.max_shape<=.05&&arm.max_strain<=.05&&arm.max_drift<=1e-10&&arm.max_common<=1e-10&&arm.recovery<=1e-9;if(spec.p==0)arm.rest=arm.coherent&&arm.displacement.mag()<=1e-10&&boost_velocity(state).mag()<=1e-10&&arm.total_hops==0;if(spec.kind=="ladder"&&std::abs(spec.p-.12)<1e-15)arm.high=arm.coherent&&arm.projected>=.75&&arm.mobility>=.75&&arm.transverse<=.10&&arm.total_hops>=16&&arm.final_velocity>0&&arm.soft_fraction>=.95&&arm.max_dressing<=.50;if(spec.kind=="ladder"){if(arm.mobility>=.5&&arm.projected>0)arm.onset="mobile";else if(std::abs(arm.mobility)<=.1)arm.onset="pinned";else arm.onset="transition";}return arm;}

const BoostArm* boost_find(const BoostSummary&s,const std::string&family,const std::string&kind,double p,int map_count=0){for(const auto&a:s.arms)if(a.spec.family==family&&a.spec.kind==kind&&std::abs(a.spec.p-p)<1e-15&&a.spec.map_count==map_count)return &a;return nullptr;}
void evaluate_boost(BoostSummary&s){s.coverage=s.arms.size()==29;s.execution=s.coverage&&std::all_of(s.arms.begin(),s.arms.end(),[](const BoostArm&a){return a.initialized&&a.forward&&a.reverse;});s.coherence=s.execution&&std::all_of(s.arms.begin(),s.arms.end(),[](const BoostArm&a){return a.coherent;});const auto*rest=boost_find(s,"rest","rest",0);s.rest=rest&&rest->rest;s.high=s.monotonic=s.coherence;const std::array<double,7> ladder{{.001875,.00375,.0075,.015,.03,.06,.12}};int family_index=0;bool all_finite=true,all_mobile=true;for(const std::string family:{"100","110","111"}){double prior=-INFINITY;s.last_pinned[family_index]=-1;s.first_mobile[family_index]=-1;for(double p:ladder){const auto*a=boost_find(s,family,"ladder",p);if(!a){s.monotonic=false;continue;}s.monotonic=s.monotonic&&a->projected>=-1e-10&&a->projected+1e-6>=prior;prior=a->projected;if(a->onset=="pinned")s.last_pinned[family_index]=p;if(a->onset=="mobile"&&s.first_mobile[family_index]<0)s.first_mobile[family_index]=p;}const auto*h=boost_find(s,family,"ladder",.12);s.high=s.high&&h&&h->high;all_finite=all_finite&&s.last_pinned[family_index]>0&&s.first_mobile[family_index]>0;all_mobile=all_mobile&&s.last_pinned[family_index]<0&&std::all_of(ladder.begin(),ladder.end(),[&](double p){const auto*a=boost_find(s,family,"ladder",p);return a&&a->onset=="mobile";});++family_index;}
  s.mirror=s.coherence;s.mirror_residual=0;for(const std::string family:{"100","110","111"})for(double p:{.03,.12}){const auto*a=boost_find(s,family,"ladder",p),*n=boost_find(s,family,"mirror",p);if(!a||!n){s.mirror=false;continue;}for(int t=0;t<boost_ticks;++t){const auto&x=a->ticks[t];const auto&y=n->ticks[t];s.mirror_residual=std::max({s.mirror_residual,boost_max(x.displacement+y.displacement),std::abs(x.shape-y.shape),std::abs(x.field_energy-y.field_energy),std::abs(x.soft_fraction-y.soft_fraction),std::abs(x.dressing-y.dressing)});}s.mirror=s.mirror&&s.mirror_residual<=1e-7;}
  s.cubic=s.coherence;s.cubic_residual=0;for(const auto&a:s.arms)if(a.spec.kind=="cyclic"){const auto*c=boost_find(s,a.spec.family,"ladder",.12);if(!c){s.cubic=false;continue;}for(int t=0;t<boost_ticks;++t){const auto&x=c->ticks[t];const auto&y=a.ticks[t];s.cubic_residual=std::max({s.cubic_residual,boost_max(y.displacement-boost_cycle(x.displacement,a.spec.map_count)),boost_max(y.momentum-boost_cycle(x.momentum,a.spec.map_count)),std::abs(x.shape-y.shape),std::abs(x.field_energy-y.field_energy),std::abs(x.soft_fraction-y.soft_fraction),std::abs(x.dressing-y.dressing)});}s.cubic_residual=std::max(s.cubic_residual,std::abs(a.recovery-c->recovery));s.cubic=s.cubic&&a.total_hops==c->total_hops&&s.cubic_residual<=1e-7;}
  for(const auto&a:s.arms){s.worst_common=std::max(s.worst_common,a.max_common);s.worst_drift=std::max(s.worst_drift,a.max_drift);if(std::isfinite(a.recovery))s.worst_recovery=std::max(s.worst_recovery,a.recovery);s.worst_shape=std::max(s.worst_shape,a.max_shape);s.worst_strain=std::max(s.worst_strain,a.max_strain);s.worst_dressing=std::max(s.worst_dressing,a.max_dressing);}if(!s.parent||!s.eigensystem||!s.coverage||!s.execution||!s.coherence||!s.rest)s.verdict="ANALYTIC_CENTER_BOOST_EXECUTION_INVALID";else if(!s.high||!s.monotonic||!s.mirror||!s.cubic)s.verdict="ANALYTIC_CENTER_DIRECTIONAL_TRANSPORT_CLOSED";else if(all_finite)s.verdict="ANALYTIC_CENTER_COHERENT_FINITE_DEPINNING_CONSTRUCTIVE";else if(all_mobile)s.verdict="ANALYTIC_CENTER_COHERENT_NO_THRESHOLD_AT_LADDER_RESOLUTION";else s.verdict="ANALYTIC_CENTER_COHERENT_MIXED_ONSET";}

std::vector<BoostSpec> boost_specs(){const double r2=1/std::sqrt(2.0),r3=1/std::sqrt(3.0);const std::vector<std::pair<std::string,Vec3>> families{{"100",{1,0,0}},{"110",{r2,r2,0}},{"111",{r3,r3,r3}}};const std::array<double,7> ladder{{.001875,.00375,.0075,.015,.03,.06,.12}};std::vector<BoostSpec>s{{"rest","rest","rest",{},0,0}};for(const auto&f:families){for(double p:ladder)s.push_back({f.first+"_p"+std::to_string(p),"ladder",f.first,f.second,p,0});for(double p:{.03,.12})s.push_back({f.first+"_n"+std::to_string(p),"mirror",f.first,f.second*(-1),p,0});}s.push_back({"100_y","cyclic","100",{0,1,0},.12,1});s.push_back({"100_z","cyclic","100",{0,0,1},.12,2});s.push_back({"110_yz","cyclic","110",{0,r2,r2},.12,1});s.push_back({"110_xz","cyclic","110",{r2,0,r2},.12,2});return s;}

void write_boost(const BoostSummary&s){const auto dir=std::filesystem::path(__FILE__).parent_path().parent_path()/"results/ftd_0643";std::filesystem::create_directories(dir);std::ofstream json(dir/"ftd_0643_analytic_center_collective_boost_ladder_v1.json");json<<std::setprecision(17)<<"{\n  \"ftd_id\": \"FTD-0643\",\n  \"protocol_sha256\": \""<<boost_protocol_sha256<<"\",\n  \"parent_result_sha256\": \""<<boost_parent_sha256<<"\",\n  \"verdict\": \""<<s.verdict<<"\",\n  \"production_changed\": false,\n  \"arm_count\": "<<s.arms.size()<<",\n  \"ticks_each_direction\": "<<boost_ticks<<",\n  \"coverage_pass\": "<<s.coverage<<",\n  \"execution_pass\": "<<s.execution<<",\n  \"coherence_pass\": "<<s.coherence<<",\n  \"rest_pass\": "<<s.rest<<",\n  \"high_boost_pass\": "<<s.high<<",\n  \"monotonic_pass\": "<<s.monotonic<<",\n  \"mirror_pass\": "<<s.mirror<<",\n  \"cubic_pass\": "<<s.cubic<<",\n  \"last_pinned_100\": "<<s.last_pinned[0]<<",\n  \"last_pinned_110\": "<<s.last_pinned[1]<<",\n  \"last_pinned_111\": "<<s.last_pinned[2]<<",\n  \"first_mobile_100\": "<<s.first_mobile[0]<<",\n  \"first_mobile_110\": "<<s.first_mobile[1]<<",\n  \"first_mobile_111\": "<<s.first_mobile[2]<<",\n  \"mirror_residual\": "<<s.mirror_residual<<",\n  \"cubic_residual\": "<<s.cubic_residual<<",\n  \"worst_common_residual\": "<<s.worst_common<<",\n  \"worst_energy_drift\": "<<s.worst_drift<<",\n  \"worst_recovery\": "<<s.worst_recovery<<",\n  \"worst_shape\": "<<s.worst_shape<<",\n  \"worst_strain\": "<<s.worst_strain<<",\n  \"worst_dressing\": "<<s.worst_dressing<<"\n}\n";
  std::ofstream arms(dir/"ftd_0643_analytic_center_collective_boost_ladder_arms_v1.csv");arms<<"ftd_id,label,kind,family,p,dir_x,dir_y,dir_z,map_count,initialized,forward,reverse,coherent,rest,high,onset,total_hops,free_displacement,projected,transverse,mobility,soft_fraction,max_dressing,max_shape,max_strain,max_drift,max_common,recovery,disp_x,disp_y,disp_z,momentum_x,momentum_y,momentum_z,final_velocity,max_multiplicity,min_separation\n";for(const auto&a:s.arms)arms<<std::setprecision(17)<<"FTD-0643,"<<a.spec.label<<','<<a.spec.kind<<','<<a.spec.family<<','<<a.spec.p<<','<<a.spec.direction.x<<','<<a.spec.direction.y<<','<<a.spec.direction.z<<','<<a.spec.map_count<<','<<a.initialized<<','<<a.forward<<','<<a.reverse<<','<<a.coherent<<','<<a.rest<<','<<a.high<<','<<a.onset<<','<<a.total_hops<<','<<a.free_displacement<<','<<a.projected<<','<<a.transverse<<','<<a.mobility<<','<<a.soft_fraction<<','<<a.max_dressing<<','<<a.max_shape<<','<<a.max_strain<<','<<a.max_drift<<','<<a.max_common<<','<<a.recovery<<','<<a.displacement.x<<','<<a.displacement.y<<','<<a.displacement.z<<','<<a.final_momentum.x<<','<<a.final_momentum.y<<','<<a.final_momentum.z<<','<<a.final_velocity<<','<<a.max_multiplicity<<','<<a.min_separation<<'\n';
  std::ofstream ticks(dir/"ftd_0643_analytic_center_collective_boost_ladder_ticks_v1.csv");ticks<<"ftd_id,label,tick,hops,disp_x,disp_y,disp_z,momentum_x,momentum_y,momentum_z,velocity_x,velocity_y,velocity_z,shape,strain,field_energy,drift,residual,multiplicity,separation,dressing,soft_fraction";for(int i=0;i<N;++i)ticks<<",q"<<i;ticks<<'\n';for(const auto&a:s.arms)for(const auto&t:a.ticks){ticks<<std::setprecision(17)<<"FTD-0643,"<<a.spec.label<<','<<t.tick<<','<<t.hops<<','<<t.displacement.x<<','<<t.displacement.y<<','<<t.displacement.z<<','<<t.momentum.x<<','<<t.momentum.y<<','<<t.momentum.z<<','<<t.velocity.x<<','<<t.velocity.y<<','<<t.velocity.z<<','<<t.shape<<','<<t.strain<<','<<t.field_energy<<','<<t.drift<<','<<t.residual<<','<<t.multiplicity<<','<<t.separation<<','<<t.dressing<<','<<t.soft_fraction;for(double q:t.q)ticks<<','<<q;ticks<<'\n';}}
}

#ifdef FTD_0643_EMBEDDED
int ftd_0643_embedded_main(){
#else
int main(){
#endif
BoostSummary summary;summary.parent=boost_parent();const auto normalization=ftd::eft::measure_face_flux_normalization();summary.beta=normalization.mapped_field_work_coefficient;ftd::eft::ConnectedMooreBlockOptions options;options.allow_shared_anchor_chart=true;if(summary.parent&&normalization.valid){const auto reference=load_refined_state(0);const auto analytic=analytic_at("boost",0,reference,summary.beta,options);if(analytic.valid)summary.modes=full_modes(analytic.hessian);summary.eigensystem=summary.modes.valid;}if(summary.eigensystem){const auto specs=boost_specs();constexpr std::size_t batch=8;for(std::size_t start=0;start<specs.size();start+=batch){std::vector<std::future<BoostArm>> futures;const auto end=std::min(specs.size(),start+batch);for(std::size_t i=start;i<end;++i)futures.push_back(std::async(std::launch::async,[&,spec=specs[i]](){return run_boost(spec,summary.modes,summary.beta,options);}));for(std::size_t i=start;i<end;++i){summary.arms.push_back(futures[i-start].get());std::cout<<"completed "<<specs[i].label<<std::endl;}}}evaluate_boost(summary);write_boost(summary);std::cout<<std::setprecision(17)<<"protocol_sha256="<<boost_protocol_sha256<<'\n'<<"verdict="<<summary.verdict<<'\n'<<"coverage="<<summary.coverage<<" execution="<<summary.execution<<" coherence="<<summary.coherence<<" rest="<<summary.rest<<" high="<<summary.high<<" monotonic="<<summary.monotonic<<" mirror="<<summary.mirror<<" cubic="<<summary.cubic<<'\n'<<"pinned="<<summary.last_pinned[0]<<','<<summary.last_pinned[1]<<','<<summary.last_pinned[2]<<" mobile="<<summary.first_mobile[0]<<','<<summary.first_mobile[1]<<','<<summary.first_mobile[2]<<'\n';for(const auto&a:summary.arms)std::cout<<a.spec.label<<" coherent="<<a.coherent<<" onset="<<a.onset<<" D="<<a.projected<<" mu="<<a.mobility<<" hops="<<a.total_hops<<" soft="<<a.soft_fraction<<" dressing="<<a.max_dressing<<" recovery="<<a.recovery<<'\n';return summary.verdict=="ANALYTIC_CENTER_BOOST_EXECUTION_INVALID"?0:1;}
