#!/usr/bin/env python3
"""What IS the fine structure constant? How is it actually measured?"""
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

print('=' * 78)
print('  WHAT IS ALPHA? HOW IS 137.035999 ACTUALLY OBTAINED?')
print('=' * 78)

print()
print('  WHAT ALPHA IS:')
print()
print('  alpha = e^2 / (4*pi*epsilon_0*hbar*c)')
print()
print('  Dimensionless. No units. The probability amplitude (squared)')
print('  for a charged particle to emit or absorb a photon.')
print('  ~1/137 means roughly 1 in 137 chances per encounter.')
print()

print('  HOW IT IS MEASURED (the actual chain):')
print()
print('  There is no device that reads out 137.036 directly.')
print('  The measurement is INDIRECT:')
print()
print('  CHAIN 1: Electron g-2 (most precise)')
print('    1. Trap a single electron in a Penning trap.')
print('    2. Measure g_e/2 = 1.00115965218059(13) [13 digits]')
print('    3. Compute g_e from QED as a series in alpha:')
print('       g_e/2 = 1 + alpha/(2pi) - 0.328*(alpha/pi)^2 + ...')
print('       Computed to 5 LOOPS = 12,672 Feynman diagrams.')
print('    4. INVERT: find alpha that makes QED match measured g_e.')
print('    -> alpha^{-1} = 137.035999166(15)')
print()
print('  CHAIN 2: Cesium atom recoil')
print('    1. Fire photons at Cs atoms, measure recoil velocity.')
print('    2. Extract h/m_Cs via matter-wave interferometry.')
print('    3. Combine with mass ratios to get alpha.')
print('    -> alpha^{-1} = 137.035999046(27) [Parker 2018]')
print()
print('  CHAIN 3: Rubidium atom recoil')
print('    Same method, different atom.')
print('    -> alpha^{-1} = 137.035999206(11) [Morel 2020]')
print()
print('  CODATA 2022 combines these:')
print('    alpha^{-1} = 137.035999177(21)')
print()

print('  THE CRITICAL POINT:')
print()
print('  The "measured" alpha is NOT a direct observation.')
print('  It is: experiment(g_e or h/m) + theory(QED series) -> alpha.')
print()
print('  The precision depends on:')
print('    (a) Measuring g_e or recoil (~13 digits)')
print('    (b) Computing the QED series (~5 loops, 12672 diagrams)')
print('    (c) Assuming QED is EXACTLY correct')
print()
print('  If QED has even a tiny systematic at 5-loop,')
print('  the extracted alpha shifts.')
print()

print('  THE TENSION:')
print()
print('  Cs and Rb recoil DISAGREE at 5.4 sigma:')
print('    Cs: 137.035999046(27)')
print('    Rb: 137.035999206(11)')
print('    Gap: 0.000000160 = 1.2 ppb')
print()
print('  The experimental community has an unresolved 5-sigma tension')
print('  at the parts-per-billion level. The value 137.035999177 is a')
print('  WEIGHTED AVERAGE with expanded uncertainty to accommodate this.')
print()

print('  WHERE FTD SITS:')
print()
print('  FTD tree:    137.036171        (1.26 ppm above CODATA)')
print('  FTD 1-loop:  ~137.036001       (99.2%% of gap closed)')
print('  FTD 4-term:  137.0359999(07)   (sub-ppt)')
print('  CODATA:      137.035999177(21)')
print()
print('  Tree-level gap: 0.000172 = 1.26 ppm')
print('  After 1-loop:   ~0.000002 = ~15 ppb')
print('  Cs-Rb tension:  0.000000160 = 1.2 ppb')
print()
print('  After the one-loop correction, FTD is within 10x of the')
print('  level where the EXPERIMENTS THEMSELVES disagree.')
print()

print('  THE LOGICAL STRUCTURE:')
print()
print('  QED chain: measure g_e -> apply 5-loop QED series -> invert -> alpha')
print('  FTD chain: evaluate Gamma(1/4)/Gamma(3/4) -> master quadratic -> alpha')
print()
print('  Both chains end at the same number.')
print('  The QED chain uses an experiment + perturbation theory.')
print('  The FTD chain uses pure mathematics + one quadratic equation.')
print()
print('  Neither chain measures alpha directly.')
print('  Both DERIVE it from something else.')
print()
print('  The difference: QED needs a physical measurement (g_e) as input.')
print('  FTD needs only the Gamma function (a mathematical object).')
print()

print('  WHAT THIS MEANS FOR THE 1.26 PPM GAP:')
print()
print('  The gap between FTD tree-level (137.036171) and CODATA (137.035999)')
print('  is 1.26 ppm. This could be:')
print()
print('    (a) Radiative correction (FTD claim: one-loop lattice tadpole')
print('        closes 99.2%% of the gap, higher loops should close the rest)')
print()
print('    (b) A systematic in the master quadratic (the equation')
print('        x^2 - 16G*^2 x + 16G*^3 = 0 might need modification)')
print()
print('    (c) A difference in WHAT is being computed: FTD computes alpha')
print('        at the LATTICE SCALE (the Planck scale), not at the')
print('        electron mass scale where experiments measure it.')
print('        Running alpha from Planck to electron mass via RG')
print('        changes it by O(alpha*log(M_P/m_e)) ~ 1%%, much larger')
print('        than 1.26 ppm. So the running must nearly cancel.')
print()
print('  The most CONSERVATIVE interpretation:')
print('  FTD tree-level gives a value within 1.26 ppm of the')
print('  experimentally derived value. One-loop closes 99.2%% of that.')
print('  Whether higher loops close the rest, or whether the remaining')
print('  ~15 ppb requires new physics, is an open question that may')
print('  be resolved when the Cs-Rb tension is itself resolved.')
