#pragma once
// tritium/trit.h — Core ternary types for balanced ternary {-1, 0, +1}
//
// Two representations:
//   TritWord64 — compute format: 32 trits in uint64_t (2 bits each)
//   TritPack   — storage format: 5 trits in uint8_t (3^5 = 243)

#include <cstdint>
#include <array>

#if defined(_MSC_VER)
#include <intrin.h>
#endif

namespace tritium {

// Portable popcount for uint64_t
inline int popcount64(uint64_t x) {
#if defined(_MSC_VER)
    return static_cast<int>(__popcnt64(x));
#elif defined(__GNUC__) || defined(__clang__)
    return popcount64(x);
#else
    x = x - ((x >> 1) & 0x5555555555555555ULL);
    x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
    x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
    return static_cast<int>((x * 0x0101010101010101ULL) >> 56);
#endif
}

// Single balanced ternary digit: -1, 0, +1
enum class Trit : int8_t { Neg = -1, Zero = 0, Pos = 1 };

// Negate a single trit
inline Trit operator-(Trit t) {
    return static_cast<Trit>(-static_cast<int8_t>(t));
}

// Convert trit to int
inline int to_int(Trit t) { return static_cast<int>(t); }

// Convert int to trit (clamps to {-1, 0, +1})
inline Trit to_trit(int v) {
    if (v > 0) return Trit::Pos;
    if (v < 0) return Trit::Neg;
    return Trit::Zero;
}

// ============================================================================
// TritWord64 — Compute format: 32 trits packed in a uint64_t
// ============================================================================
//
// Encoding per 2-bit slot:
//   00 = Zero (0)
//   01 = Pos  (+1)
//   11 = Neg  (-1)
//   10 = invalid (never generated by valid operations)
//
// Trit at position i occupies bits [2i, 2i+1].

struct TritWord64 {
    uint64_t bits = 0;

    static constexpr int CAPACITY = 32;

    // Masks
    static constexpr uint64_t EVEN_BITS = 0x5555555555555555ULL; // low bit of each pair
    static constexpr uint64_t ODD_BITS  = 0xAAAAAAAAAAAAAAAAULL; // high bit of each pair

    // Extract trit at position i (0-31)
    Trit get(int i) const {
        uint64_t pair = (bits >> (2 * i)) & 0x3;
        // 00 -> 0, 01 -> +1, 11 -> -1, 10 -> invalid (treat as 0)
        if (pair == 0x0) return Trit::Zero;
        if (pair == 0x1) return Trit::Pos;
        if (pair == 0x3) return Trit::Neg;
        return Trit::Zero; // 10: invalid, shouldn't happen
    }

    // Set trit at position i (0-31)
    void set(int i, Trit t) {
        uint64_t mask = ~(uint64_t(0x3) << (2 * i));
        uint64_t val;
        switch (t) {
            case Trit::Zero: val = 0x0; break;
            case Trit::Pos:  val = 0x1; break;
            case Trit::Neg:  val = 0x3; break;
        }
        bits = (bits & mask) | (val << (2 * i));
    }

    // Fill all 32 positions with the same trit
    static TritWord64 splat(Trit t) {
        TritWord64 w;
        uint64_t pair;
        switch (t) {
            case Trit::Zero: pair = 0x0; break;
            case Trit::Pos:  pair = 0x1; break;
            case Trit::Neg:  pair = 0x3; break;
        }
        // Replicate 2-bit pattern across 64 bits
        uint64_t v = pair;
        v |= v << 2;   // 4 bits
        v |= v << 4;   // 8 bits
        v |= v << 8;   // 16 bits
        v |= v << 16;  // 32 bits
        v |= v << 32;  // 64 bits
        w.bits = v;
        return w;
    }

    // Count of non-void trits (positions that are +1 or -1)
    int popcount_nonzero() const {
        // A trit is nonzero iff at least one bit of its 2-bit pair is set.
        // low | high gives 1 in the low bit for each nonzero pair.
        uint64_t low  = bits & EVEN_BITS;
        uint64_t high = (bits >> 1) & EVEN_BITS;
        uint64_t nonzero = low | high; // one bit per trit, set if nonzero
        return popcount64(nonzero);
    }

    // Count of positive trits (+1)
    int popcount_pos() const {
        // Pos = 01: low bit set, high bit clear
        uint64_t low  = bits & EVEN_BITS;
        uint64_t high = (bits >> 1) & EVEN_BITS;
        uint64_t pos = low & ~high;
        return popcount64(pos);
    }

    // Count of negative trits (-1)
    int popcount_neg() const {
        // Neg = 11: both bits set
        uint64_t low  = bits & EVEN_BITS;
        uint64_t high = (bits >> 1) & EVEN_BITS;
        uint64_t neg = low & high;
        return popcount64(neg);
    }

    bool operator==(const TritWord64& o) const { return bits == o.bits; }
    bool operator!=(const TritWord64& o) const { return bits != o.bits; }
};

// ============================================================================
// TritPack — Storage format: 5 trits packed in a uint8_t
// ============================================================================
//
// Encoding: value = sum(ti * 3^i) for i=0..4, where ti ∈ {0,1,2}
// ti is the trit value offset by +1: Neg(-1)→0, Zero(0)→1, Pos(+1)→2
// Range: [0, 242] (3^5 - 1)

struct TritPack {
    uint8_t byte = 121; // 121 = 1 + 3 + 9 + 27 + 81 = all zeros

    static constexpr int CAPACITY = 5;
    static constexpr int POWERS[5] = {1, 3, 9, 27, 81};

    // Extract trit at position i (0-4)
    Trit get(int i) const {
        int v = (byte / POWERS[i]) % 3; // 0, 1, or 2
        return static_cast<Trit>(v - 1);  // -> -1, 0, +1
    }

    // Set trit at position i (0-4)
    void set(int i, Trit t) {
        int encoded = static_cast<int>(t) + 1; // -1→0, 0→1, +1→2
        int current = (byte / POWERS[i]) % 3;
        byte = static_cast<uint8_t>(byte + (encoded - current) * POWERS[i]);
    }

    bool operator==(const TritPack& o) const { return byte == o.byte; }
    bool operator!=(const TritPack& o) const { return byte != o.byte; }
};

} // namespace tritium
