"""generate_phase_i_lattice_green_fixtures.py — emit C++ test fixtures for Phase I.

Computes the lattice Poisson Green's function G_L(r) along the x-axis at
selected L and r values, using the SC7 stencil (matching the engine's
gauss-projection 7-point Laplacian). Emits values at high precision for
embedding in benchmark_phase_i_native_coupling.cpp.

The Phase I cross-check assertion is:
    alpha_r_engine(r, L) == (1/x_+) * 2 * r * G_L(r)
where the LHS is what benchmark_emergent_alpha measures in the
wave-propagation channel, and the RHS factorizes into:
    1/x_+        — FTD-native coupling (master quadratic [THEOREM])
    2 r G_L(r)   — lattice geometric kernel (Phase G [THEOREM])

USAGE:
    python scripts/proofs/generate_phase_i_lattice_green_fixtures.py
"""

from __future__ import annotations

import sys
import numpy as np


def lattice_green_sc7(L: int) -> np.ndarray:
    """Periodic lattice Poisson Green's function on L^3 torus, SC7 stencil.

    Solves Δ_L G = -δ where Δ_L is the 7-point Laplacian
    Δ_L f(x) = sum_{neighbors} (f(nbr) - f(x)) over 6 face neighbors.
    Eigenvalue: lambda(k) = 2 * (3 - cos kx - cos ky - cos kz).
    Zero-mean convention: G(0) = 0.
    """
    kx = 2 * np.pi * np.fft.fftfreq(L)
    ky = 2 * np.pi * np.fft.fftfreq(L)
    kz = 2 * np.pi * np.fft.fftfreq(L)
    KX, KY, KZ = np.meshgrid(kx, ky, kz, indexing="ij")
    lam = 2 * (3 - np.cos(KX) - np.cos(KY) - np.cos(KZ))
    with np.errstate(divide="ignore", invalid="ignore"):
        G_k = np.where(lam > 1e-12, 1.0 / lam, 0.0)
    G_k[0, 0, 0] = 0.0
    G_L = np.fft.ifftn(G_k).real
    return G_L


def main():
    print("// Auto-generated by scripts/proofs/generate_phase_i_lattice_green_fixtures.py")
    print("// SC7 Poisson Green's function values at selected (L, r) pairs along x-axis.")
    print("// Ground truth for Phase I cross-check (FTD-0125).")
    print()
    print("namespace phase_i {")
    print()
    print("struct GreenFixture { int L; int r; double G_L_r; double two_r_G; };")
    print()

    cases = []
    for L in [32, 64]:
        G_L = lattice_green_sc7(L)
        # Sample along x-axis at small/medium/large r
        for r in [4, 8, L // 4, L // 3]:
            G_at_r = float(G_L[r, 0, 0])
            two_r_G = 2.0 * r * G_at_r
            cases.append((L, r, G_at_r, two_r_G))

    print("// L, r, G_L(r), 2*r*G_L(r)")
    print("inline constexpr GreenFixture kFixtures[] = {")
    for L, r, G, twg in cases:
        print(f"    {{ {L}, {r}, {G:.15e}, {twg:.15e} }},")
    print("};")
    print()
    print(f"inline constexpr int kNumFixtures = {len(cases)};")
    print()
    print("}  // namespace phase_i")


if __name__ == "__main__":
    main()
