"""generate_phase_i_lattice_green_fixtures.py — emit C++ test fixtures for Phase I.

Computes the lattice Poisson Green's function G_L(r) along the x-axis at
selected L and r values, using the G18 stencil (the engine's gauss-
projection runs `sor_sweep_18pt` per engine/src/poisson_solvers.cpp; this
is the isotropic 18-point Laplacian, NOT the 7-point SC stencil).

The G18 Green's function differs from SC7 by O(1) factors at finite r;
see FTD-0118 for details. Critical to match the engine's actual stencil
when comparing benchmark output to fixture values.

Emits values at high precision for embedding in
benchmark_phase_i_native_coupling.cpp.

The Phase I cross-check assertion is:
    alpha_r_engine(r, L) == (1/x_+) * 2 * r * G_L(r)
where the LHS is what benchmark_emergent_alpha measures in the
wave-propagation channel, and the RHS factorizes into:
    1/x_+        — FTD-native coupling (master quadratic [THEOREM])
    2 r G_L(r)   — lattice geometric kernel (Phase G [THEOREM])

USAGE:
    python scripts/proofs/generate_phase_i_lattice_green_fixtures.py
"""

from __future__ import annotations

import sys
import numpy as np


def lattice_green_g18(L: int) -> np.ndarray:
    """Periodic lattice Poisson Green's function on L^3 torus, G18 stencil.

    Matches the engine's `sor_sweep_18pt` in engine/src/poisson_solvers.cpp.
    The 18-point isotropic Laplacian has eigenvalue
        lambda^G18(k) = (4/3) * sum_i sin^2(k_i/2)
                      + (8/3) * sum_{i<j} sin^2(k_i/2) * sin^2(k_j/2)
    (a = 1/3 face-stencil weight, b = 1/6 edge-stencil weight, c = 0 corner).

    Zero-mean convention: G(0) = 0.
    """
    kx = 2 * np.pi * np.fft.fftfreq(L)
    ky = 2 * np.pi * np.fft.fftfreq(L)
    kz = 2 * np.pi * np.fft.fftfreq(L)
    KX, KY, KZ = np.meshgrid(kx, ky, kz, indexing="ij")
    s2x = np.sin(KX / 2) ** 2
    s2y = np.sin(KY / 2) ** 2
    s2z = np.sin(KZ / 2) ** 2
    lam = (4.0 / 3.0) * (s2x + s2y + s2z) \
        + (8.0 / 3.0) * (s2x * s2y + s2x * s2z + s2y * s2z)
    with np.errstate(divide="ignore", invalid="ignore"):
        G_k = np.where(lam > 1e-12, 1.0 / lam, 0.0)
    G_k[0, 0, 0] = 0.0
    G_L = np.fft.ifftn(G_k).real
    return G_L


def main():
    print("// Auto-generated by scripts/proofs/generate_phase_i_lattice_green_fixtures.py")
    print("// G18 Poisson Green's function values at selected (L, r) pairs along x-axis.")
    print("// Matches engine's sor_sweep_18pt stencil per engine/src/poisson_solvers.cpp.")
    print("// Ground truth for Phase I cross-check (FTD-0125).")
    print()
    print("namespace phase_i {")
    print()
    print("struct GreenFixture { int L; int r; double G_L_r; double two_r_G; };")
    print()

    cases = []
    for L in [32, 64]:
        G_L = lattice_green_g18(L)
        # Sample along x-axis at small/medium/large r
        for r in [4, 8, L // 4, L // 3]:
            G_at_r = float(G_L[r, 0, 0])
            two_r_G = 2.0 * r * G_at_r
            cases.append((L, r, G_at_r, two_r_G))

    print("// L, r, G_L(r), 2*r*G_L(r)")
    print("inline constexpr GreenFixture kFixtures[] = {")
    for L, r, G, twg in cases:
        print(f"    {{ {L}, {r}, {G:.15e}, {twg:.15e} }},")
    print("};")
    print()
    print(f"inline constexpr int kNumFixtures = {len(cases)};")
    print()
    print("}  // namespace phase_i")


if __name__ == "__main__":
    main()
