"""
Proof — FTD-0110 Phase B: Global field projection onto local slow modes
==========================================================================

Phase A reformulation: instead of analyzing isolated 27-blocks with a
delta source at each block's center (which gives universal results), we
now compute the GLOBAL FIELD generated by an origin delta source and
project it onto each block's LOCAL slow mode.

Method:
  1. Compute lattice Poisson Green's function G_L(r) on L=32 lattice via
     direct Fourier sum.
  2. For each sample block position x_0 of each symmetry type, build the
     27-component field vector J_block(delta) = G_L(x_0 + delta - origin).
  3. Project J_block onto the block's local trivial-irrep subspace.
  4. Compute slow-mode energy fraction f_slow(x_0) := |<v_slow, J_block>|^2 / |J_block|^2.
  5. Test: does f_slow vary with symmetry type? Specifically, does it
     match 1/sqrt(d_G) (the empirical regularity)?

Hypothesis under test: per-block manifestation efficiency at off-center
blocks is f_slow(G) ~ 1/sqrt(d_G) where d_G is the trivial-irrep dim.

Provenance: docs/theory/03_derivations/EXPLR_FTD_0110_NONLINEAR_BRIDGE_ANALYSIS.md
LEDGER: FTD-0119 Phase B (Mechanism alpha closure attempt).

Usage:
    python scripts/proofs/proof_ftd0110_langevin_steady_state.py
"""

import math
import sys
from itertools import product, permutations

import numpy as np


# ---------------------------------------------------------------------------
# Lattice setup
# ---------------------------------------------------------------------------

L_LATTICE = 32                  # global lattice size
C_LAT = 1.0 / math.sqrt(3.0)    # CFL speed of light


# ---------------------------------------------------------------------------
# Voxels of a 27-block (relative coordinates {-1, 0, 1}^3)
# ---------------------------------------------------------------------------

VOXELS = [tuple(d) for d in product(range(-1, 2), repeat=3)]
N_VOXELS = len(VOXELS)
VOXEL_INDEX = {v: i for i, v in enumerate(VOXELS)}
CENTER_INDEX = VOXEL_INDEX[(0, 0, 0)]


# ---------------------------------------------------------------------------
# 18-point Laplacian on the 27-voxel block (Phase A)
# ---------------------------------------------------------------------------

def build_laplacian_27():
    L = np.zeros((N_VOXELS, N_VOXELS))
    a_face = 1.0 / 3.0
    b_edge = 1.0 / 6.0
    for i, vi in enumerate(VOXELS):
        L[i, i] = -(6 * a_face + 12 * b_edge)
        for j, vj in enumerate(VOXELS):
            if i == j:
                continue
            d2 = sum((a - b) ** 2 for a, b in zip(vi, vj))
            if d2 == 1:
                L[i, j] = a_face
            elif d2 == 2:
                L[i, j] = b_edge
    return L


# ---------------------------------------------------------------------------
# Symmetry groups + trivial-irrep projector
# ---------------------------------------------------------------------------

def gen_O_h():
    return [(p, s) for p in permutations(range(3))
                   for s in product([1, -1], repeat=3)]

def gen_C_4v_x():
    return [
        ((0, 1, 2), (1, 1, 1)),
        ((0, 2, 1), (1, -1, 1)),
        ((0, 1, 2), (1, -1, -1)),
        ((0, 2, 1), (1, 1, -1)),
        ((0, 1, 2), (1, -1, 1)),
        ((0, 1, 2), (1, 1, -1)),
        ((0, 2, 1), (1, 1, 1)),
        ((0, 2, 1), (1, -1, -1)),
    ]

def gen_C_3v_xyz():
    return [
        ((0, 1, 2), (1, 1, 1)),
        ((1, 2, 0), (1, 1, 1)),
        ((2, 0, 1), (1, 1, 1)),
        ((1, 0, 2), (1, 1, 1)),
        ((0, 2, 1), (1, 1, 1)),
        ((2, 1, 0), (1, 1, 1)),
    ]

def gen_C_2v_xy():
    return [
        ((0, 1, 2), (1, 1, 1)),
        ((1, 0, 2), (1, 1, 1)),
        ((0, 1, 2), (1, 1, -1)),
        ((1, 0, 2), (1, 1, -1)),
    ]

def gen_C_s_y():
    return [
        ((0, 1, 2), (1, 1, 1)),
        ((0, 1, 2), (1, 1, -1)),
    ]

def gen_C_1():
    return [((0, 1, 2), (1, 1, 1))]


def perm_matrix(perm, sign):
    M = np.zeros((N_VOXELS, N_VOXELS))
    for j, v in enumerate(VOXELS):
        gv = tuple(sign[i] * v[perm[i]] for i in range(3))
        i = VOXEL_INDEX[gv]
        M[i, j] = 1.0
    return M


def trivial_basis(elements):
    P = np.zeros((N_VOXELS, N_VOXELS))
    for perm, sign in elements:
        P += perm_matrix(perm, sign)
    P /= len(elements)
    eigvals, eigvecs = np.linalg.eigh(P)
    mask = eigvals > 0.5
    return eigvecs[:, mask]


# ---------------------------------------------------------------------------
# Global lattice Poisson Green's function
# ---------------------------------------------------------------------------

def lattice_green_function_table(L_side, c=C_LAT, max_distance=20):
    """Compute G_L(r) for r = (rx, ry, rz) with |r|_inf <= max_distance.

    G_L solves c^2 * Delta_L G_L = -delta on the periodic L^3 lattice
    using the SC (simple cubic) Laplacian. Per FTD's Phase G convention.
    """
    table = {}
    # Compute via direct Fourier sum
    for rx in range(-max_distance, max_distance + 1):
        for ry in range(-max_distance, max_distance + 1):
            for rz in range(-max_distance, max_distance + 1):
                if abs(rx) > max_distance or abs(ry) > max_distance or abs(rz) > max_distance:
                    continue
                # Compute G_L at (rx, ry, rz) via Fourier sum
                total = 0.0
                for n1 in range(L_side):
                    for n2 in range(L_side):
                        for n3 in range(L_side):
                            if n1 == 0 and n2 == 0 and n3 == 0:
                                continue
                            k = (2 * math.pi * n1 / L_side,
                                 2 * math.pi * n2 / L_side,
                                 2 * math.pi * n3 / L_side)
                            kh2 = sum(4.0 * math.sin(0.5 * ki) ** 2 for ki in k)
                            if kh2 == 0:
                                continue
                            phase = math.cos(k[0]*rx + k[1]*ry + k[2]*rz)
                            total += phase / (c * c * kh2)
                table[(rx, ry, rz)] = total / (L_side ** 3)
    return table


def lattice_green_at_offset(rx, ry, rz, c=C_LAT, L_side=L_LATTICE):
    """Single-point evaluation of G_L."""
    total = 0.0
    for n1 in range(L_side):
        for n2 in range(L_side):
            for n3 in range(L_side):
                if n1 == 0 and n2 == 0 and n3 == 0:
                    continue
                k = (2 * math.pi * n1 / L_side,
                     2 * math.pi * n2 / L_side,
                     2 * math.pi * n3 / L_side)
                kh2 = sum(4.0 * math.sin(0.5 * ki) ** 2 for ki in k)
                if kh2 == 0:
                    continue
                phase = math.cos(k[0]*rx + k[1]*ry + k[2]*rz)
                total += phase / (c * c * kh2)
    return total / (L_side ** 3)


# Use numpy for vectorized speed
def green_table_vectorized(L_side, c=C_LAT, max_dist=12):
    """Faster computation using numpy."""
    L = L_side
    # Build k-vectors (excluding zero mode)
    n = np.arange(L)
    k1, k2, k3 = np.meshgrid(n, n, n, indexing='ij')
    k1f = 2 * np.pi * k1.flatten() / L
    k2f = 2 * np.pi * k2.flatten() / L
    k3f = 2 * np.pi * k3.flatten() / L
    # k_hat^2 = 4 sum sin(k/2)^2
    kh2 = 4 * (np.sin(0.5 * k1f) ** 2 + np.sin(0.5 * k2f) ** 2 + np.sin(0.5 * k3f) ** 2)
    nonzero = kh2 > 1e-14
    kh2 = kh2[nonzero]
    k1f = k1f[nonzero]
    k2f = k2f[nonzero]
    k3f = k3f[nonzero]
    inv_kh2 = 1.0 / (c * c * kh2)
    # For each r in the box, compute G_L(r)
    table = {}
    for rx in range(-max_dist, max_dist + 1):
        for ry in range(-max_dist, max_dist + 1):
            for rz in range(-max_dist, max_dist + 1):
                phase = np.cos(k1f * rx + k2f * ry + k3f * rz)
                table[(rx, ry, rz)] = float(np.sum(phase * inv_kh2)) / (L ** 3)
    return table


# ---------------------------------------------------------------------------
# Per-block analysis on global field
# ---------------------------------------------------------------------------

def field_in_block(block_center, green_table):
    """27-vector of G_L evaluated at (block_center + delta) for delta in
    {-1,0,1}^3, indexed by VOXELS order.
    """
    cx, cy, cz = block_center
    field = np.zeros(N_VOXELS)
    for i, (dx, dy, dz) in enumerate(VOXELS):
        rx, ry, rz = cx + dx, cy + dy, cz + dz
        field[i] = green_table.get((rx, ry, rz), 0.0)
    return field


def slow_mode_energy_fraction(field, basis, L_27):
    """Fraction of |field|^2 carried by the slow mode of the trivial-
    irrep subspace.

    Returns:
        f_slow      = |<v_slow_local, field>|^2 / |field_in_subspace|^2
        d_G          = trivial-irrep dim
        slow_lambda = eigenvalue of slow mode
        f_block      = |field_in_subspace|^2 / |field|^2 (subspace fraction)
    """
    d = basis.shape[1]
    # Project field onto trivial subspace
    field_in_sub = basis.T @ field
    norm_sq_full = np.sum(field ** 2)
    norm_sq_in = np.sum(field_in_sub ** 2)
    f_block = norm_sq_in / norm_sq_full if norm_sq_full > 1e-14 else 0.0

    # Build trivial-subspace Laplacian
    M = basis.T @ L_27 @ basis
    M = 0.5 * (M + M.T)
    eigvals, eigvecs = np.linalg.eigh(M)
    # Slow mode: smallest |lambda|
    slow_idx = int(np.argmin(np.abs(eigvals)))
    slow_lambda = float(eigvals[slow_idx])
    # Project field-in-subspace onto eigenvector
    v_slow = eigvecs[:, slow_idx]
    proj_slow = float(np.dot(v_slow, field_in_sub))
    energy_slow = proj_slow ** 2

    f_slow = energy_slow / norm_sq_in if norm_sq_in > 1e-14 else 0.0
    return f_slow, d, slow_lambda, f_block


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print('=' * 72)
    print('PROOF Phase B: Global field projection onto local slow modes')
    print('FTD-0110 Mechanism alpha — closure attempt')
    print('=' * 72)
    print(f'Global lattice: L = {L_LATTICE},  c_lat = 1/sqrt(3)')
    print()
    print('Computing lattice Poisson Green function G_L(r) on L^3 lattice...')

    green_table = green_table_vectorized(L_LATTICE, max_dist=12)
    G0 = green_table[(0, 0, 0)]
    print(f'  G_L(0)         = {G0:.6f}    (lattice self-energy)')
    print(f'  G_L(1, 0, 0)  = {green_table[(1, 0, 0)]:.6f}')
    print(f'  G_L(2, 0, 0)  = {green_table[(2, 0, 0)]:.6f}')
    print(f'  G_L(1, 1, 0)  = {green_table[(1, 1, 0)]:.6f}')
    print(f'  G_L(1, 1, 1)  = {green_table[(1, 1, 1)]:.6f}')

    L_27 = build_laplacian_27()

    bases = {
        'O_h':  trivial_basis(gen_O_h()),
        'C_4v': trivial_basis(gen_C_4v_x()),
        'C_3v': trivial_basis(gen_C_3v_xyz()),
        'C_2v': trivial_basis(gen_C_2v_xy()),
        'C_s':  trivial_basis(gen_C_s_y()),
        'C_1':  trivial_basis(gen_C_1()),
    }

    # Sample positions for each symmetry type
    test_positions = [
        ('O_h',  (0, 0, 0)),
        ('C_4v', (1, 0, 0)),
        ('C_4v', (2, 0, 0)),
        ('C_4v', (3, 0, 0)),
        ('C_4v', (5, 0, 0)),
        ('C_3v', (1, 1, 1)),
        ('C_3v', (2, 2, 2)),
        ('C_3v', (3, 3, 3)),
        ('C_2v', (1, 1, 0)),
        ('C_2v', (2, 2, 0)),
        ('C_2v', (3, 3, 0)),
        ('C_s',  (1, 2, 0)),
        ('C_s',  (2, 3, 0)),
        ('C_s',  (1, 3, 0)),
        ('C_1',  (1, 2, 3)),
        ('C_1',  (2, 3, 4)),
        ('C_1',  (3, 4, 5)),
    ]

    print()
    print('Per-block slow-mode analysis (global field generated by origin delta):')
    print(f'  {"Sym":>5s} | {"position":>12s} | {"d":>3s} | '
          f'{"|J_block|^2":>12s} | {"f_block":>9s} | {"f_slow":>9s} | '
          f'{"1/sqrt(d)":>10s} | {"ratio":>9s}')
    print('  ' + '-' * 100)

    aggregated = {sym: [] for sym in bases}

    for sym, pos in test_positions:
        basis = bases[sym]
        field = field_in_block(pos, green_table)
        norm_sq_full = float(np.sum(field ** 2))
        f_slow, d, slow_lam, f_block = slow_mode_energy_fraction(field, basis, L_27)
        invsqrtd = 1.0 / math.sqrt(d)
        # Compare f_slow * f_block (slow mode energy / total block energy) to 1/sqrt(d)
        prod = f_slow * f_block
        ratio = f_slow / invsqrtd if invsqrtd > 0 else 0.0
        aggregated[sym].append((f_slow, f_block, prod))
        print(f'  {sym:>5s} | {str(pos):>12s} | {d:>3d} | '
              f'{norm_sq_full:>12.4e} | {f_block:>9.4f} | {f_slow:>9.4f} | '
              f'{invsqrtd:>10.4f} | {ratio:>9.4f}')

    print()
    print('SYMMETRY-AVERAGED RESULTS:')
    print(f'  {"Sym":>5s} | {"d":>3s} | {"<f_slow>":>9s} | {"<f_block>":>10s} | '
          f'{"<prod>":>9s} | {"1/sqrt(d)":>10s}')
    for sym, basis in bases.items():
        d = basis.shape[1]
        if not aggregated[sym]:
            continue
        f_slow_avg = np.mean([x[0] for x in aggregated[sym]])
        f_block_avg = np.mean([x[1] for x in aggregated[sym]])
        prod_avg = np.mean([x[2] for x in aggregated[sym]])
        print(f'  {sym:>5s} | {d:>3d} | {f_slow_avg:>9.4f} | {f_block_avg:>10.4f} | '
              f'{prod_avg:>9.4f} | {1/math.sqrt(d):>10.4f}')

    print()
    print('INTERPRETATION:')
    print('  f_slow      = fraction of in-subspace block energy on the slow mode')
    print('  f_block     = fraction of total block energy in the trivial subspace')
    print('  prod = f_slow * f_block = fraction of total block energy on slow mode')
    print()
    print('  If Mechanism alpha gives 1/sqrt(d) law, expect <prod> ~ 1/sqrt(d) per sym.')
    print('  If <prod> is uniform across symmetries, alpha is FALSIFIED.')


if __name__ == '__main__':
    main()
