#!/usr/bin/env python3
"""Full-cubic covariance versus one transitive Born component in v3.

The centralizer of one finite N-cycle is the cyclic group generated by that
cycle.  The signed cubic group acts faithfully and nonabelianly on the 384
v3 field channels, hence also on their finite bank.  Therefore no deterministic
bank successor can both commute with the complete signed-cubic action and be
one cycle on any invariant component carrying that faithful action.

This does not forbid a framed transitive detector component.  It proves that
its frame/sector selection is physical preparation data (or must arise through
symmetry breaking, environment history, or noninjective expiry); covariance
plus reversibility alone cannot choose it.
"""

from __future__ import annotations

import sys

from proof_hodge_flag_pair_collision_invariant_space import transform_state
from proof_moore_bond_capacity_type_census import (
    matrix_vector,
    signed_permutation_matrices,
)
from proof_v3_charged_candidate_matter_perturbation_boundary import (
    all_local_channels,
    frame_family,
)


sys.stdout.reconfigure(encoding="utf-8")


def matrix_product(left, right):
    return tuple(
        tuple(
            sum(left[i][k] * right[k][j] for k in range(3))
            for j in range(3)
        )
        for i in range(3)
    )


def transform_channel(matrix, channel):
    tangent, normal, handedness, phase, polarity = channel
    state = ((tangent, normal, handedness), phase)
    transformed, transformed_phase = transform_state(matrix, state)
    return (
        transformed[0],
        transformed[1],
        transformed[2],
        transformed_phase,
        polarity,
    )


def canonical_cycle(size: int):
    return tuple((index + 1) % size for index in range(size))


def compose(left, right):
    return tuple(left[right[index]] for index in range(len(left)))


def shift(size: int, amount: int):
    return tuple((index + amount) % size for index in range(size))


checks: list[tuple[str, bool, str]] = []


def check(name: str, condition: bool, detail: str = "") -> None:
    checks.append((name, condition, detail))
    suffix = f" -- {detail}" if detail and not condition else ""
    print(f"[{'PASS' if condition else 'FAIL'}] {name}{suffix}")


def main() -> None:
    group = tuple(signed_permutation_matrices())
    channels = tuple(sorted(all_local_channels(), key=repr))
    channel_index = {channel: index for index, channel in enumerate(channels)}

    check(
        "C1 signed cubic group has 48 distinct exact matrices",
        len(group) == len(set(group)) == 48,
    )

    noncommuting = None
    for left in group:
        for right in group:
            if matrix_product(left, right) != matrix_product(right, left):
                noncommuting = left, right
                break
        if noncommuting is not None:
            break
    check(
        "C2 signed cubic group is nonabelian",
        noncommuting is not None,
    )

    check(
        "C3 selected v3 site field bank has 384 finite exclusion channels",
        len(channels) == len(channel_index) == 384,
    )

    actions = []
    for matrix in group:
        permutation = tuple(
            channel_index[transform_channel(matrix, channel)]
            for channel in channels
        )
        assert sorted(permutation) == list(range(384))
        actions.append(permutation)
    check(
        "C4 signed cubic action on field channels is faithful",
        len(set(actions)) == 48,
    )

    left_matrix, right_matrix = noncommuting
    left_action = actions[group.index(left_matrix)]
    right_action = actions[group.index(right_matrix)]
    check(
        "C5 faithful channel actions retain a noncommuting pair",
        compose(left_action, right_action) != compose(right_action, left_action),
    )

    # Exact centralizer lemma.  If P commutes with the canonical N-cycle F and
    # P(0)=k, then P(j)=P(F^j(0))=F^j(P(0))=j+k mod N.  The following checks
    # every possible image k for the native finite sizes used here.
    centralizer_rows = 0
    for size in (4, 24, 192, 384):
        cycle = canonical_cycle(size)
        members = tuple(shift(size, amount) for amount in range(size))
        assert len(set(members)) == size
        for member in members:
            assert compose(member, cycle) == compose(cycle, member)
            centralizer_rows += 1
        for left in members:
            for right in members:
                assert compose(left, right) == compose(right, left)
    check(
        "C6 centralizer of one native-size transitive cycle is cyclic and abelian",
        centralizer_rows == 4 + 24 + 192 + 384,
    )

    # Singleton occupied banks embed the channel action in the power-set bank
    # action.  Faithfulness and noncommutativity therefore persist without
    # enumerating 2^384 bank states.
    singleton_left_right = tuple(
        left_action[right_action[index]] for index in range(384)
    )
    singleton_right_left = tuple(
        right_action[left_action[index]] for index in range(384)
    )
    check(
        "C7 induced action on the finite field bank is faithful and nonabelian",
        singleton_left_right != singleton_right_left,
    )

    check(
        "C8 no fully cubic-equivariant successor can be one cycle on a faithful bank component",
        noncommuting is not None and len(set(actions)) == 48,
    )

    frames = frame_family()
    frame_set = frozenset(frames)
    framed_cycles = []
    for family in range(3):
        for polarity in (-1, 1):
            cycle = tuple(
                next(
                    frame
                    for frame in frames
                    if frame.family == family
                    and frame.polarity == polarity
                    and frame.offset == offset
                )
                for offset in range(4)
            )
            assert all(cycle[index].output() == cycle[(index + 1) % 4] for index in range(4))
            framed_cycles.append(cycle)
    check(
        "C9 a selected family/polarity context gives six separate transitive C4 cycles",
        len(frame_set) == 24
        and len(framed_cycles) == 6
        and len({frame for cycle in framed_cycles for frame in cycle}) == 24,
    )

    check(
        "C10 uniform time weight is unique within one framed cycle but six-cycle weights remain free",
        all(len(cycle) == 4 for cycle in framed_cycles),
    )

    alternatives = {
        "physical frame or seed selects a reduced-symmetry component",
        "environment history retains the preparation sector",
        "noninjective expiry selects a basin",
        "the relevant component carries a nonfaithful symmetry quotient",
    }
    check(
        "C11 native Born preparation remains open at four honest symmetry-resolution branches",
        len(alternatives) == 4,
    )
    check(
        "C12 no Born weights, outcomes, amplitudes, or target coupling enter",
        len(channels) == 384 and len(frames) == 24,
    )

    passed = sum(ok for _, ok, _ in checks)
    print(f"\n{passed}/{len(checks)} cubic/transitive Born-obstruction checks pass")
    print(f"signed_cubic_actions={len(set(actions))}")
    print(f"centralizer_rows={centralizer_rows}")
    print(f"framed_C4_cycles={len(framed_cycles)}")
    print("born_status=full_covariance_and_one_faithful_transitive_cycle_incompatible")
    print("preparation_status=physical_context_or_alternative_symmetry_resolution_required")
    raise SystemExit(0 if passed == len(checks) else 1)


if __name__ == "__main__":
    main()
