"""Fixed-curve CM realization operator certificate.

Run with:
  wsl -d Ubuntu-22.04 sage scripts/proofs/proof_cm_realization_operator.sage

The curve, differential normalization, prime ranges, and newform are locked by
PREREG_NATIVE_PHASE_ACTION_CM_OPERATOR_v1.md protocol v1.2.  This is not a
search over curves, conductors, discriminants, or prime subsets.
"""


# This file was *autogenerated* from the file scripts/proofs/proof_cm_realization_operator.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_32 = Integer(32); _sage_const_1728 = Integer(1728); _sage_const_64 = Integer(64); _sage_const_200 = Integer(200); _sage_const_45 = Integer(45); _sage_const_190 = Integer(190); _sage_const_170 = Integer(170); _sage_const_185 = Integer(185); _sage_const_100 = Integer(100); _sage_const_201 = Integer(201)
from pathlib import Path
import hashlib


ROOT = Path(__file__).resolve().parents[_sage_const_2 ]
PROTOCOL = (
    ROOT
    / "docs/theory/10_eft_program/preregistrations/"
    "native_time_carrier_programme/PREREG_NATIVE_PHASE_ACTION_CM_OPERATOR_v1.md"
)
PROTOCOL_SHA256 = "8BE09323F54424C51EA96B2589D532559CC54C4656DE39DEE0626DD6C5EC09F5"


class Certificate:
    def __init__(self):
        self.count = _sage_const_0 

    def check(self, name, condition):
        if not bool(condition):
            raise AssertionError(name)
        self.count += _sage_const_1 
        print(f"[PASS {self.count:02d}] {name}")


def protocol_prefix_hash(path):
    raw = path.read_bytes()
    at = raw.index(b"`protocol_sha256=")
    return hashlib.sha256(raw[:at]).hexdigest().upper()


def manual_point_count(p):
    # #E(F_p)=1+sum_x(1+Legendre(x^3-x,p)); the leading 1 is infinity.
    return _sage_const_1  + sum(_sage_const_1  + kronecker_symbol((x**_sage_const_3  - x) % p, p) for x in range(p))


def primary_gaussian_trace(p):
    """Trace pi+conjugate(pi) for the conductor-32 primary convention.

    For p=1 mod 4 choose pi=u+i*v with u odd, v even, and u+v=1 mod 4.
    Conjugation may leave two values of v, but the real part and trace are
    unique.  No quadrant is selected from a target trace.
    """
    bound = floor(sqrt(p))
    traces = set()
    for u in range(-bound, bound + _sage_const_1 ):
        for v in range(-bound, bound + _sage_const_1 ):
            if u*u + v*v != p:
                continue
            if u % _sage_const_2  == _sage_const_0  or v % _sage_const_2  != _sage_const_0 :
                continue
            if (u + v - _sage_const_1 ) % _sage_const_4  == _sage_const_0 :
                traces.add(_sage_const_2 *u)
    if len(traces) != _sage_const_1 :
        raise AssertionError(f"primary trace not unique at p={p}: {traces}")
    return traces.pop()


def hecke_coefficients(E, limit):
    """Generate a_n from fixed local Euler factors, including bad p=2."""
    coeff = [ZZ(_sage_const_0 )] * limit
    coeff[_sage_const_1 ] = ZZ(_sage_const_1 )
    for n in range(_sage_const_2 , limit):
        fac = factor(n)
        value = ZZ(_sage_const_1 )
        for p, exponent in fac:
            p = ZZ(p)
            if p == _sage_const_2 :
                # Additive reduction: local factor is 1, so a_(2^r)=0.
                value = ZZ(_sage_const_0 )
                break
            a0 = ZZ(_sage_const_1 )
            a1 = ZZ(E.ap(p))
            if exponent == _sage_const_1 :
                power_coeff = a1
            else:
                prev2, prev1 = a0, a1
                for _ in range(_sage_const_2 , exponent + _sage_const_1 ):
                    current = E.ap(p) * prev1 - p * prev2
                    prev2, prev1 = prev1, current
                power_coeff = prev1
            value *= power_coeff
        coeff[n] = value
    return coeff


def eta_product_coefficients(limit):
    """q-product eta(4 tau)^2 eta(8 tau)^2 through q^(limit-1)."""
    PS = PowerSeriesRing(QQ, "q", default_prec=limit)
    q = PS.gen()
    product = q
    for n in range(_sage_const_1 , (limit - _sage_const_1 )//_sage_const_4  + _sage_const_1 ):
        product *= (_sage_const_1  - q**(_sage_const_4 *n))**_sage_const_2 
    for n in range(_sage_const_1 , (limit - _sage_const_1 )//_sage_const_8  + _sage_const_1 ):
        product *= (_sage_const_1  - q**(_sage_const_8 *n))**_sage_const_2 
    return [ZZ(product[n]) for n in range(limit)]


def sym2_polynomial(trace, determinant, X):
    return (
        X**_sage_const_3 
        - (trace**_sage_const_2  - determinant) * X**_sage_const_2 
        + determinant * (trace**_sage_const_2  - determinant) * X
        - determinant**_sage_const_3 
    )


def main():
    cert = Certificate()
    print("CM realization operator fixed-curve certificate")
    print(f"protocol={PROTOCOL_SHA256}")
    cert.check("protocol v1.2 prefix hash", protocol_prefix_hash(PROTOCOL) == PROTOCOL_SHA256)

    E = EllipticCurve(QQ, [_sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_1 , _sage_const_0 ])
    cert.check("fixed curve is y^2=x^3-x", E.ainvs() == (_sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_1 , _sage_const_0 ))
    cert.check("Cremona label is 32a2", E.cremona_label() == "32a2")
    cert.check("conductor is 32", E.conductor() == _sage_const_32 )
    cert.check("j invariant is 1728", E.j_invariant() == _sage_const_1728 )
    cert.check("minimal discriminant is 64", E.discriminant() == _sage_const_64 )
    cert.check("rank is zero", E.rank() == _sage_const_0 )
    cert.check("torsion is Z/2 + Z/2", tuple(E.torsion_subgroup().invariants()) == (_sage_const_2 , _sage_const_2 ))
    cert.check("E(R) has two components", E.real_components() == _sage_const_2 )
    cert.check("p=2 reduction is additive Kodaira III", str(E.local_data(_sage_const_2 ).kodaira_symbol()) == "III")
    cert.check("p=2 Tamagawa number is 2", E.local_data(_sage_const_2 ).tamagawa_number() == _sage_const_2 )
    cert.check("Tamagawa product is 2", E.tamagawa_product() == _sage_const_2 )
    cert.check("analytic Sha order is 1", E.sha().an() == _sage_const_1 )

    # Archimedean realization in the Neron differential dx/(2y).
    RF = RealField(_sage_const_200 )
    gamma14 = RF(_sage_const_1 /_sage_const_4 ).gamma()
    pi_rf = RF.pi()
    K = gamma14**_sage_const_2  / (_sage_const_4  * sqrt(pi_rf))
    varpi = gamma14**_sage_const_2  / (_sage_const_2  * sqrt(_sage_const_2  * pi_rf))
    gstar = _sage_const_2  * varpi / sqrt(pi_rf)
    sage_period = RF(E.period_lattice().real_period())
    cert.check("least real period equals the lemniscatic varpi",
               abs(sage_period - varpi) / varpi < RF(_sage_const_2 )**-_sage_const_45 )
    cert.check("varpi=sqrt(2) K(1/sqrt(2)) normalization",
               abs(varpi - RF(_sage_const_2 ).sqrt()*K) < RF(_sage_const_2 )**-_sage_const_190 )
    cert.check("G*=2 varpi/sqrt(pi)", abs(gstar - _sage_const_2 *varpi/sqrt(pi_rf)) < RF(_sage_const_2 )**-_sage_const_190 )

    # Full BSD real volume: two components times the least real period.
    bsd_from_invariants = (_sage_const_2  * varpi) * E.tamagawa_product() / E.torsion_order()**_sage_const_2 
    cert.check("BSD invariant quotient is varpi/4", abs(bsd_from_invariants - varpi/_sage_const_4 ) < RF(_sage_const_2 )**-_sage_const_190 )
    L1 = RF(E.lseries().dokchitser(prec=_sage_const_200 )(_sage_const_1 ).real())
    cert.check("analytic L(E,1)=varpi/4", abs(L1 - varpi/_sage_const_4 ) / (varpi/_sage_const_4 ) < RF(_sage_const_2 )**-_sage_const_170 )
    cert.check("archimedean-to-Euler bridge G*=8L(E,1)/sqrt(pi)",
               abs(gstar - _sage_const_8 *L1/sqrt(pi_rf)) / gstar < RF(_sage_const_2 )**-_sage_const_170 )

    # The BCC square naturally sees the 2-twist E^(2), whose least period is K.
    E2 = E.quadratic_twist(_sage_const_2 ).minimal_model()
    cert.check("fixed quadratic twist is y^2=x^3-4x", E2.ainvs() == (_sage_const_0 , _sage_const_0 , _sage_const_0 , -_sage_const_4 , _sage_const_0 ))
    cert.check("2-twist label/conductor is 64a1/64", E2.cremona_label() == "64a1" and E2.conductor() == _sage_const_64 )
    cert.check("2-twist least period is K(1/sqrt(2))",
               abs(RF(E2.period_lattice().real_period()) - K) / K < RF(_sage_const_2 )**-_sage_const_45 )
    bcc_period = (_sage_const_2 *K/pi_rf)**_sage_const_2 
    cert.check("BCC Watson period is G*^2/(2*pi)",
               abs(bcc_period - gstar**_sage_const_2 /(_sage_const_2 *pi_rf)) < RF(_sage_const_2 )**-_sage_const_185 )

    # Finite-prime Frobenius.  The first range and held-out range are fixed,
    # exhaustive ranges rather than selected framework primes.
    prefix = list(prime_range(_sage_const_3 , _sage_const_100 ))
    held_out = list(prime_range(_sage_const_100 , _sage_const_200 ))
    all_primes = prefix + held_out
    cert.check("manual point counts match Sage on prime prefix",
               all(manual_point_count(p) == E.change_ring(GF(p)).cardinality()
                   for p in prefix))
    cert.check("manual point counts match Sage on held-out primes",
               all(manual_point_count(p) == E.change_ring(GF(p)).cardinality()
                   for p in held_out))
    cert.check("inert primes have a_p=0 on both ranges",
               all(E.ap(p) == _sage_const_0  for p in all_primes if p % _sage_const_4  == _sage_const_3 ))
    cert.check("split-prime trace follows the fixed primary Gaussian character",
               all(E.ap(p) == primary_gaussian_trace(p)
                   for p in all_primes if p % _sage_const_4  == _sage_const_1 ))

    PR = PolynomialRing(QQ, "X")
    X = PR.gen()
    frobenius_ok = True
    euler_ok = True
    inert_order4_ok = True
    twist_ok = True
    sym2_twist_ok = True
    inert_sym2_ok = True
    for p in all_primes:
        ap = ZZ(E.ap(p))
        Fp = matrix(QQ, [[_sage_const_0 , -p], [_sage_const_1 , ap]])
        frobenius_ok &= Fp.charpoly("X") == X**_sage_const_2  - ap*X + p
        T = polygen(QQ, "T")
        euler_ok &= (identity_matrix(QQ, _sage_const_2 ) - Fp*T).det() == _sage_const_1  - ap*T + p*T**_sage_const_2 
        if p % _sage_const_4  == _sage_const_3 :
            inert_order4_ok &= Fp**_sage_const_2  == -p*identity_matrix(QQ, _sage_const_2 )
            inert_order4_ok &= Fp**_sage_const_4  == p**_sage_const_2 *identity_matrix(QQ, _sage_const_2 )
        chi2 = kronecker_symbol(_sage_const_2 , p)
        twist_ok &= E2.ap(p) == chi2 * ap
        sym2_twist_ok &= sym2_polynomial(ap, p, X) == sym2_polynomial(chi2*ap, p, X)
        if p % _sage_const_4  == _sage_const_3 :
            inert_sym2_ok &= sym2_polynomial(ap, p, X) == (X-p)*(X+p)**_sage_const_2 
    cert.check("Frobenius companion has T^2-a_p*T+p", frobenius_ok)
    cert.check("det(I-F_p*T) gives the local Euler polynomial", euler_ok)
    cert.check("inert Frobenius obeys F_p^2=-pI and normalized order four", inert_order4_ok)
    cert.check("quadratic-twist traces differ by the fixed (2/p) character", twist_ok)
    cert.check("Sym^2 Frobenius polynomial is exactly twist-blind", sym2_twist_ok)
    cert.check("inert Sym^2 polynomial is (X-p)(X+p)^2", inert_sym2_ok)

    # One fixed newform: eta(4 tau)^2 eta(8 tau)^2.  Its coefficients must
    # agree both with the curve and with the local-factor recurrence.
    limit = _sage_const_201 
    qform = E.q_eigenform(limit)
    curve_coeff = [ZZ(qform[n]) for n in range(limit)]
    eta_coeff = eta_product_coefficients(limit)
    hecke_coeff = hecke_coefficients(E, limit)
    cert.check("newform is eta(4*tau)^2 eta(8*tau)^2 through q^200",
               curve_coeff == eta_coeff)
    cert.check("newform coefficients obey all fixed Hecke/Euler recurrences through n=200",
               curve_coeff[_sage_const_1 :] == hecke_coeff[_sage_const_1 :])
    cert.check("bad-prime local factor is 1 (all even coefficients vanish)",
               all(curve_coeff[n] == _sage_const_0  for n in range(_sage_const_2 , limit, _sage_const_2 )))

    print(f"\nPASS {cert.count}/{cert.count}")
    print("Genuine operator: the compatible H^1(E) Hecke/Frobenius system.")
    print("Boundary: BCC supplies Sym^2 H^1 and is blind to the quadratic-twist")
    print("and rank-two orientation needed to choose this lift.")
    return _sage_const_0 


main()

