#!/usr/bin/env python3
"""Exact layer-covariant collision for the global-C3 cotangent carrier.

At cotangent layer q=0 the Hodge flag reads E=d and B=n.  This certificate
constructs one fixed-point-free pair involution preserving those six totals
and commuting with O_h and the C4 phase return U^3.  The q=2 and q=1
collisions are then generated by conjugating with one and two internal ticks.

The resulting three-collision family is a single global-clock-indexed rule:

    U C_q = C_(q-1) U.

Every layer has exactly seven additive invariants (record number plus E and B)
and an exact negative-semidefinite product-reference correction of rank 185.
No fitted coefficient, target spectrum, or measured quantity is used.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from itertools import combinations

from sympy import Matrix
from sympy.polys.matrices import DomainMatrix

from proof_global_c3_cotangent_layer_hodge_maxwell_target import (
    internal_tick,
    layer_value,
)
from proof_hodge_flag_pair_collision_invariant_space import add, one_particle_states
from proof_moore_bond_capacity_type_census import signed_permutation_matrices
from proof_shared_edge_hodge_flag_bcc_propagation import transform_flag


Pair = tuple[int, int]
CERTIFICATE_DATA = None


def canonical_pair(left: int, right: int) -> Pair:
    assert left != right
    return (left, right) if left < right else (right, left)


def exact_rank(matrix: Matrix) -> int:
    return DomainMatrix.from_Matrix(matrix).rank()


def main() -> None:
    global CERTIFICATE_DATA
    checks = 0
    states = one_particle_states()
    state_index = {state: index for index, state in enumerate(states)}
    size = len(states)
    assert size == 192
    checks += 1

    spatial_group = tuple(signed_permutation_matrices())
    spatial_actions = tuple(
        tuple(
            state_index[(transform_flag(matrix, state[0]), state[1])]
            for state in states
        )
        for matrix in spatial_group
    )
    phase_actions = tuple(
        tuple(
            state_index[(state[0], (state[1] + phase_shift) % 4)]
            for state in states
        )
        for phase_shift in range(4)
    )
    actions = tuple(
        tuple(phase[spatial[index]] for index in range(size))
        for spatial in spatial_actions
        for phase in phase_actions
    )
    assert len(actions) == 192
    assert len(set(actions)) == 192
    assert all(len(set(action)) == size for action in actions)
    checks += 3

    pairs = tuple(combinations(range(size), 2))
    pair_set = set(pairs)

    def transform_pair(action, pair: Pair) -> Pair:
        return canonical_pair(action[pair[0]], action[pair[1]])

    field_keys = tuple(layer_value(state, 0) for state in states)

    def pair_field(pair: Pair):
        return add(field_keys[pair[0]], field_keys[pair[1]])

    sectors: defaultdict[tuple[int, ...], list[Pair]] = defaultdict(list)
    for pair in pairs:
        sectors[pair_field(pair)].append(pair)
    sector_histogram = Counter(map(len, sectors.values()))
    assert sum(map(len, sectors.values())) == len(pairs)
    checks += 1

    # The complete relation supplies the target upper rank before any
    # deterministic orbit map is selected.
    complete_rows = []
    for sector in sectors.values():
        reference = sector[0]
        for candidate in sector[1:]:
            row = [0] * size
            for index in candidate:
                row[index] += 1
            for index in reference:
                row[index] -= 1
            complete_rows.append(row)
    complete_rank = exact_rank(Matrix(complete_rows))
    complete_nullity = size - complete_rank
    assert complete_rank == 185
    assert complete_nullity == 7
    checks += 2

    orbit_id: dict[Pair, int] = {}
    representatives: list[Pair] = []
    orbits: list[tuple[Pair, ...]] = []
    unseen = set(pairs)
    while unseen:
        seed = min(unseen)
        orbit = tuple(sorted({transform_pair(action, seed) for action in actions}))
        identifier = len(orbits)
        for pair in orbit:
            assert pair in unseen
            orbit_id[pair] = identifier
            unseen.remove(pair)
        representatives.append(orbit[0])
        orbits.append(orbit)
    orbit_histogram = Counter(map(len, orbits))
    assert sum(map(len, orbits)) == len(pairs)
    checks += 1

    stabilizers = []
    for identifier, representative in enumerate(representatives):
        stabilizer = tuple(
            action_index
            for action_index, action in enumerate(actions)
            if transform_pair(action, representative) == representative
        )
        assert len(stabilizer) * len(orbits[identifier]) == len(actions)
        stabilizers.append(stabilizer)
        checks += 1

    self_options: defaultdict[int, list[Pair]] = defaultdict(list)
    distinct_edges = set()
    for identifier, representative in enumerate(representatives):
        stabilizer = stabilizers[identifier]
        for candidate in sectors[pair_field(representative)]:
            if candidate == representative:
                continue
            if not all(
                transform_pair(actions[action_index], candidate) == candidate
                for action_index in stabilizer
            ):
                continue
            candidate_stabilizer_size = sum(
                transform_pair(action, candidate) == candidate for action in actions
            )
            if candidate_stabilizer_size != len(stabilizer):
                continue
            target_identifier = orbit_id[candidate]
            if target_identifier == identifier:
                if any(
                    transform_pair(action, representative) == candidate
                    and transform_pair(action, candidate) == representative
                    for action in actions
                ) and candidate not in self_options[identifier]:
                    self_options[identifier].append(candidate)
            else:
                distinct_edges.add(tuple(sorted((identifier, target_identifier))))

    print(f"field_sectors={len(sectors)}, histogram={sorted(sector_histogram.items())}")
    print(f"complete_relation_rank={complete_rank}, nullity={complete_nullity}")
    print(f"pair_orbits={len(orbits)}, orbit_histogram={sorted(orbit_histogram.items())}")
    print(f"self_matchable_orbits={len(self_options)}/{len(orbits)}")
    print(f"self_option_histogram={sorted(Counter(map(len, self_options.values())).items())}")
    print(f"distinct_compatible_edges={len(distinct_edges)}")
    assert len(self_options) == len(orbits)
    checks += 1

    def option_transitions(identifier: int, candidate: Pair):
        source_rep = representatives[identifier]
        mapping = {}
        for action in actions:
            source = transform_pair(action, source_rep)
            output = transform_pair(action, candidate)
            if source in mapping:
                assert mapping[source] == output
            mapping[source] = output
        assert set(mapping) == set(orbits[identifier])
        return tuple(sorted(mapping.items()))

    def option_rows(identifier: int, candidate: Pair):
        rows = []
        for source, output in option_transitions(identifier, candidate):
            row = [0] * size
            for index in output:
                row[index] += 1
            for index in source:
                row[index] -= 1
            rows.append(row)
        return tuple(rows)

    prime = 1_000_003

    def reduced_add(basis: dict[int, tuple[int, ...]], row) -> bool:
        vector = [int(entry) % prime for entry in row]
        for pivot in sorted(basis):
            if vector[pivot] == 0:
                continue
            factor = vector[pivot]
            vector = [
                (entry - factor * basis_entry) % prime
                for entry, basis_entry in zip(vector, basis[pivot])
            ]
        pivot = next((index for index, entry in enumerate(vector) if entry), None)
        if pivot is None:
            return False
        inverse = pow(vector[pivot], prime - 2, prime)
        basis[pivot] = tuple(entry * inverse % prime for entry in vector)
        return True

    option_cache = {
        (identifier, candidate): option_rows(identifier, candidate)
        for identifier, candidates in self_options.items()
        for candidate in candidates
    }
    modular_basis: dict[int, tuple[int, ...]] = {}
    chosen_self: dict[int, Pair] = {}
    gain_histogram = Counter()
    processing_order = sorted(
        range(len(orbits)),
        key=lambda identifier: (len(self_options[identifier]), identifier),
    )
    for identifier in processing_order:
        best_candidate = None
        best_basis = None
        best_gain = -1
        for candidate in sorted(self_options[identifier]):
            trial_basis = dict(modular_basis)
            old_rank = len(trial_basis)
            for row in option_cache[(identifier, candidate)]:
                reduced_add(trial_basis, row)
            gain = len(trial_basis) - old_rank
            if gain > best_gain:
                best_candidate = candidate
                best_basis = trial_basis
                best_gain = gain
        assert best_candidate is not None and best_basis is not None
        chosen_self[identifier] = best_candidate
        modular_basis = best_basis
        gain_histogram[best_gain] += 1

    print(f"rank_greedy_modular_rank={len(modular_basis)}")
    print(f"rank_greedy_gain_histogram={sorted(gain_histogram.items())}")

    base_collision: dict[Pair, Pair] = {}

    def install_orbit_map(source_rep: Pair, target: Pair) -> None:
        for action in actions:
            source = transform_pair(action, source_rep)
            output = transform_pair(action, target)
            if source in base_collision:
                assert base_collision[source] == output
            base_collision[source] = output

    for identifier, candidate in chosen_self.items():
        install_orbit_map(representatives[identifier], candidate)

    assert set(base_collision) == pair_set
    assert set(base_collision.values()) == pair_set
    assert all(base_collision[base_collision[pair]] == pair for pair in pairs)
    assert all(base_collision[pair] != pair for pair in pairs)
    checks += 4

    generator_matrices = (
        ((0, 1, 0), (1, 0, 0), (0, 0, 1)),
        ((0, 1, 0), (0, 0, 1), (1, 0, 0)),
        ((-1, 0, 0), (0, 1, 0), (0, 0, 1)),
    )
    generator_actions = [
        tuple(
            state_index[(transform_flag(matrix, state[0]), state[1])]
            for state in states
        )
        for matrix in generator_matrices
    ] + [phase_actions[1]]
    for pair in pairs:
        outgoing = base_collision[pair]
        assert pair_field(outgoing) == pair_field(pair)
        for action in generator_actions:
            assert base_collision[transform_pair(action, pair)] == transform_pair(
                action, outgoing
            )
            checks += 1

    selected_rows = []
    for pair in pairs:
        outgoing = base_collision[pair]
        row = [0] * size
        for index in outgoing:
            row[index] += 1
        for index in pair:
            row[index] -= 1
        selected_rows.append(row)
    selected_rank = exact_rank(Matrix(selected_rows))
    selected_nullity = size - selected_rank
    print(f"selected_transition_rank={selected_rank}, nullity={selected_nullity}")

    # Global clock conjugation.  One internal tick U advances the flag/C4
    # state and sends layer q to q-1.  Because C_0 commutes with U^3, the
    # conjugated family closes after exactly three layers.
    internal_action = tuple(state_index[internal_tick(state)] for state in states)
    inverse_internal = [0] * size
    for source, target in enumerate(internal_action):
        inverse_internal[target] = source

    def action_power(action, exponent: int):
        result = tuple(range(size))
        for _ in range(exponent):
            result = tuple(action[index] for index in result)
        return result

    internal_powers = tuple(action_power(internal_action, exponent) for exponent in range(3))
    inverse_powers = tuple(action_power(tuple(inverse_internal), exponent) for exponent in range(3))

    layer_collisions = []
    for layer in range(3):
        exponent = (-layer) % 3
        forward = internal_powers[exponent]
        backward = inverse_powers[exponent]
        collision = {}
        for pair in pairs:
            base_input = transform_pair(backward, pair)
            base_output = base_collision[base_input]
            collision[pair] = transform_pair(forward, base_output)
        layer_collisions.append(collision)

    for layer, collision in enumerate(layer_collisions):
        layer_keys = tuple(layer_value(state, layer) for state in states)

        def current_pair_field(pair: Pair):
            return add(layer_keys[pair[0]], layer_keys[pair[1]])

        assert all(collision[collision[pair]] == pair for pair in pairs)
        assert all(collision[pair] != pair for pair in pairs)
        assert all(current_pair_field(collision[pair]) == current_pair_field(pair) for pair in pairs)
        checks += 3

        next_layer = (layer - 1) % 3
        next_collision = layer_collisions[next_layer]
        for pair in pairs:
            advanced = transform_pair(internal_action, pair)
            assert transform_pair(internal_action, collision[pair]) == next_collision[advanced]
            checks += 1

    assert layer_collisions[0] == base_collision
    checks += 1

    # Exact symmetric product-reference corrections for all three layers.
    corrections = []
    for collision in layer_collisions:
        correction = Matrix.zeros(size, size)
        for before in pairs:
            after = collision[before]
            if before >= after:
                continue
            delta = [0] * size
            for index in after:
                delta[index] += 1
            for index in before:
                delta[index] -= 1
            column = Matrix(delta)
            correction -= 2 * column * column.T
        assert correction == correction.T
        assert exact_rank(correction) == 185
        corrections.append(correction)
        checks += 2

    internal_matrix = Matrix.zeros(size, size)
    for source, target in enumerate(internal_action):
        internal_matrix[target, source] = 1
    for layer in range(3):
        next_layer = (layer - 1) % 3
        assert corrections[next_layer] == (
            internal_matrix * corrections[layer] * internal_matrix.T
        )
        checks += 1

    CERTIFICATE_DATA = {
        "states": states,
        "collisions": tuple(layer_collisions),
        "corrections": tuple(corrections),
        "internal_action": internal_action,
    }

    print(
        "PASS: global-C3 cotangent layer-covariant collision "
        f"({checks} exact checks)"
    )
    print("all three layers: fixed-point-free, involutive, rank185/nullity7")
    print("exact covariance: U C_q = C_(q-1) U")
    print("Open: three-tick finite-k kernel and Gauss/continuity reduction")


if __name__ == "__main__":
    main()
