#!/usr/bin/env python3
"""Exact common-admission clock/Maxwell scaling and half-lensing boundary.

The autonomous ternary-square material clock already admits a binary local
capacity permission g_n: admitted ticks apply its reversible period-eight map
F, while stalled ticks apply identity.  This certificate exhausts finite
permission words and proves X_N=F^(sum g_n)X_0 with a retained inverse.

The same algebra applied to a cotangent Maxwell Floquet step scales its
first-order cone speed by the admitted-tick fraction nu.  If nu=1-a_t U in a
weak capacity depth, shared clock/wave admission gives only the temporal
optical coefficient a_0=a_t and therefore the clock-medium/1911 response.  A
second spatial/Hodge factor 1-a_s U is required for the equal temporal+spatial
response.  This is a conditional common-gate theorem and boundary, not a
derivation of the permission field or a production lensing operator.
"""

from __future__ import annotations

from itertools import product

from sympy import I, Rational, diff, limit, simplify, symbols

from proof_ternary_square_phase_polarity_autonomous_clock import (
    iterate,
    tick,
    valid_owned_states,
)


C_EFF = Rational(1, 6)


def apply_permission_word(state, word):
    for admitted in word:
        if admitted:
            state = tick(state)
    return state


def reverse_permission_word(state, word):
    # tick^8=1 on the valid one-token orbit, so tick^-1=tick^7.  The permission
    # history is retained and read in reverse; no stall/admit bit is erased.
    for admitted in reversed(word):
        if admitted:
            state = iterate(state, 7)
    return state


def verify_finite_permission_histories() -> int:
    checks = 0
    states = valid_owned_states()
    assert len(states) == 16
    checks += 1
    for state in states:
        assert iterate(state, 8) == state
        checks += 1
        for length in range(11):
            for word in product((0, 1), repeat=length):
                admitted = sum(word)
                output = apply_permission_word(state, word)
                assert output == iterate(state, admitted)
                assert reverse_permission_word(output, word) == state
                checks += 2
    return checks


def verify_floquet_scaling() -> int:
    checks = 0
    k, c = symbols("k c", real=True)
    # Any normalized slow Floquet eigenvalue has this first-order form.  The
    # exact derivative of m admitted advances over N global ticks scales the
    # cone coefficient by m/N.
    one_advance = 1 + I * c * k
    for global_ticks in range(1, 17):
        for admitted in range(global_ticks + 1):
            product_eigenvalue = one_advance**admitted
            derivative = diff(product_eigenvalue, k).subs(k, 0)
            effective_coefficient = simplify(
                derivative / (I * global_ticks)
            )
            assert effective_coefficient == Rational(admitted, global_ticks) * c
            assert effective_coefficient.subs(c, C_EFF) == (
                Rational(admitted, global_ticks) * C_EFF
            )
            checks += 2
    return checks


def verify_weak_optical_boundary() -> int:
    checks = 0
    u = symbols("u")
    a_m, a_t, a_s = symbols("a_m a_t a_s", nonzero=True)

    admission = 1 - a_t * u
    spatial_hodge = 1 - a_s * u

    # A common admission gate alone scales both the material clock and the
    # Maxwell cone by admission.  Its optical coefficient is temporal only.
    temporal_index = 1 / admission
    assert limit((temporal_index - 1) / u, u, 0) == a_t
    checks += 1

    # An additional spatial incidence/Hodge response supplies the second
    # coefficient.  It is not generated by the admission identity.
    full_index = 1 / (admission * spatial_hodge)
    assert limit((full_index - 1) / u, u, 0) == a_t + a_s
    checks += 1

    temporal_discriminator = simplify(a_t / a_m)
    full_discriminator = simplify((a_t + a_s) / a_m)
    assert temporal_discriminator.subs(a_t, a_m) == 1
    assert full_discriminator.subs({a_t: a_m, a_s: 0}) == 1
    assert full_discriminator.subs({a_t: a_m, a_s: a_m}) == 2
    checks += 3

    # Spatial response is independent of the admission theorem.
    assert diff(full_discriminator, a_s) == 1 / a_m
    assert diff(temporal_discriminator, a_s) == 0
    checks += 2
    return checks


def main() -> None:
    checks = verify_finite_permission_histories()
    checks += verify_floquet_scaling()
    checks += verify_weak_optical_boundary()

    print("all finite permission histories: X_N=F^(sum g_n)X_0 with retained inverse")
    print("common admission fraction nu scales clock rate and Maxwell speed nu/6")
    print("nu=1-a_t U gives temporal optical response a_0=a_t")
    print("admission only gives class 1 when a_t=a_m, not equal-response class 2")
    print("second half requires independent spatial/Hodge coefficient a_s=a_m")
    print(
        "PASS: common-admission clock/Maxwell half-lensing boundary "
        f"({checks} exact checks)"
    )
    print(
        "Open: native generation of g_n(U), spatial Hodge transaction, "
        "inhomogeneous interfaces, static pole, and blind lensing fixture"
    )


if __name__ == "__main__":
    main()
