"""
proof_valuation_4gstar.py -- checkable algebra for FTD-0353, the valuation theorem
at the prime (4G*-1) (THEOREM_VALUATION_4GSTAR_MINUS_1.md).

Statement being verified (conditional on Chudnovsky 1976 throughout):

  Model F = Q(G*, pi) ~ Q(t, u) (t -> G*, u -> pi; the repaired FTD-0244 Lemma 2
  step (1)).  Let v = v_{(4t-1)} be the discrete valuation of Q(u)(t) at the
  prime (4t-1).  Then:

  T1 (F-level, the E2 core): every class in the subgroup H of F^x/(F^x)^2
     generated by { [q] : q in Q^x } u { [t], [u] } has EVEN v; since
     v(t(4t-1)) = 1 is odd, [t(4t-1)] is not in H, and by the multiquadratic
     (Kummer) lemma delta = sqrt(G*(4G*-1)) lies in NO one-layer multiquadratic
     extension F(sqrt(h_1), ..., sqrt(h_n)) with classes [h_i] in H.

  T2 (hull level): every documented native analytic output is an algebraic
     multiple of a monomial s^a w^b under s = sqrt(G*), w = pi^(1/4); hence the
     compositum of all documented outputs embeds in the "native period hull"
     N = Qbar(pi^(1/4), sqrt(G*)) ~ Qbar(w, s).  In N the prime (4t-1) SPLITS
     as (2s-1)(2s+1), both unramified; delta^2 = s^2(2s-1)(2s+1) has ODD
     multiplicity at (2s-1), so delta is NOT in N, [N(delta):N] = 2, and the
     Galois swap x_+ <-> x_- is invisible to every element of the hull.

  T3 (radical-tower stability): for every m >= 1, delta is not in
     Qbar(w^(1/m), s^(1/m)) -- adjoining ALL radicals of the native coordinate
     monomials never reaches delta, because the branch locus of delta (the
     fiber 4G*-1 = 0, i.e. s = +-1/2) is disjoint from the coordinate cross
     {0, infinity} where monomial radicals ramify.

  Ramification reading: adjoining delta ramifies EXACTLY the two hull primes
  (2s-1), (2s+1) over (4G*-1) (Newton slope 1/2) and nothing else (mult at (s)
  is 2, even; degree 4 at infinity, even).  Over F both (t) and (4t-1) ramify
  in F(delta); the native sqrt(G*)-line uniformizes (t) (t = s^2) and leaves
  only the (4G*-1)-branch -- FC-W = adopted ramification at (4G*-1).

This script machine-verifies every step that IS checkable:
  A. setup identities: G*, reflection formula, delta, x_pm, hull coordinates
     Gamma(1/4) = s w^2 2^(1/4), Gamma(3/4) = w^2 2^(1/4)/s
  B. inventory membership: each documented native analytic output equals its
     claimed Qbar-monomial in (s, w) at 50+ digits (det_zeta values and ratio,
     Watson G_BCC(0), theta-nulls at tau=i, eta-invariants via Hurwitz zeta,
     AGM(1, sqrt2), lemniscate constant, CM period Omega, L(E,1) hull form)
  C. F-level valuation: t(4t-1) squarefree; v_{(4t-1)} of t, u, 2, rationals
     all 0; randomized even-parity checks on H; v(t(4t-1)) = 1 odd;
     theta-null quadratic layer over F is [2u] (NOT [t] -- E2-sketch fix)
  D. hull split + odd multiplicity: 4t-1 = (2s-1)(2s+1) under t = s^2;
     factor_list(4s^4 - s^2) multiplicities; irreducibility of y^2 - delta^2
     over Q, Q(i), Q(sqrt2), Q(i, 2^(1/4))
  E. ramification data: Newton slopes at (4t-1), (2s-1), (t); evenness at (s)
     and at infinity; e = 2 exactly on the (4G*-1) fiber
  F. radical towers: 4S^(2m) - 1 squarefree and coprime to S for m = 2, 3, 4
  G. corroborations: FTD-0314 C3's ad-hoc prime 4*Gamma(1/4)^2 - sqrt(2)*pi
     equals sqrt(2)*pi*(4G*-1) (same branch locus, different coordinates);
     PSLQ finds no relation delta vs monomials s^a w^b (evidence only, high
     dps per the FTD-0351 spurious-PSLQ lesson)

What is NOT machine-checkable here and stays CONDITIONAL or [SELECTION]:
Chudnovsky 1976 itself; the completeness of the documented inventory (the
FTD-0347 generator-representativeness flag, explicitly inherited); and the
L(E,1) = G*sqrt(pi)/8 value, which is cited from FTD-0314 C3 (only its hull
membership is checked here, not the L-value computation).
"""

import sys
from mpmath import mp, mpf, mpc, gamma, sqrt, pi as mppi, exp, jtheta, zeta, agm, quad, pslq
import sympy as sp

mp.dps = 60
G = gamma(mpf(1)/4) / gamma(mpf(3)/4)
PI = +mppi
S = sqrt(G)                  # s = sqrt(G*)
W = PI ** (mpf(1)/4)         # w = pi^(1/4)
R4 = mpf(2) ** (mpf(1)/4)    # 2^(1/4)
DELTA = sqrt(G * (4*G - 1))
TOL = mpf(10) ** -48

checks = []
def check(name, ok, detail=""):
    checks.append((name, bool(ok)))
    print(("  [PASS] " if ok else "  [FAIL] ") + name + ((" -- " + detail) if detail else ""))

def close(a, b, tol=TOL):
    return abs(a - b) < tol

print("=" * 92)
print("FTD-0353: the valuation theorem at the prime (4G*-1) -- machine-checkable layer")
print("G*    = " + mp.nstr(G, 30))
print("delta = " + mp.nstr(DELTA, 30))
print("=" * 92)

# ---------------------------------------------------------------- A. setup
print("\nA. Setup identities")
check("A1 reflection: G* == Gamma(1/4)^2/(pi sqrt2)",
      close(G, gamma(mpf(1)/4)**2 / (PI*sqrt(mpf(2)))))
x_p = 8*G**2 + 4*G*DELTA
x_m = 8*G**2 - 4*G*DELTA
qp = (16*G**2 + sqrt((16*G**2)**2 - 4*16*G**3)) / 2
qm = (16*G**2 - sqrt((16*G**2)**2 - 4*16*G**3)) / 2
check("A2 x_pm = 8G*^2 +- 4G* delta match quadratic formula", close(x_p, qp) and close(x_m, qm))
check("A3 delta == (x_+ - x_-)/(8G*)  (sole root-distinguishing irrational)",
      close(DELTA, (x_p - x_m)/(8*G)))
check("A4 hull coordinate: Gamma(1/4) == s * w^2 * 2^(1/4)",
      close(gamma(mpf(1)/4), S * W**2 * R4))
check("A5 hull coordinate: Gamma(3/4) == w^2 * 2^(1/4) / s",
      close(gamma(mpf(3)/4), W**2 * R4 / S))
check("A6 F-membership: G* == s^2 and pi == w^4", close(G, S**2) and close(PI, W**4))

# ------------------------------------------------- B. inventory membership
print("\nB. Documented native analytic outputs are Qbar-monomials in (s, w)")
dz14 = sqrt(2*PI)/gamma(mpf(1)/4)     # det_zeta(D_{1/4}) = sqrt(2pi)/Gamma(1/4)  (Lerch, FTD-0234)
dz34 = sqrt(2*PI)/gamma(mpf(3)/4)
check("B1 det_zeta(D_{1/4}) == 2^(1/4) * s^(-1)", close(dz14, R4 / S))
check("B2 det_zeta(D_{3/4}) == 2^(1/4) * s", close(dz34, R4 * S))
check("B3 det_zeta ratio == G* == s^2  (FTD-0234)", close(dz34/dz14, S**2))
watson = G**2 / (2*PI)
check("B4 Watson G_BCC(0) = G*^2/(2pi) == s^4/(2 w^4)  (OT-2.1)",
      close(watson, S**4/(2*W**4)))
check("B5 Watson closed form G*^2/(2pi) == Gamma(1/4)^4/(4 pi^3)",
      close(watson, gamma(mpf(1)/4)**4/(4*PI**3)))
q_nome = exp(-PI)
t3 = jtheta(3, 0, q_nome); t2 = jtheta(2, 0, q_nome); t4 = jtheta(4, 0, q_nome)
check("B6 theta3(0, i) == pi^(1/4)/Gamma(3/4)  (FTD-0341 C2)",
      close(t3, W/gamma(mpf(3)/4), mpf(10)**-40))
check("B7 theta3 == s * 2^(-1/4) * w^(-1)  (hull monomial)",
      close(t3, S/(R4*W), mpf(10)**-40))
check("B8 theta2 == theta4 == s * 2^(-1/2) * w^(-1)  (self-dual point)",
      close(t2, t4, mpf(10)**-40) and close(t4, S/(sqrt(mpf(2))*W), mpf(10)**-40))
check("B9 theta3^2 == G*/sqrt(2 pi)  (the [2u] quadratic layer, sec. C)",
      close(t3**2, G/sqrt(2*PI), mpf(10)**-40))
eta14 = zeta(0, mpf(1)/4) - zeta(0, mpf(3)/4)   # eta(D_a) = zeta_H(0,a) - zeta_H(0,1-a)
eta34 = zeta(0, mpf(3)/4) - zeta(0, mpf(1)/4)
check("B10 eta(D_{1/4}) == +1/2, eta(D_{3/4}) == -1/2  (rational; FTD-0341 C1)",
      close(eta14, mpf(1)/2) and close(eta34, -mpf(1)/2))
check("B11 zeta_H(0, a) == 1/2 - a at a = 1/4, 3/4  (Bernoulli value)",
      close(zeta(0, mpf(1)/4), mpf(1)/4) and close(zeta(0, mpf(3)/4), -mpf(1)/4))
check("B12 AGM(1, sqrt2) == 2 sqrt(pi)/G* == 2 w^2 s^(-2)  (FTD-0327/0341 C4)",
      close(agm(1, sqrt(mpf(2))), 2*W**2/S**2))
check("B13 AGM orientation i*4*sqrt2*G* is in Qbar * s^2 (both conventions: i*4G* too)",
      close(mpc(0, 4*sqrt(mpf(2)))*G, mpc(0, 4*sqrt(mpf(2)))*S**2)
      and close(mpc(0, 4)*G, mpc(0, 4)*S**2))
check("B14 half-derivative outputs {G*, 1/G*} in F; product == 1  (FTD-0341 C3)",
      close(G * (1/G), mpf(1)) and close(G, S**2))
lem = 2*quad(lambda x: 1/sqrt(1 - x**4), [0, 1])
check("B15 lemniscate constant 2*int_0^1 dt/sqrt(1-t^4) == G* sqrt(pi)/2 == s^2 w^2/2",
      close(lem, S**2*W**2/2, mpf(10)**-30))  # endpoint-singular quadrature: ~1e-32 attained
omega = gamma(mpf(1)/4)**2 / sqrt(2*PI)
check("B16 CM period Omega = Gamma(1/4)^2/sqrt(2pi) == s^2 w^2  (FTD-0314 C3)",
      close(omega, S**2*W**2))
check("B17 L(E,1) hull form: G* sqrt(pi)/8 == s^2 w^2/8 (value cited from FTD-0314 C3)",
      close(G*sqrt(PI)/8, S**2*W**2/8))
check("B18 Omega/G* == sqrt(pi) == w^2  (so sqrt(pi) is a native-composite monomial)",
      close(omega/G, W**2))

# ------------------------------------------- C. F-level valuation (sympy)
print("\nC. F-level: the (4t-1)-adic valuation on Q(u)(t)")
t, u, y, ssym, wsym = sp.symbols('t u y s w')
c_poly = sp.expand(t*(4*t - 1))
fl = sp.factor_list(sp.Poly(c_poly, t))
facs = sorted([(sp.expand(f.as_expr()), m) for f, m in fl[1]], key=lambda z: sp.degree(z[0], t))
check("C1 t(4t-1) squarefree: factor_list = (t,1)(4t-1,1)",
      facs == [(t, 1), (sp.expand(4*t - 1), 1)])
check("C2 gcd(c, c') == 1 (squarefree, second route)",
      sp.gcd(sp.Poly(c_poly, t), sp.Poly(sp.diff(c_poly, t), t)).degree() == 0)

def v_4tm1(expr):
    """(4t-1)-adic valuation of a nonzero element of Q(u)(t)."""
    num, den = sp.fraction(sp.together(sp.expand(expr)))
    p = sp.Poly(sp.expand(4*t - 1), t, domain=sp.FractionField(sp.QQ, [u]))
    def mult(poly_expr):
        q = sp.Poly(sp.expand(poly_expr), t, domain=sp.FractionField(sp.QQ, [u]))
        if q.is_zero:
            raise ValueError("zero")
        m = 0
        while True:
            quo, rem = sp.div(q, p)
            if rem.is_zero:
                m += 1
                q = quo
            else:
                return m
    return mult(num) - mult(den)

check("C3 v(t) == 0, v(u) == 0, v(2) == 0, v(3/7) == 0 (all generators are units)",
      v_4tm1(t) == 0 and v_4tm1(u) == 0 and v_4tm1(sp.Integer(2)) == 0
      and v_4tm1(sp.Rational(3, 7)) == 0)
check("C4 v(t(4t-1)) == 1 (odd)", v_4tm1(c_poly) == 1)
check("C5 v(4t-1) == 1 (odd): the value 4G*-1 is native, its square class is not",
      v_4tm1(4*t - 1) == 1)

import random
random.seed(42)
ok_parity = True
for _ in range(20):
    a = random.randint(-2, 2); b = random.randint(-2, 2)
    qq = sp.Rational(random.randint(1, 9), random.randint(1, 9)) * random.choice([1, -1])
    f = (t**random.randint(0, 2) + sp.Rational(random.randint(1, 5))
         + u * sp.Rational(random.randint(0, 3)))
    h = qq * t**a * u**b * f**2
    if v_4tm1(h) % 2 != 0:
        ok_parity = False
        break
check("C6 randomized (seed 42, 20x): v is EVEN on q * t^a * u^b * f^2 for all samples",
      ok_parity)
check("C7 v(t(4t-1) * f^2) is ODD on a sample (class [t(4t-1)] escapes H)",
      v_4tm1(c_poly * (t**2 + u + 3)**2) % 2 == 1)
# E2-sketch correction: the theta-null quadratic layer over F is [2u], not [t]
check("C8 theta3^4 == G*^2/(2 pi) is in F while theta3^2 is not: class algebra "
      "[t^2/(2u)] == [2u] since (t^2/(2u))*(2u) == t^2 is a square",
      sp.simplify((t**2/(2*u))*(2*u) - t**2) == 0
      and close(t3**4, G**2/(2*PI), mpf(10)**-40))
check("C9 v_(u)(t^2/(2u)) == -1 odd (so [2u] is a genuinely nontrivial class over F)",
      sp.degree(sp.fraction(sp.together(t**2/(2*u)))[1], u) == 1)

# --------------------------------------- D. hull split and odd multiplicity
print("\nD. Hull level: t = s^2 splits (4t-1); delta^2 has odd multiplicity")
split = sp.factor(sp.expand((4*t - 1).subs(t, ssym**2)))
check("D1 4t-1 == (2s-1)(2s+1) under t = s^2 (the native sqrt(G*) line SPLITS the prime)",
      sp.expand(split - (2*ssym - 1)*(2*ssym + 1)) == 0)
d2 = sp.expand((t*(4*t - 1)).subs(t, ssym**2))
check("D2 delta^2 == 4s^4 - s^2 == s^2 (2s-1)(2s+1)",
      sp.expand(d2 - (4*ssym**4 - ssym**2)) == 0
      and sp.expand(d2 - ssym**2*(2*ssym - 1)*(2*ssym + 1)) == 0)
fl2 = sp.factor_list(sp.Poly(d2, ssym))
mults = {}
for f, m in fl2[1]:
    mults[sp.expand(f.as_expr())] = m
check("D3 multiplicities: (s)^2 (even), (2s-1)^1 and (2s+1)^1 (both ODD)",
      mults.get(ssym) == 2 and
      (mults.get(2*ssym - 1) == 1 or mults.get(ssym - sp.Rational(1, 2)) == 1) and
      (mults.get(2*ssym + 1) == 1 or mults.get(ssym + sp.Rational(1, 2)) == 1))
p_irr = sp.Poly(y**2 - d2, y, ssym)
check("D4 y^2 - delta^2 irreducible over Q[y, s]",
      len(sp.factor_list(p_irr)[1]) == 1 and sp.factor_list(p_irr)[1][0][1] == 1)
f_i = sp.factor(y**2 - d2, extension=[sp.I])
f_r2 = sp.factor(y**2 - d2, extension=[sp.sqrt(2)])
f_big = sp.factor(y**2 - d2, extension=[sp.I, sp.root(2, 4)])
def still_quadratic_in_y(e):
    fl_ = sp.factor_list(e)
    return len(fl_[1]) == 1 and fl_[1][0][1] == 1 and sp.degree(fl_[1][0][0], y) == 2
check("D5 y^2 - delta^2 stays irreducible over Q(i), Q(sqrt2), Q(i, 2^(1/4))",
      still_quadratic_in_y(f_i) and still_quadratic_in_y(f_r2) and still_quadratic_in_y(f_big))
check("D6 y^2 - t(4t-1) irreducible over Q[y, t, u] (F-level, matches FTD-0244 Lemma 2)",
      len(sp.factor_list(sp.Poly(y**2 - t*(4*t-1), y, t, u))[1]) == 1)
# Galois blindness: Tr and Det are delta-free; delta -> -delta swaps the roots
d_sym = sp.symbols('d')
xp_s = 8*t**2 + 4*t*d_sym
xm_s = 8*t**2 - 4*t*d_sym
check("D7 Tr = x_+ + x_- == 16 t^2 and Det = x_+ x_- == 16 t^3 are delta-free "
      "(using d^2 = t(4t-1)); sigma: d -> -d swaps x_+ <-> x_-",
      sp.expand(xp_s + xm_s - 16*t**2) == 0
      and sp.expand(sp.expand(xp_s*xm_s).subs(d_sym**2, t*(4*t - 1)) - 16*t**3) == 0
      and sp.expand(xp_s.subs(d_sym, -d_sym) - xm_s) == 0)

# ----------------------------------------------------- E. ramification data
print("\nE. Ramification: e = 2 exactly on the (4G*-1) fiber")
tau, sig = sp.symbols('tau sigma')
exp_t = sp.expand((t*(4*t - 1)).subs(t, (1 + tau)/4))
check("E1 Newton slope at (4t-1) over F: delta^2 = tau/4 + tau^2/4, lowest degree 1 => e = 2",
      sp.expand(exp_t - (tau/4 + tau**2/4)) == 0)
exp_s = sp.expand(d2.subs(ssym, sp.Rational(1, 2) + sig))
check("E2 Newton slope at (2s-1) in the hull: lowest sigma-degree 1 => e = 2",
      exp_s.subs(sig, 0) == 0 and sp.diff(exp_s, sig).subs(sig, 0) != 0)
check("E3 at (s): multiplicity 2 (EVEN) => the native line ABSORBS the (t)-ramification",
      mults.get(ssym) == 2)
check("E4 at infinity: deg_s(delta^2) == 4 (EVEN) => unramified at infinity",
      sp.degree(d2, ssym) == 4)
check("E5 over F the prime (t) also ramifies in F(delta): v_(t)(t(4t-1)) == 1 odd "
      "(FTD-0244's route -- dies in the hull, unlike (4t-1))",
      sp.degree(sp.gcd(sp.Poly(c_poly, t), sp.Poly(t, t)), t) == 1
      and mults.get(ssym) == 2)
check("E6 delta^2 has no w-content: unramified along every w-prime",
      sp.simplify(sp.diff(d2, wsym)) == 0)

# -------------------------------------------------------- F. radical towers
print("\nF. Radical-tower stability (Theorem 3)")
Ssym = sp.symbols('S')
ok_rad = True
for m_ in (2, 3, 4):
    poly = sp.Poly(4*Ssym**(2*m_) - 1, Ssym)
    sqfree = sp.gcd(poly, sp.Poly(sp.diff(poly.as_expr(), Ssym), Ssym)).degree() == 0
    coprime = sp.gcd(poly, sp.Poly(Ssym, Ssym)).degree() == 0
    if not (sqfree and coprime):
        ok_rad = False
check("F1 4S^(2m) - 1 squarefree and coprime to S for m = 2, 3, 4: delta^2 = "
      "S^(2m)(4S^(2m)-1) keeps ODD multiplicity at every branch prime under s = S^m",
      ok_rad)
check("F2 sanity m=2: factor multiplicities of S^4(4S^4-1) are {S:4 even; each root of "
      "4S^4-1: 1 odd}",
      all(mm == 1 for ff, mm in sp.factor_list(sp.Poly(4*Ssym**4 - 1, Ssym))[1]))

# --------------------------------------------------------- G. corroborations
print("\nG. Corroborations")
lhs314 = 4*gamma(mpf(1)/4)**2 - sqrt(mpf(2))*PI
rhs314 = sqrt(mpf(2))*PI*(4*G - 1)
check("G1 FTD-0314 C3's prime: 4 Gamma(1/4)^2 - sqrt2 pi == sqrt2 pi (4G*-1) "
      "(same branch locus, (pi, Gamma) coordinates)",
      close(lhs314, rhs314))
check("G2 FTD-0314 C3 numerator identity: surd^2 == (4 Gamma(1/4)^4 - sqrt2 pi Gamma(1/4)^2)/(2 pi^2)",
      close(DELTA**2, (4*gamma(mpf(1)/4)**4 - sqrt(mpf(2))*PI*gamma(mpf(1)/4)**2)/(2*PI**2)))
# PSLQ: delta against hull monomials s^a w^b, 0 <= a, b <= 3. Evidence only, not proof.
# INCIDENT LOG (mirrors the FTD-0351 spurious-PSLQ lesson): at dps=250 with
# maxcoeff=1e12 this 17-element vector yields a SPURIOUS relation whose
# coefficients sit at ~1e11-1e12 (the maxcoeff ceiling) -- 250 digits is
# marginal for 17 elements x 12-digit coefficients. At dps=500, maxcoeff=1e10
# PSLQ correctly returns None. Reproduced 2026-07-02 during this script's
# development; the high-dps run below is the recorded check.
mp.dps = 500
G_hi = gamma(mpf(1)/4)/gamma(mpf(3)/4)
S_hi = sqrt(G_hi); W_hi = mppi ** (mpf(1)/4)
D_hi = sqrt(G_hi*(4*G_hi - 1))
vec = [D_hi] + [S_hi**a * W_hi**b for a in range(4) for b in range(4)]
rel = pslq(vec, maxcoeff=10**10, maxsteps=10**6)
check("G3 PSLQ (dps 500, maxcoeff 1e10): NO integer relation delta vs {s^a w^b} "
      "(corroboration of T2, not a proof; see spurious-PSLQ incident log above)",
      rel is None)
mp.dps = 60

# ------------------------------------------------------------------ summary
n_pass = sum(1 for _, ok in checks if ok)
n_all = len(checks)
print("\n" + "=" * 92)
print("SUMMARY: %d/%d PASS" % (n_pass, n_all))
print("Conditional throughout on Chudnovsky 1976. Inventory completeness is [SELECTION]")
print("and inherits the FTD-0347 generator-representativeness flag. No alpha derived;")
print("x_+ = 1/alpha stays [SMC]; MC-T4.3 stays [FOUNDATIONAL OBSTRUCTION]; FC-W stays adopted.")
print("=" * 92)
sys.exit(0 if n_pass == n_all else 1)
