#!/usr/bin/env python3
"""Exact directional-port coherence-metric and handoff family.

At one port edge there are four records labelled by internal handedness
h=+/- and C4 phase band p/p+2.  Cubic/C4/channel-exchange symmetry permits a
three-parameter normalized quadratic Gram:

    a = cross weight for same phase, opposite h,
    b = cross weight for same h, opposite phase band,
    c = cross weight for both labels opposite.

The standing, outgoing, and separated-free field energies are

    H_S    = (1+a)/2,
    H_O    = (1+a+b+c)/2,
    H_free = (1+b)/2.

Exact port-to-free handoff conservation requires c=-a.  Positive
semidefiniteness then leaves a continuum

    b >= -1,  |2a| <= 1-b.

Hence symmetry, fixed records, E/B covariance, and free streaming do not fix
the phase-coherence weight b or emission work (b-a)/2.  The fully coarse
metric (a,b,c)=(1,1,1) gives the previously observed handoff defect.  The
flag-resolved phase-coherent metric (0,1,0) preserves handoff energy, while the
fully resolved metric (0,0,0) also preserves it but assigns no emission work.

No target coupling or Born weight is used.  The result isolates the field
quadratic-form datum.  The later C4 kernel-separation certificate proves that
this field Gram cannot be identified literally with the raw Born kernel;
one action must derive their distinct sectors and contextual coupling.
"""

from __future__ import annotations

from sympy import Matrix, Rational, simplify, symbols

from proof_c18_equivariant_single_record_collision_no_go import SC_DIRECTIONS
from proof_cotangent_handed_directional_radiation_port import (
    DirectionalPortState,
    local_fields,
    propagation_direction,
)
from proof_oriented_bond_plaquette_hodge_maxwell_target import cross, dot


def gram_matrix(a, b, c) -> Matrix:
    # Channel order: (h+,phase0), (h-,phase0), (h+,phase2), (h-,phase2).
    return Matrix(
        [
            [1, a, b, c],
            [a, 1, c, b],
            [b, c, 1, a],
            [c, b, a, 1],
        ]
    )


def quadratic_energy(vectors, gram) -> object:
    output = 0
    for left_index, left in enumerate(vectors):
        for right_index, right in enumerate(vectors):
            output += gram[left_index, right_index] * dot(left, right)
    return output / 64


def main() -> None:
    checks = 0
    a, b, c = symbols("a b c", real=True)
    gram = gram_matrix(a, b, c)

    # The channel-exchange group is the Klein four generated by swapping
    # handedness and swapping the two C4 phase bands.
    swap_h = Matrix(
        [
            [0, 1, 0, 0],
            [1, 0, 0, 0],
            [0, 0, 0, 1],
            [0, 0, 1, 0],
        ]
    )
    swap_phase = Matrix(
        [
            [0, 0, 1, 0],
            [0, 0, 0, 1],
            [1, 0, 0, 0],
            [0, 1, 0, 0],
        ]
    )
    actions = (
        Matrix.eye(4),
        swap_h,
        swap_phase,
        swap_h * swap_phase,
    )
    assert all(action.T * gram * action == gram for action in actions)
    checks += 1

    characters = (
        Matrix([1, 1, 1, 1]),
        Matrix([1, -1, 1, -1]),
        Matrix([1, 1, -1, -1]),
        Matrix([1, -1, -1, 1]),
    )
    eigenvalues = (
        1 + a + b + c,
        1 - a + b - c,
        1 + a - b - c,
        1 - a - b + c,
    )
    for character, eigenvalue in zip(characters, eigenvalues):
        assert gram * character == eigenvalue * character
        checks += 1

    # One normalized edge. E and B are orthogonal unit directions. The
    # standing mode has v+ on phase0 and v- on phase2; outgoing has v+ in all
    # four channels. The separated mode has only same-h phase pairs co-located.
    electric = (1, 0, 0)
    magnetic = (0, 1, 0)
    plus = electric + magnetic
    minus = electric + tuple(-entry for entry in magnetic)
    standing_vectors = (plus, plus, minus, minus)
    outgoing_vectors = (plus, plus, plus, plus)

    standing_edge = simplify(quadratic_energy(standing_vectors, gram))
    outgoing_edge = simplify(quadratic_energy(outgoing_vectors, gram))
    # Four edges make one port.
    standing = simplify(4 * standing_edge)
    outgoing = simplify(4 * outgoing_edge)
    separated = simplify(Rational(1, 2) * (1 + b))
    assert standing == (1 + a) / 2
    assert outgoing == (1 + a + b + c) / 2
    assert separated == (1 + b) / 2
    emission_work = simplify(outgoing - standing)
    handoff_defect = simplify(outgoing - separated)
    assert emission_work == (b + c) / 2
    assert handoff_defect == (a + c) / 2
    checks += 5

    conserving_c = -a
    conserving_emission = simplify(emission_work.subs(c, conserving_c))
    conserving_eigenvalues = tuple(
        simplify(value.subs(c, conserving_c)) for value in eigenvalues
    )
    assert conserving_emission == (b - a) / 2
    assert conserving_eigenvalues == (
        1 + b,
        1 + b,
        1 + 2 * a - b,
        1 - 2 * a - b,
    )
    checks += 2

    # Exact representative metrics.
    examples = {
        "fully_resolved": (Rational(0), Rational(0), Rational(0)),
        "flag_resolved_phase_coherent": (Rational(0), Rational(1), Rational(0)),
        "interior_handoff_family": (Rational(1, 4), Rational(1, 2), Rational(-1, 4)),
        "fully_coarse": (Rational(1), Rational(1), Rational(1)),
    }
    expected = {
        "fully_resolved": (Rational(1, 2), Rational(1, 2), Rational(1, 2)),
        "flag_resolved_phase_coherent": (Rational(1, 2), Rational(1), Rational(1)),
        "interior_handoff_family": (Rational(5, 8), Rational(3, 4), Rational(3, 4)),
        "fully_coarse": (Rational(1), Rational(2), Rational(1)),
    }
    for name, substitution in examples.items():
        values = {a: substitution[0], b: substitution[1], c: substitution[2]}
        actual = (
            simplify(standing.subs(values)),
            simplify(outgoing.subs(values)),
            simplify(separated.subs(values)),
        )
        assert actual == expected[name]
        eigenvalue_values = tuple(value.subs(values) for value in eigenvalues)
        assert all(value >= 0 for value in eigenvalue_values)
        if name == "fully_coarse":
            assert simplify(handoff_defect.subs(values)) == 1
        else:
            assert simplify(handoff_defect.subs(values)) == 0
        checks += 3

    # Spatial/charge covariance does not reduce the three channel weights:
    # all frames have the same standing/outgoing coarse field geometry.
    frames = tuple(
        (direction, second)
        for direction in SC_DIRECTIONS
        for second in SC_DIRECTIONS
        if dot(direction, second) == 0
    )
    for frame in frames:
        for chirality in (-1, 1):
            propagation = propagation_direction(frame, chirality)
            for orientation in (-1, 1):
                standing_state = DirectionalPortState(
                    frame, chirality, 0, 0, orientation, False, 1
                )
                outgoing_state = DirectionalPortState(
                    frame, chirality, 0, 0, orientation, True, 0
                )
                assert len(local_fields(standing_state)) == len(local_fields(outgoing_state)) == 4
                assert propagation in SC_DIRECTIONS
                checks += 2

    print("invariant four-channel coherence Gram has three weights (a,b,c)")
    print("standing=(1+a)/2, outgoing=(1+a+b+c)/2, free=(1+b)/2")
    print("exact handoff conservation requires c=-a")
    print("PSD handoff family: b>=-1 and |2a|<=1-b")
    print("emission work on that family=(b-a)/2: not symmetry-fixed")
    print("coarse metric (1,1,1) has handoff defect 1")
    print("phase-coherent flag-resolved (0,1,0) and fully resolved (0,0,0) both conserve")
    print("successor: the actual C4-trivial field type uniquely selects (0,1,0)")
    print(
        f"PASS: directional-port coherence-metric handoff family ({checks} exact checks)"
    )
    print(
        "Open: derive the physical field metric from the common action; raw Born "
        "histories occupy an orthogonal C4 sector and require a derived nonlinear "
        "pair conversion or contextual mixer rather than reuse of this Gram"
    )


if __name__ == "__main__":
    main()
