#!/usr/bin/env python3
"""
proof_determinant_grading_parity.py

Closure attempt for the MC-T4.3 *determinant-grading* sub-problem.

Pre-registration : FTD-0217 (provisional)
                   docs/theory/10_eft_program/PREREG_ALPHA_READOUT_DETERMINANT_GRADING_v1.md
                   SHA256 f55c7504401a1e5eb4a61ae18380d10c0ae8a4d407cfb1fc48da45e91918abd7
Verdict supported: CLOSED-NEGATIVE  (pre-reg §6 CLOSED-NEGATIVE: a structural
                   argument that the frozen ingredients generate only a
                   restricted set of G*-degrees that excludes the determinant's)

THE QUESTION (pre-reg §2)
-------------------------
Can a readout operator T, built forward from the FROZEN ingredients
  {V_complex = Z[i]^2 ;  |mu_4|^2 = 16 ;  Watson G_BCC(0) = G*^2/(2pi) ;  winding index},
have determinant  Det(T) = 16 G*^3  (and trace Tr(T) = 16 G*^2) -- i.e. the
master-quadratic grading Det/Tr = G* -- with NO falsifier firing (in particular
NOT F4: no sqrt(Watson) / G*-prefactor selected to supply the odd power)?

THE OBSTRUCTION (G*-degree parity)
----------------------------------
Every frozen ingredient has a definite, EVEN G*-degree:
   |mu_4|^2 = 16 ............ degree 0   (a count)
   winding index ........... degree 0   (an integer)
   J^2 = -I ................ degree 0   (complex structure; det=1, tr=0)
   Watson G_BCC(0)=G*^2/2pi  degree 2
The admissible forward operations (sum, product, Z[i]-norm |z|^2=z zbar,
trace, determinant) ADD or PRESERVE G*-degree; none HALVES it. Hence the
determinant of any operator with entries in the even-degree ring Q[G*^2] is
itself in Q[G*^2] (even powers of G* only). But  16 G*^3  has ODD degree 3.
Because G* = Gamma(1/4)/Gamma(3/4) is transcendental, {1, G*, G*^2, G*^3, ...}
are Q-linearly independent, so  G*^3 is NOT in Q[G*^2].  Therefore no
forward operator over the frozen ring has determinant 16 G*^3.

The unique even -> odd route is a square root: sqrt(Watson) = G*/sqrt(2pi)
(degree 1 -- the field AMPLITUDE rather than the self-ENERGY). Selecting the
amplitude over the energy, with a prefactor tuned to land 8 sqrt(2pi) G*, is
exactly pre-reg falsifier F4 -- and is exactly the "Selection 1" the ARC-C1/B2
resolution docs already ADMIT (FTD-0216 §3 / FTD-0215 §4).

This script verifies the parity facts symbolically (sympy) + numerically
(mpmath/constants.py). It does NOT compare any candidate readout to 1/alpha;
no CODATA value appears (pre-reg banned move).

Run:  python scripts/proofs/proof_determinant_grading_parity.py
Exit: 0 iff every parity fact verifies (-> CLOSED-NEGATIVE supported).
"""

import os
import sys

import mpmath as mp
import sympy as sp

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from constants import G_STAR as G_STAR_NUMPY  # noqa: E402

mp.mp.dps = 40
results = []


def check(name, passed, detail=""):
    results.append((name, bool(passed)))
    print(f"  [{'PASS' if passed else 'FAIL'}] {name}" + (f"  --  {detail}" if detail else ""))


print("=" * 78)
print("Determinant-grading attempt -- G*-degree parity obstruction (CLOSED-NEGATIVE)")
print("=" * 78)

Gs = sp.symbols("G", positive=True)  # symbolic G* (transcendental: an independent symbol)

# --- 1. Master-quadratic coefficient degrees -------------------------------
print("\n[1] Master quadratic  x^2 - 16 G*^2 x + 16 G*^3 : coefficient G*-degrees")
tr = 16 * Gs**2          # trace  = coefficient of -x
det = 16 * Gs**3         # determinant = constant term
deg_tr = sp.degree(sp.Poly(tr, Gs))
deg_det = sp.degree(sp.Poly(det, Gs))
check("Tr = 16 G*^2 has EVEN degree", deg_tr % 2 == 0, f"degree {deg_tr}")
check("Det = 16 G*^3 has ODD degree", deg_det % 2 == 1, f"degree {deg_det}")
check("Det/Tr = G* (the extra ODD power, degree 1)", sp.simplify(det / tr - Gs) == 0)

# --- 2. Frozen-ingredient G*-degrees (incl. the user's hint structure) ------
print("\n[2] Frozen ingredients are all EVEN G*-degree (0 or 2)")
#   |mu_4|^2 = |Aut(E^2)| count : degree 0
#   J^2 = -I (complex structure on V_complex=Z[i]^2) : degree 0
#   winding index : degree 0
#   Watson self-energy on the 3D (conjugate-field) BCC structure : degree 2
ingredient_degree = {"|mu_4|^2 = 16": 0, "J^2 = -I": 0, "winding index": 0,
                     "Watson G_BCC(0) = G*^2/(2pi)": 2}
all_even = all(d % 2 == 0 for d in ingredient_degree.values())
check("every frozen ingredient has even G*-degree", all_even,
      ", ".join(f"{k}:deg{v}" for k, v in ingredient_degree.items()))

# --- 3. Forward determinant over the even-degree ring is even-degree --------
print("\n[3] Any forward 2x2 operator over the even ring Q[G*^2] has EVEN-degree det")
# General 2x2 matrix whose entries are arbitrary Q-combinations of {1, G*^2}
# (= the even-degree ring generated by the ingredients).  Symbolic coefficients:
c = sp.symbols("a0 a2 b0 b2 c0 c2 d0 d2")
M = sp.Matrix([[c[0] + c[1] * Gs**2, c[2] + c[3] * Gs**2],
               [c[4] + c[5] * Gs**2, c[6] + c[7] * Gs**2]])
detM = sp.expand(M.det())                      # determinant
poly = sp.Poly(detM, Gs)
odd_powers_present = any((mono[0] % 2 == 1) for mono in poly.monoms())
check("det(M) contains NO odd power of G* (even-degree ring closed under det)",
      not odd_powers_present, f"powers of G* in det: {sorted({m[0] for m in poly.monoms()})}")
# And: 16 G*^3 cannot equal det(M) for ANY rational coefficients, since det(M)
# has a ZERO coefficient at G*^3 while the target needs 16 there.
det_cube_coeff = detM.coeff(Gs, 3)          # coefficient of G*^3 in det(M)
check("det(M) = 16 G*^3 is UNSOLVABLE over the even ring (G*^3 coeff is 0, target needs 16)",
      det_cube_coeff == 0, f"det(M) coeff at G*^3 = {det_cube_coeff} (target 16) -> no match")

# --- 4. The unique even->odd route is sqrt(Watson) = the F4 prefactor --------
print("\n[4] The only even->odd route is sqrt(Watson) -- pre-reg falsifier F4")
GAMMA_QUARTER = mp.gamma(mp.mpf(1) / 4)
GAMMA_HALF = mp.gamma(mp.mpf(1) / 2)
G_STAR = GAMMA_QUARTER**2 / (mp.sqrt(2) * GAMMA_HALF**2)
watson = G_STAR**2 / (2 * mp.pi)                       # = G_BCC(0), degree 2
amplitude = mp.sqrt(watson)                            # sqrt(Watson) = G*/sqrt(2pi), degree 1
check("G_STAR matches constants.py", abs(G_STAR - mp.mpf(str(G_STAR_NUMPY))) < mp.mpf(10)**(-12),
      f"G* = {mp.nstr(G_STAR, 10)}")
check("sqrt(Watson) = G*/sqrt(2pi)  (degree-1, ODD)", abs(amplitude - G_STAR / mp.sqrt(2 * mp.pi)) < mp.mpf(10)**(-25))
# The resolution docs' prefactor R = 16 pi * sqrt(Watson) = 8 sqrt(2pi) G*  (FTD-0216 §3 / FTD-0215 §4)
R_docs = 16 * mp.pi * amplitude
check("docs' prefactor 16pi*sqrt(Watson) = 8 sqrt(2pi) G*  (the admitted Selection 1)",
      abs(R_docs - 8 * mp.sqrt(2 * mp.pi) * G_STAR) < mp.mpf(10)**(-22),
      f"= {mp.nstr(R_docs, 10)} = degree-1 in G* (F4)")

# --- 5. The user's hint, tested: it organizes EVEN content, supplies no ODD --
print("\n[5] User's hint {J^2 ; Aut(E^2)=16 ; conjugate fields each 3D} tested")
#   J^2 = -I            -> degree 0 (no G*)
#   |Aut(E^2)| = |mu_4|^2 = 16 (two conjugate Z[i] factors) -> degree 0
#   conjugate-field / 3D structure -> the BCC triple-product (cube) Watson -> degree 2
#   The norm over the 3 spatial axes gives Gamma(1/4)^4 = G*^2 (degree 2), NOT
#   Gamma(1/4)^6 = G*^3: the cube is the exponent on the 1D sum (each axis is a
#   rational, degree 0), so 3 axes -> (sum)^3 -> Gamma(1/4)^4 = degree-2.
hint_degrees = {"J^2=-I": 0, "Aut(E^2)=16": 0, "conj.3D -> Watson cube": 2}
check("hint supplies only EVEN G*-degrees (no odd-degree source)",
      all(d % 2 == 0 for d in hint_degrees.values()),
      ", ".join(f"{k}:deg{v}" for k, v in hint_degrees.items()))
# 3D Watson cube gives Gamma(1/4)^4 = G*^2 * (2 pi^2), i.e. degree 2 -- not G*^3
gamma4 = GAMMA_QUARTER**4
check("3D Watson cube -> Gamma(1/4)^4 = G*^2 * 2 pi^2  (degree 2, NOT G*^3)",
      abs(gamma4 - G_STAR**2 * 2 * mp.pi**2) < mp.mpf(10)**(-20))

# ---------------------------------------------------------------------------
print("\n" + "=" * 78)
n_pass = sum(1 for _, p in results if p)
n_tot = len(results)
print(f"PARITY FACTS: {n_pass}/{n_tot} verified.")
print("Conclusion: the determinant grading 16 G*^3 has ODD G*-degree; the frozen")
print("ingredients (incl. the J^2 / Aut(E^2)=16 / conjugate-3D hint) are EVEN-degree;")
print("forward operations keep the determinant even-degree.  The only even->odd")
print("route is sqrt(Watson)=G*/sqrt(2pi) -- the F4-forbidden amplitude/prefactor")
print("selection the resolution docs already ADMIT.  Det=16 G*^3 is NOT forward-")
print("derivable within the frozen ingredients.  VERDICT: CLOSED-NEGATIVE.")
print("=" * 78)
sys.exit(0 if n_pass == n_tot else 1)
