#!/usr/bin/env python3
"""Exact O_h x C4 collision preserving cotangent EM and tensor moments.

The joint layer-zero readout contains E/B plus the C4 FCC-dyad tensor
doublet.  Its complete pair relation has exactly nineteen additive invariants
but 10,368 singleton pair sectors.  This certificate fixes those mandatory
states and constructs equivariant involutions on every active group orbit.

A deterministic finite-field rank-greedy choice attains the complete
equivariant-option ceiling 171, two below the unrestricted-relation rank 173.
The other two cotangent-layer collisions are generated by internal-tick
conjugation and obey U C_q = C_(q-1) U.

No gravitational coefficient, target spectrum, or measured value is used.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from itertools import combinations

import networkx as nx
from sympy import Matrix
from sympy.polys.matrices import DomainMatrix

from proof_cotangent_em_tensor_pair_relation_and_activity_price import combined_value
from proof_cotangent_fcc_dyad_tensor_doublet_and_source import dyad
from proof_global_c3_cotangent_layer_hodge_maxwell_target import internal_tick
from proof_hodge_flag_pair_collision_invariant_space import add, one_particle_states
from proof_moore_bond_capacity_type_census import signed_permutation_matrices
from proof_shared_edge_hodge_flag_bcc_propagation import transform_flag


Pair = tuple[int, int]
CERTIFICATE_DATA = None


def canonical_pair(left: int, right: int) -> Pair:
    assert left != right
    return (left, right) if left < right else (right, left)


def exact_rank(matrix: Matrix) -> int:
    return DomainMatrix.from_Matrix(matrix).rank()


def main() -> None:
    global CERTIFICATE_DATA
    checks = 0
    states = one_particle_states()
    state_index = {state: index for index, state in enumerate(states)}
    size = len(states)
    assert size == 192
    checks += 1

    spatial_group = tuple(signed_permutation_matrices())
    spatial_actions = tuple(
        tuple(
            state_index[(transform_flag(matrix, state[0]), state[1])]
            for state in states
        )
        for matrix in spatial_group
    )
    phase_actions = tuple(
        tuple(
            state_index[(state[0], (state[1] + phase_shift) % 4)]
            for state in states
        )
        for phase_shift in range(4)
    )
    actions = tuple(
        tuple(phase[spatial[index]] for index in range(size))
        for spatial in spatial_actions
        for phase in phase_actions
    )
    assert len(actions) == 192
    assert len(set(actions)) == 192
    checks += 2

    pairs = tuple(combinations(range(size), 2))
    pair_set = set(pairs)

    def transform_pair(action, pair: Pair) -> Pair:
        return canonical_pair(action[pair[0]], action[pair[1]])

    keys = tuple(combined_value(state, 0) for state in states)

    def pair_key(pair: Pair):
        return add(keys[pair[0]], keys[pair[1]])

    sectors: defaultdict[tuple[object, ...], list[Pair]] = defaultdict(list)
    for pair in pairs:
        sectors[pair_key(pair)].append(pair)
    sector_histogram = Counter(map(len, sectors.values()))
    assert sector_histogram == Counter(
        {1: 10368, 2: 3264, 4: 48, 8: 120, 16: 12, 96: 1}
    )
    checks += 1

    orbit_id: dict[Pair, int] = {}
    representatives: list[Pair] = []
    orbits: list[tuple[Pair, ...]] = []
    unseen = set(pairs)
    while unseen:
        seed = min(unseen)
        orbit = tuple(sorted({transform_pair(action, seed) for action in actions}))
        identifier = len(orbits)
        for pair in orbit:
            assert pair in unseen
            orbit_id[pair] = identifier
            unseen.remove(pair)
        representatives.append(orbit[0])
        orbits.append(orbit)
    orbit_histogram = Counter(map(len, orbits))
    assert sum(map(len, orbits)) == len(pairs)
    checks += 1

    stabilizers = []
    for identifier, representative in enumerate(representatives):
        stabilizer = tuple(
            action_index
            for action_index, action in enumerate(actions)
            if transform_pair(action, representative) == representative
        )
        assert len(stabilizer) * len(orbits[identifier]) == len(actions)
        stabilizers.append(stabilizer)
        checks += 1

    identity_orbits = {
        identifier
        for identifier, representative in enumerate(representatives)
        if len(sectors[pair_key(representative)]) == 1
    }
    assert sum(len(orbits[identifier]) for identifier in identity_orbits) == 10368
    checks += 1

    self_options: defaultdict[int, list[Pair]] = defaultdict(list)
    edge_options: defaultdict[tuple[int, int], list[tuple[int, Pair]]] = defaultdict(list)
    for identifier, representative in enumerate(representatives):
        if identifier in identity_orbits:
            continue
        stabilizer = stabilizers[identifier]
        for candidate in sectors[pair_key(representative)]:
            if candidate == representative:
                continue
            if not all(
                transform_pair(actions[action_index], candidate) == candidate
                for action_index in stabilizer
            ):
                continue
            candidate_stabilizer_size = sum(
                transform_pair(action, candidate) == candidate for action in actions
            )
            if candidate_stabilizer_size != len(stabilizer):
                continue
            target_identifier = orbit_id[candidate]
            if target_identifier == identifier:
                if any(
                    transform_pair(action, representative) == candidate
                    and transform_pair(action, candidate) == representative
                    for action in actions
                ) and candidate not in self_options[identifier]:
                    self_options[identifier].append(candidate)
            else:
                key = tuple(sorted((identifier, target_identifier)))
                option = (identifier, candidate)
                if option not in edge_options[key]:
                    edge_options[key].append(option)

    active_orbits = set(range(len(orbits))) - identity_orbits
    unmatched_nodes = active_orbits - set(self_options)
    graph = nx.Graph()
    graph.add_nodes_from(unmatched_nodes)
    graph.add_edges_from(
        edge for edge in edge_options if set(edge).issubset(unmatched_nodes)
    )
    matching = nx.algorithms.matching.max_weight_matching(graph, maxcardinality=True)
    matched_nodes = {node for edge in matching for node in edge}
    unmatched_after = unmatched_nodes - matched_nodes

    print(f"pair_orbits={len(orbits)}, orbit_histogram={sorted(orbit_histogram.items())}")
    print(f"mandatory_identity_orbits={len(identity_orbits)}, states=10368")
    print(f"active_orbits={len(active_orbits)}")
    print(f"self_matchable_active_orbits={len(self_options)}")
    print(f"self_option_histogram={sorted(Counter(map(len, self_options.values())).items())}")
    print(f"distinct_compatible_edges={len(edge_options)}")
    print(f"distinct_orbit_map_options={sum(map(len, edge_options.values()))}")
    print(
        f"required_distinct_nodes={len(unmatched_nodes)}, "
        f"matching_edges={len(matching)}, unmatched_after={len(unmatched_after)}"
    )
    assert not unmatched_after
    checks += 1

    def option_transitions(identifier: int, candidate: Pair):
        source_rep = representatives[identifier]
        mapping = {}
        for action in actions:
            source = transform_pair(action, source_rep)
            output = transform_pair(action, candidate)
            if source in mapping:
                assert mapping[source] == output
            mapping[source] = output
        assert set(mapping) == set(orbits[identifier])
        return tuple(sorted(mapping.items()))

    def option_rows(identifier: int, candidate: Pair):
        rows = []
        for source, output in option_transitions(identifier, candidate):
            row = [0] * size
            for index in output:
                row[index] += 1
            for index in source:
                row[index] -= 1
            rows.append(row)
        return tuple(rows)

    prime = 1_000_003

    def reduced_add(basis: dict[int, tuple[int, ...]], row) -> bool:
        vector = [int(entry) % prime for entry in row]
        for pivot in sorted(basis):
            if vector[pivot] == 0:
                continue
            factor = vector[pivot]
            vector = [
                (entry - factor * basis_entry) % prime
                for entry, basis_entry in zip(vector, basis[pivot])
            ]
        pivot = next((index for index, entry in enumerate(vector) if entry), None)
        if pivot is None:
            return False
        inverse = pow(vector[pivot], prime - 2, prime)
        basis[pivot] = tuple(entry * inverse % prime for entry in vector)
        return True

    option_cache = {
        (identifier, candidate): option_rows(identifier, candidate)
        for identifier, candidates in self_options.items()
        for candidate in candidates
    }

    # Determine the absolute transition-rank ceiling of every admissible
    # equivariant orbit map before selecting one global involution.
    union_basis: dict[int, tuple[int, ...]] = {}
    for rows in option_cache.values():
        for row in rows:
            reduced_add(union_basis, row)
    for options in edge_options.values():
        for source_identifier, candidate in options:
            for row in option_rows(source_identifier, candidate):
                reduced_add(union_basis, row)
    print(f"all_equivariant_option_union_rank={len(union_basis)}")

    collision: dict[Pair, Pair] = {
        pair: pair
        for identifier in identity_orbits
        for pair in orbits[identifier]
    }
    modular_basis: dict[int, tuple[int, ...]] = {}
    occupied = set(matched_nodes)

    def install_orbit_map(source_rep: Pair, target: Pair) -> None:
        for action in actions:
            source = transform_pair(action, source_rep)
            output = transform_pair(action, target)
            if source in collision:
                assert collision[source] == output
            collision[source] = output

    def compatible_target(source_identifier: int, target_identifier: int) -> Pair:
        key = tuple(sorted((source_identifier, target_identifier)))
        for witness_source, candidate in edge_options[key]:
            if witness_source == source_identifier and orbit_id[candidate] == target_identifier:
                return candidate
        source_rep = representatives[source_identifier]
        return next(
            option
            for option in sectors[pair_key(source_rep)]
            if orbit_id[option] == target_identifier
            and all(
                transform_pair(actions[action_index], option) == option
                for action_index in stabilizers[source_identifier]
            )
        )

    for left_identifier, right_identifier in sorted(tuple(sorted(edge)) for edge in matching):
        target = compatible_target(left_identifier, right_identifier)
        for row in option_rows(left_identifier, target):
            reduced_add(modular_basis, row)
        install_orbit_map(representatives[left_identifier], target)
        install_orbit_map(target, representatives[left_identifier])

    chosen_self = {}
    gain_histogram = Counter()
    processing_order = sorted(
        active_orbits - occupied,
        key=lambda identifier: (len(self_options[identifier]), identifier),
    )
    for identifier in processing_order:
        best_candidate = None
        best_basis = None
        best_gain = -1
        for candidate in sorted(self_options[identifier]):
            trial_basis = dict(modular_basis)
            old_rank = len(trial_basis)
            for row in option_cache[(identifier, candidate)]:
                reduced_add(trial_basis, row)
            gain = len(trial_basis) - old_rank
            if gain > best_gain:
                best_candidate = candidate
                best_basis = trial_basis
                best_gain = gain
        assert best_candidate is not None and best_basis is not None
        chosen_self[identifier] = best_candidate
        modular_basis = best_basis
        gain_histogram[best_gain] += 1
        install_orbit_map(representatives[identifier], best_candidate)

    print(f"rank_greedy_modular_rank={len(modular_basis)}")
    print(f"rank_greedy_gain_histogram={sorted(gain_histogram.items())}")

    assert set(collision) == pair_set
    assert set(collision.values()) == pair_set
    assert all(collision[collision[pair]] == pair for pair in pairs)
    fixed_pairs = sum(collision[pair] == pair for pair in pairs)
    assert fixed_pairs == 10368
    checks += 4

    generator_matrices = (
        ((0, 1, 0), (1, 0, 0), (0, 0, 1)),
        ((0, 1, 0), (0, 0, 1), (1, 0, 0)),
        ((-1, 0, 0), (0, 1, 0), (0, 0, 1)),
    )
    generator_actions = [
        tuple(
            state_index[(transform_flag(matrix, state[0]), state[1])]
            for state in states
        )
        for matrix in generator_matrices
    ] + [phase_actions[1]]
    for pair in pairs:
        outgoing = collision[pair]
        assert pair_key(outgoing) == pair_key(pair)
        for action in generator_actions:
            assert collision[transform_pair(action, pair)] == transform_pair(
                action, outgoing
            )
            checks += 1

    selected_rows = []
    for pair in pairs:
        outgoing = collision[pair]
        row = [0] * size
        for index in outgoing:
            row[index] += 1
        for index in pair:
            row[index] -= 1
        selected_rows.append(row)
    selected_rank = exact_rank(Matrix(selected_rows))
    selected_nullity = size - selected_rank
    print(f"selected_transition_rank={selected_rank}, nullity={selected_nullity}")
    assert len(union_basis) == 171
    assert selected_rank == 171
    assert selected_nullity == 21
    checks += 3

    # Generate the q=2 and q=1 collisions by internal-tick conjugation.
    internal_action = tuple(state_index[internal_tick(state)] for state in states)
    inverse_internal = [0] * size
    for source, target in enumerate(internal_action):
        inverse_internal[target] = source

    def action_power(action, exponent: int):
        result = tuple(range(size))
        for _ in range(exponent):
            result = tuple(action[index] for index in result)
        return result

    powers = tuple(action_power(internal_action, exponent) for exponent in range(3))
    inverse_powers = tuple(action_power(tuple(inverse_internal), exponent) for exponent in range(3))
    layer_collisions = []
    for layer in range(3):
        exponent = (-layer) % 3
        forward = powers[exponent]
        backward = inverse_powers[exponent]
        layer_collision = {}
        for pair in pairs:
            base_input = transform_pair(backward, pair)
            layer_collision[pair] = transform_pair(forward, collision[base_input])
        layer_collisions.append(layer_collision)

    for layer, layer_collision in enumerate(layer_collisions):
        layer_keys = tuple(combined_value(state, layer) for state in states)

        def layer_pair_key(pair: Pair):
            return add(layer_keys[pair[0]], layer_keys[pair[1]])

        assert all(layer_collision[layer_collision[pair]] == pair for pair in pairs)
        assert all(layer_pair_key(layer_collision[pair]) == layer_pair_key(pair) for pair in pairs)
        next_layer = (layer - 1) % 3
        for pair in pairs:
            advanced = transform_pair(internal_action, pair)
            assert transform_pair(internal_action, layer_collision[pair]) == (
                layer_collisions[next_layer][advanced]
            )
            checks += 1
        checks += 2

    corrections = []
    extra_eg_rows = []
    for layer, layer_collision in enumerate(layer_collisions):
        correction = Matrix.zeros(size, size)
        for before in pairs:
            after = layer_collision[before]
            if before >= after:
                continue
            delta = [0] * size
            for index in after:
                delta[index] += 1
            for index in before:
                delta[index] -= 1
            column = Matrix(delta)
            correction -= 2 * column * column.T
        assert correction == correction.T
        assert exact_rank(correction) == 171
        known_rows = Matrix.vstack(
            Matrix([[1] * size]),
            *(
                Matrix([[combined_value(state, layer)[component] for state in states]])
                for component in range(18)
            ),
        )
        layer_dyads = tuple(dyad(state, layer) for state in states)
        eg_rows = Matrix.vstack(
            Matrix([[matrix[0, 0] - matrix[1, 1] for matrix in layer_dyads]]),
            Matrix([[
                2 * matrix[2, 2] - matrix[0, 0] - matrix[1, 1]
                for matrix in layer_dyads
            ]]),
        )
        complete_rows = Matrix.vstack(known_rows, eg_rows)
        assert exact_rank(complete_rows) == 21
        assert complete_rows * correction == Matrix.zeros(21, size)
        extra_eg_rows.append(eg_rows)
        corrections.append(correction)
        checks += 4

    CERTIFICATE_DATA = {
        "states": states,
        "collisions": tuple(layer_collisions),
        "corrections": tuple(corrections),
        "internal_action": internal_action,
        "extra_eg_rows": tuple(extra_eg_rows),
    }

    print(
        "PASS: cotangent EM+tensor equivariant collision "
        f"({checks} exact checks)"
    )
    print("mandatory fixed pairs=10368; all 7968 active pairs are involutively matched")
    print("all layers rank171/nullity21 and obey U C_q=C_(q-1) U")
    print("two surplus invariants=phase-blind FCC-dyad Eg diagonal shear")
    print("Open: classify surplus pair and test joint EM/tensor Bloch kernel")


if __name__ == "__main__":
    main()
